receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :4317
      http:
        endpoint: :4318
processors:
  batch:
    timeout: 10s
    send_batch_size: 8192
    send_batch_max_size: 10000
  probabilistic_sampler/traces:
    sampling_percentage: ${env:TRACE_SAMPLING_PERCENTAGE:-1}
  cumulativetodelta:
  resource/metrics:
    attributes:
      - key: qualifier
        value: ${env:QUALIFIER}
        action: upsert
  resource/remove_default_attributes:
    attributes:
      - key: telemetry.sdk.name
        action: delete
      - key: telemetry.sdk.version
        action: delete
      - key: telemetry.sdk.language
        action: delete
      - key: service.name
        action: delete
extensions:
  health_check:
    endpoint: :13133
exporters:
  awsemf:
    namespace: 'OpenSearchMigrations'
    dimension_rollup_option: NoDimensionRollup # Reduce number of metrics by only publishing with all dimensions
    resource_to_telemetry_conversion:
      enabled: true
  awsxray:
    index_all_attributes: true
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, resource/remove_default_attributes, resource/metrics, cumulativetodelta]
      exporters: [awsemf]
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler/traces, batch]
      exporters: [awsxray]
