receivers:
  otlp:
    protocols:
      grpc:
processors:
  batch:
    timeout: 10s
    send_batch_size: 8192
    send_batch_max_size: 10000
extensions:
  health_check:
exporters:
  awsemf:
    namespace: 'OpenSearchMigrations'
  awsxray:
    index_all_attributes: true
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsemf]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]
