receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :4317
      http:
        endpoint: :4318
processors:
extensions:
  zpages:
    endpoint: :55679
  pprof:
    endpoint: :1888
  health_check:
    endpoint: :13133
exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
service:
  extensions: [zpages, pprof, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors:
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors:
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors:
      exporters: [debug]
