#!/usr/bin/env python3
import os
import subprocess
import sys
from contextlib import contextmanager

ABORT = 1

@contextmanager
def cd(new_dir):
    '''Navigate to a directory in a context and then return to original directory.'''
    prev_dir = os.getcwd()
    os.chdir(os.path.expanduser(new_dir))
    try:
        yield
    finally:
        os.chdir(prev_dir)

if __name__ == '__main__':
    try:
        abort = False
        abort_messages = []
        skip_flake8 = False
        FLAKE8_CFG_FILE = '.flake8'

        # Get base folder of repo
        loc_proc = subprocess.Popen('git rev-parse --show-toplevel'.split(), stdout=subprocess.PIPE)
        repo_base_folder = loc_proc.communicate()[0].decode('utf-8').strip()
        flake8_config_path = os.path.join(repo_base_folder, FLAKE8_CFG_FILE)

        # Run pytests
#        print('_______________________' + 'Running Unit Tests' + '_______________________')
#        with cd(repo_base_folder + '/<older>'):
#            test_proc = subprocess.Popen(['./manage.py', 'test', '--noinput'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
#            out, err = test_proc.communicate()
#            err_s = err.decode('utf-8')
#            out_s = out.decode('utf-8')
#            if 'FAILED' in err_s or 'ERROR' in err_s:
#                abort_messages.append('All unit tests did not succeed. Please fix code/tests before committing.')
#                abort = True
#        print('_______________________' + 'Unit Test Output' + '_______________________')
#        print(out_s)
#        print('_______________________' + 'Unit Test Error' + '________________________')
#        print(err_s)

        if not os.path.isfile(flake8_config_path):
            skip_flake8 = True
            print('Warning: Could not find flake8 config file at repo base ({}).'.format(flake8_config_path))

        if skip_flake8:
            print('________________________' + 'Skipping Flake8' + '_______________________')
        else:
            print('________________________' + 'Running Flake8' + '_______________________')
            flake8_proc = subprocess.Popen('python3 -m flake8 --config={}'.format(flake8_config_path).split(),
                                            stdout=subprocess.PIPE)
            flake_output = flake8_proc.communicate()[0].decode('utf-8')
            num_flake8_errors = len(flake_output.splitlines())
            if num_flake8_errors:
                print(flake_output)
                abort_messages.append(('{} flake8 errors. Please fix code style before commiting.'.format(num_flake8_errors)))
                abort = True

    except Exception as error:
        abort = True
        print('Exception occurred during git pre-commit validation:\n{}.'.format(str(error)), file=sys.stderr)
    finally:
        if abort:
            print('________________________' + 'Aborting Commit' + '_______________________')
            for msg in abort_messages:
                print(msg)
            sys.exit(ABORT)
        print('___________________' + 'pre-commit checks passed' + '___________________')

