package org.opensearch.migrations.coreutils;

public enum MetricsEvent {
    CONNECTION_OPENED,
    CONNECTION_CLOSED,
    BACKSIDE_HANDLER_CHANNEL_ACTIVE,
    BACKSIDE_HANDLER_CHANNEL_CLOSED,
    BACKSIDE_HANDLER_EXCEPTION,
    RECORD_SENT_TO_KAFKA,
    RECORD_FAILED_TO_KAFKA,
    RECORD_RECEIVED_FROM_KAFKA,
    RECORD_FAILED_FROM_KAFKA,
    WRITING_REQUEST_COMPONENT_FAILED,
    WROTE_REQUEST_COMPONENT,
    TEMPORARILY_UNNAMED_EVENT
}