{{- $fullname := include "generic.fullname" . -}}
{{- if not (lookup "v1" "ConfigMap" .Release.Namespace $fullname) }}
{{- $weight := (dig "weights" "sharedConfigMaps" 0 (.Values | merge (dict)))  }}

{{- range $key, $param := .Values.globalParameters }}
  {{- include "generic.createConfigMap"
      (dict
      "Name" (kebabcase $key)
      "AllowRuntimeOverride" (hasKey $param "allowRuntimeOverride" | ternary $param.allowRuntimeOverride true)
      "Value" $param.object
      "Weight" $weight)
  }}
{{- end -}}
{{- end -}}