apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: full-migration-
spec:
  workflowTemplateRef:
    name: full-migration
  entrypoint: main
  arguments:
    parameters:
      - name: snapshotRepoConfigs
        value: |
          {
              "mainRepo": {
                  "aws_region": "us-east-2",
                  "endpoint": "http://ma-localstack:4566",
                  "repoPath": "s3://snapshot"
              }
          }
      - name: sourceClusters
        value: |
          {
            "source1": {
               "endpoint": "https://elasticsearch-master-headless:9200",
               "allowInsecure": true,
               "authConfig": {
                   "username": "admin",
                   "password": "admin"
               }
           }
          },
      - name: targetClusters
        value: |
          {
              "target1": {
                  "endpoint": "https://opensearch-cluster-master-headless:9200",
                  "allowInsecure": true,
                  "authConfig": {
                      "username": "admin",
                      "password": "admin"
                  }
              }
          }
      - name: sourceMigrationConfigs
        value: |
            [
                {
                    "source": "source1",
                    "targets": ["target1"],
            
                    "snapshotExtractAndLoadConfigs": [
                        {          
                            "snapshotConfig": {
                                "snapshotName": "indices_3_and_4",
                                "repoConfig": "mainRepo"
                                "indices": [ "index_3", "index_4"],
                            },
                            "migrations": [
                                {
                                    "metadata": {
                                      "enabled": true,
                                    },
                                    "documentBackfillConfig":
                                        "enabled": true,
                                        "batchSize": 1000,
                                        "concurrency": 4
                                }
                            ]
                        }
                    ],
                    "replayerConfig": {
                         "enabled": true
                    }
                }
            ]
