#!/bin/sh
# =============================================================================
# generate-private-ecr-values.sh
#
# Generates a helm values override file that rewrites all image and chart
# repository references to point at a private ECR registry.
#
# Usage: ./generate-private-ecr-values.sh <ecr-host> > private-ecr-values.yaml
# Example: ./generate-private-ecr-values.sh 123456789012.dkr.ecr.us-east-1.amazonaws.com
# =============================================================================
set -euo pipefail

ECR="${1:-}"
if [ -z "$ECR" ]; then
  echo "Usage: $0 <ecr-host> > private-ecr-values.yaml" >&2
  exit 1
fi

M="$ECR/mirrored"

cat <<EOF
# Generated by generate-private-ecr-values.sh
# ECR Registry: ${ECR}
# Pass to aws-bootstrap.sh via --helm-values

# --- Chart repositories (OCI from ECR) ---
charts:
  cert-manager:
    repository: "oci://${ECR}/charts/cert-manager"
    version: "v1.17.2"
    values:
      image:
        repository: "${M}/quay.io/jetstack/cert-manager-controller"
      webhook:
        image:
          repository: "${M}/quay.io/jetstack/cert-manager-webhook"
      cainjector:
        image:
          repository: "${M}/quay.io/jetstack/cert-manager-cainjector"
      startupapicheck:
        image:
          repository: "${M}/quay.io/jetstack/cert-manager-startupapicheck"

  strimzi-kafka-operator:
    repository: "oci://${ECR}/charts/strimzi-kafka-operator"
    values:
      image:
        registry: "${M}/quay.io"
      defaultImageRegistry: "${M}/quay.io"
      kafka:
        image:
          registry: "${M}/quay.io"

  argo-workflows:
    repository: "oci://${ECR}/charts/argo-workflows"
    values:
      images:
        tag: v3.7.8
      controller:
        image:
          registry: "${M}/quay.io"
          repository: argoproj/workflow-controller
      executor:
        image:
          registry: "${M}/quay.io"
          repository: argoproj/argoexec
      server:
        image:
          registry: "${M}/quay.io"
          repository: argoproj/argocli

  fluent-bit:
    repository: "oci://${ECR}/charts/fluent-bit"
    values:
      image:
        repository: "${M}/cr.fluentbit.io/fluent/fluent-bit"

  kube-prometheus-stack:
    repository: "oci://${ECR}/charts/kube-prometheus-stack"
    values:
      prometheusOperator:
        image:
          registry: "${M}/quay.io"
        admissionWebhooks:
          patch:
            image:
              registry: "${M}/registry.k8s.io"
          deployment:
            image:
              registry: "${M}/quay.io"
        prometheusConfigReloader:
          image:
            registry: "${M}/quay.io"
      prometheus:
        prometheusSpec:
          image:
            registry: "${M}/quay.io"
      nodeExporter:
        enabled: true
      prometheus-node-exporter:
        image:
          registry: "${M}/quay.io"
      kube-state-metrics:
        image:
          registry: "${M}/registry.k8s.io"

  etcd-operator:
    repository: "oci://${ECR}/charts/etcd-operator"
    values:
      image:
        repository: "${M}/ghcr.io/aenix-io/etcd-operator"
      kubeRbacProxy:
        image:
          repository: "${M}/gcr.io/kubebuilder/kube-rbac-proxy"

  opentelemetry-operator:
    repository: "oci://${ECR}/charts/opentelemetry-operator"
    values:
      manager:
        image:
          repository: "${M}/ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator"
      kubeRBACProxy:
        image:
          repository: "${M}/quay.io/brancz/kube-rbac-proxy"

  localstack:
    repository: "oci://${ECR}/charts/localstack"
    values:
      image:
        repository: "${M}/docker.io/localstack/localstack"

  grafana:
    repository: "oci://${ECR}/charts/grafana"
    values:
      image:
        repository: "${M}/docker.io/grafana/grafana"

  jaeger:
    repository: "oci://${ECR}/charts/jaeger"
    values:
      agent:
        image: "${M}/docker.io/jaegertracing/jaeger-agent"
      collector:
        image: "${M}/docker.io/jaegertracing/jaeger-collector"
      query:
        image: "${M}/docker.io/jaegertracing/jaeger-query"
      storage:
        cassandra:
          image: "${M}/docker.io/library/cassandra"

  kyverno:
    repository: "oci://${ECR}/charts/kyverno"
    values:
      image:
        registry: "${M}/reg.kyverno.io"
      initImage:
        registry: "${M}/reg.kyverno.io"
      cleanupJobs:
        admissionReports:
          image:
            registry: "${M}/docker.io"
        clusterAdmissionReports:
          image:
            registry: "${M}/docker.io"

# --- Direct template image overrides ---
defaultBucketConfiguration:
  bucketOperationImage: "${M}/docker.io/amazon/aws-cli:2.25.11"

# --- ECR auth for installer job ---
ecrAuth:
  registry: "${ECR}"
EOF
