#!/bin/bash
# =============================================================================
# generatePrivateEcrValues.sh
#
# Generates a helm values override that points all chart repositories and
# image references to a private ECR mirror.
#
# Can be run standalone or sourced by aws-bootstrap.sh.
#
# Usage: ./generatePrivateEcrValues.sh <ecr-host> > private-ecr-values.yaml
# =============================================================================
set -euo pipefail

generate_private_ecr_values() {
  local ECR="$1"
  local M="$ECR/mirrored"

  cat <<EOF
# Generated by generatePrivateEcrValues.sh
# ECR Registry: ${ECR}

# --- ECR auth for installer job (OCI chart pulls) ---
ecrAuth:
  registry: "${ECR}"

# --- Chart repositories (OCI from ECR) + image overrides ---
charts:
  cert-manager:
    repository: "oci://${ECR}/charts/cert-manager"
    version: "v1.17.2"
    values:
      image:
        repository: "${M}/quay.io/jetstack/cert-manager-controller"
      webhook:
        image:
          repository: "${M}/quay.io/jetstack/cert-manager-webhook"
      cainjector:
        image:
          repository: "${M}/quay.io/jetstack/cert-manager-cainjector"
      startupapicheck:
        image:
          repository: "${M}/quay.io/jetstack/cert-manager-startupapicheck"

  strimzi-kafka-operator:
    repository: "oci://${ECR}/charts/strimzi-kafka-operator"
    values:
      image:
        registry: "${M}/quay.io"
      defaultImageRegistry: "${M}/quay.io"
      kafka:
        image:
          registry: "${M}/quay.io"
      buildah:
        image:
          registry: "${M}/quay.io"

  argo-workflows:
    repository: "oci://${ECR}/charts/argo-workflows"
    values:
      images:
        tag: v4.0.3
      crds:
        upgradeJob:
          image:
            repository: "${M}/registry.k8s.io/kubectl"
      controller:
        image:
          registry: "${M}/quay.io"
          repository: argoproj/workflow-controller
      executor:
        image:
          registry: "${M}/quay.io"
          repository: argoproj/argoexec
      server:
        image:
          registry: "${M}/quay.io"
          repository: argoproj/argocli

  fluent-bit:
    repository: "oci://${ECR}/charts/fluent-bit"
    values:
      image:
        repository: "${M}/cr.fluentbit.io/fluent/fluent-bit"
      testFramework:
        image:
          repository: "${M}/mirror.gcr.io/library/busybox"
          tag: latest

  kube-prometheus-stack:
    repository: "oci://${ECR}/charts/kube-prometheus-stack"
    values:
      prometheusOperator:
        image:
          registry: "${M}/quay.io"
        admissionWebhooks:
          patch:
            image:
              registry: "${M}/registry.k8s.io"
        prometheusConfigReloader:
          image:
            registry: "${M}/quay.io"
      prometheus:
        prometheusSpec:
          image:
            registry: "${M}/quay.io"
          thanos:
            image: "${M}/quay.io/thanos/thanos:v0.38.0"
      alertmanager:
        alertmanagerSpec:
          image:
            registry: "${M}/quay.io"
      nodeExporter:
        enabled: true
      prometheus-node-exporter:
        image:
          registry: "${M}/quay.io"
      kube-state-metrics:
        image:
          registry: "${M}/registry.k8s.io"
      thanosRuler:
        thanosRulerSpec:
          image:
            registry: "${M}/quay.io"
      grafana:
        image:
          registry: "${ECR}"
          repository: "mirrored/mirror.gcr.io/grafana/grafana"
        sidecar:
          image:
            registry: "${M}/quay.io"
        testFramework:
          image:
            repository: "${M}/mirror.gcr.io/bats/bats"
            tag: "v1.4.1"

  opentelemetry-operator:
    repository: "oci://${ECR}/charts/opentelemetry-operator"
    values:
      manager:
        image:
          repository: "${M}/ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator"
        collectorImage:
          repository: "${M}/public.ecr.aws/aws-observability/aws-otel-collector"
      kubeRBACProxy:
        image:
          repository: "${M}/quay.io/brancz/kube-rbac-proxy"

  localstack:
    repository: "oci://${ECR}/charts/localstack"
    values:
      image:
        repository: "${M}/mirror.gcr.io/localstack/localstack"

  grafana:
    repository: "oci://${ECR}/charts/grafana"
    values:
      image:
        registry: "${ECR}"
        repository: "mirrored/mirror.gcr.io/grafana/grafana"
      sidecar:
        image:
          registry: "${M}/quay.io"
      testFramework:
        image:
          repository: "${M}/mirror.gcr.io/bats/bats"
          tag: "v1.4.1"

  jaeger:
    repository: "oci://${ECR}/charts/jaeger"
    values:
      agent:
        image: "${M}/mirror.gcr.io/jaegertracing/jaeger-agent"
      collector:
        image: "${M}/mirror.gcr.io/jaegertracing/jaeger-collector"
      query:
        image: "${M}/mirror.gcr.io/jaegertracing/jaeger-query"
      storage:
        cassandra:
          image: "${M}/mirror.gcr.io/library/cassandra"

  kyverno:
    repository: "oci://${ECR}/charts/kyverno"
    values:
      image:
        registry: "${M}/reg.kyverno.io"
      initImage:
        registry: "${M}/reg.kyverno.io"
      webhooksCleanup:
        image:
          registry: "${M}/registry.k8s.io"
      test:
        image:
          registry: "${M}/ghcr.io"

  aws-privateca-issuer:
    repository: "oci://${ECR}/charts/aws-privateca-issuer"
    version: "v1.4.0"
    values:
      image:
        repository: "${M}/public.ecr.aws/k1n1h4h4/cert-manager-aws-privateca-issuer"

  aws-mountpoint-s3-csi-driver:
    repository: "oci://${ECR}/charts/aws-mountpoint-s3-csi-driver"
    values:
      image:
        repository: "${M}/public.ecr.aws/mountpoint-s3-csi-driver/aws-mountpoint-s3-csi-driver"
      sidecars:
        nodeDriverRegistrar:
          image:
            repository: "${M}/public.ecr.aws/csi-components/csi-node-driver-registrar"
        livenessProbe:
          image:
            repository: "${M}/public.ecr.aws/csi-components/livenessprobe"

  ack-acmpca-controller:
    repository: "oci://${ECR}/charts/acmpca-chart"
    version: "1.2.2"
    values:
      image:
        repository: "${M}/public.ecr.aws/aws-controllers-k8s/acmpca-controller"
        tag: "1.2.2"

  ack-cloudwatch-controller:
    repository: "oci://${ECR}/charts/cloudwatch-chart"
    version: "1.4.2"
    values:
      image:
        repository: "${M}/public.ecr.aws/aws-controllers-k8s/cloudwatch-controller"
        tag: "1.4.2"

# --- Direct template image overrides ---
defaultBucketConfiguration:
  bucketOperationImage: "${M}/mirror.gcr.io/amazon/aws-cli:2.25.11"

# --- Otel collector (hardcoded in template, override via values) ---
otelCollectorImage: "${M}/public.ecr.aws/aws-observability/aws-otel-collector:v0.43.3"

# --- Coordinator cluster image (used by RFS workflow via configmap) ---
images:
  coordinatorCluster:
    repository: "${M}/mirror.gcr.io/opensearchproject/opensearch"
    tag: "3.1.0"
EOF
}

# --- CLI entrypoint ---
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  ECR="${1:-}"
  if [ -z "$ECR" ]; then
    echo "Usage: $0 <ecr-host> > private-ecr-values.yaml" >&2
    exit 1
  fi
  generate_private_ecr_values "$ECR"
fi
