#!/bin/sh
# =============================================================================
# generatePrivateEcrValues.sh
#
# Generates a helm values override that:
# 1. Points all chart repositories to OCI ECR
# 2. Overrides all image references to use the ECR mirror
# 3. Enables ECR auth for the installer job
#
# Usage: ./generate-private-ecr-values.sh <ecr-host> > private-ecr-values.yaml
# =============================================================================
set -euo pipefail

ECR="${1:-}"
if [ -z "$ECR" ]; then
  echo "Usage: $0 <ecr-host> > private-ecr-values.yaml" >&2
  exit 1
fi

M="$ECR/mirrored"

cat <<EOF
# Generated by generate-private-ecr-values.sh
# ECR Registry: ${ECR}

# --- ECR auth for installer job (OCI chart pulls) ---
ecrAuth:
  registry: "${ECR}"

# --- Chart repositories (OCI from ECR) + image overrides ---
charts:
  cert-manager:
    repository: "oci://${ECR}/charts/cert-manager"
    version: "v1.17.2"
    values:
      image:
        repository: "${M}/quay.io/jetstack/cert-manager-controller"
      webhook:
        image:
          repository: "${M}/quay.io/jetstack/cert-manager-webhook"
      cainjector:
        image:
          repository: "${M}/quay.io/jetstack/cert-manager-cainjector"
      startupapicheck:
        image:
          repository: "${M}/quay.io/jetstack/cert-manager-startupapicheck"

  strimzi-kafka-operator:
    repository: "oci://${ECR}/charts/strimzi-kafka-operator"
    values:
      image:
        registry: "${M}/quay.io"
      defaultImageRegistry: "${M}/quay.io"
      kafka:
        image:
          registry: "${M}/quay.io"

  argo-workflows:
    repository: "oci://${ECR}/charts/argo-workflows"
    values:
      images:
        tag: v3.7.9
      controller:
        image:
          registry: "${M}/quay.io"
          repository: argoproj/workflow-controller
      executor:
        image:
          registry: "${M}/quay.io"
          repository: argoproj/argoexec
      server:
        image:
          registry: "${M}/quay.io"
          repository: argoproj/argocli

  fluent-bit:
    repository: "oci://${ECR}/charts/fluent-bit"
    values:
      image:
        repository: "${M}/cr.fluentbit.io/fluent/fluent-bit"
      testFramework:
        image:
          repository: "${M}/docker.io/library/busybox"
          tag: latest

  kube-prometheus-stack:
    repository: "oci://${ECR}/charts/kube-prometheus-stack"
    values:
      prometheusOperator:
        image:
          registry: "${M}/quay.io"
        admissionWebhooks:
          patch:
            image:
              registry: "${M}/registry.k8s.io"
        prometheusConfigReloader:
          image:
            registry: "${M}/quay.io"
      prometheus:
        prometheusSpec:
          image:
            registry: "${M}/quay.io"
          thanos:
            image: "${M}/quay.io/thanos/thanos:v0.38.0"
      alertmanager:
        alertmanagerSpec:
          image:
            registry: "${M}/quay.io"
      nodeExporter:
        enabled: true
      prometheus-node-exporter:
        image:
          registry: "${M}/quay.io"
      kube-state-metrics:
        image:
          registry: "${M}/registry.k8s.io"
      thanosRuler:
        thanosRulerSpec:
          image:
            registry: "${M}/quay.io"
      grafana:
        image:
          registry: "${ECR}"
          repository: "mirrored/docker.io/grafana/grafana"
        sidecar:
          image:
            registry: "${M}/quay.io"
        testFramework:
          image:
            repository: "${M}/docker.io/bats/bats"
            tag: "v1.4.1"

  etcd-operator:
    repository: "oci://${ECR}/charts/etcd-operator"
    values:
      etcdOperator:
        image:
          repository: "${M}/ghcr.io/aenix-io/etcd-operator"
      kubeRbacProxy:
        image:
          repository: "${M}/gcr.io/kubebuilder/kube-rbac-proxy"

  opentelemetry-operator:
    repository: "oci://${ECR}/charts/opentelemetry-operator"
    values:
      manager:
        image:
          repository: "${M}/ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator"
        collectorImage:
          repository: "${M}/public.ecr.aws/aws-observability/aws-otel-collector"
      kubeRBACProxy:
        image:
          repository: "${M}/quay.io/brancz/kube-rbac-proxy"

  cloudnative-pg:
    repository: "oci://${ECR}/charts/cloudnative-pg"
    values:
      image:
        repository: "${M}/ghcr.io/cloudnative-pg/cloudnative-pg"

  localstack:
    repository: "oci://${ECR}/charts/localstack"
    values:
      image:
        repository: "${M}/docker.io/localstack/localstack"

  grafana:
    repository: "oci://${ECR}/charts/grafana"
    values:
      image:
        registry: "${ECR}"
        repository: "mirrored/docker.io/grafana/grafana"
      sidecar:
        image:
          registry: "${M}/quay.io"
      testFramework:
        image:
          repository: "${M}/docker.io/bats/bats"
          tag: "v1.4.1"

  jaeger:
    repository: "oci://${ECR}/charts/jaeger"
    values:
      agent:
        image: "${M}/docker.io/jaegertracing/jaeger-agent"
      collector:
        image: "${M}/docker.io/jaegertracing/jaeger-collector"
      query:
        image: "${M}/docker.io/jaegertracing/jaeger-query"
      storage:
        cassandra:
          image: "${M}/docker.io/library/cassandra"

  kyverno:
    repository: "oci://${ECR}/charts/kyverno"
    values:
      image:
        registry: "${M}/reg.kyverno.io"
      initImage:
        registry: "${M}/reg.kyverno.io"
      cleanupJobs:
        admissionReports:
          image:
            registry: "${M}/docker.io"
        clusterAdmissionReports:
          image:
            registry: "${M}/docker.io"

# --- Direct template image overrides ---
defaultBucketConfiguration:
  bucketOperationImage: "${M}/docker.io/amazon/aws-cli:2.25.11"

# --- Otel collector (hardcoded in template, override via values) ---
otelCollectorImage: "${M}/public.ecr.aws/aws-observability/aws-otel-collector:v0.43.3"

# --- Coordinator cluster image (used by RFS workflow via configmap) ---
images:
  coordinatorCluster:
    repository: "${M}/docker.io/opensearchproject/opensearch"
    tag: "3.1.0"

# --- Etcd data image (used by etcd-operator CRD) ---
etcdCluster:
  image: "${M}/quay.io/coreos/etcd:v3.5.12"

# --- CNPG PostgreSQL data image (used by CNPG operator at runtime) ---
cnpgCluster:
  imageName: "${M}/ghcr.io/cloudnative-pg/postgresql:17.2"
EOF
