exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    send_timestamps: true
    metric_expiration: 5m
    enable_open_metrics: true

service:
  pipelines:
    metrics:
      exporters: [ prometheus ]