apiVersion: 1
datasources:
  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    readOnly: false
    jsonData: {}
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      exemplarTraceIdDestinations:
        - name: trace_id
          urlDisplayLabel: Jaeger
    readOnly: false
