#!/usr/bin/env bash
# =============================================================================
# assemble-bootstrap.sh
#
# Produces the release artifacts for the EKS deploy path:
#
#   dist/aws-bootstrap.sh            backwards-compat shim (curl-friendly)
#   dist/migration-assistant-cli-<version>.tar.gz
#                                     full CLI tarball (bin + lib + skills)
#
# The shim is a single self-contained file that downloads + extracts the
# tarball into ~/.opensearch-migrate/cli/<version>/ on first run, then
# execs the unpacked migration-assistant binary. Equivalent UX to the old
# self-contained aws-bootstrap.sh but with the actual logic loaded from
# the tarball — so we only ship 50 lines of curl/tar/exec instead of
# inlining 1700 lines.
#
# Usage:
#   ./assemble-bootstrap.sh [--output-dir <path>] [--cli-version <ver>]
#
# Default: deployment/k8s/aws/dist/
# =============================================================================
set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_DIR="$SCRIPT_DIR/cli"
OUTPUT_DIR="${SCRIPT_DIR}/dist"

# CLI_VERSION resolution order:
#   1. CLI_VERSION env var / --cli-version flag (release pipelines pin this).
#   2. Repo's git short-SHA, prefixed with "0.0.0-dev-" so each dev/CI
#      build lands in its own cache slot. The shim's
#      "is the binary already installed?" check is keyed on the version
#      string baked into the shim — without per-build versions, an
#      operator who runs ./assemble-bootstrap.sh + ./dist/aws-bootstrap.sh
#      on a fresh build keeps executing the FIRST install they ever did.
#   3. Hardcoded "0.0.0-dev" as a last-resort fallback for non-git checkouts.
if [[ -z "${CLI_VERSION:-}" ]]; then
  if git_sha=$(git -C "$SCRIPT_DIR" rev-parse --short=10 HEAD 2>/dev/null); then
    CLI_VERSION="0.0.0-dev-${git_sha}"
  else
    CLI_VERSION="0.0.0-dev"
  fi
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir)  OUTPUT_DIR="$2";  shift 2 ;;
    --cli-version) CLI_VERSION="$2"; shift 2 ;;
    *) printf 'unknown arg: %s\n' "$1" >&2; exit 64 ;;
  esac
done

mkdir -p "$OUTPUT_DIR"

# 1. Tarball the CLI tree.
#
# Vendored payload: privateEcrManifest.sh (the chart's image list, source
# of truth for crane mirror). Tagged-release URL works at runtime, but the
# in-repo copy is what this CLI version was tested against; bundling it
# means `migration-assistant` is self-contained in the CI/local build flow
# and only fetches at runtime when the operator overrides MA_VERSION.
TARBALL="$OUTPUT_DIR/migration-assistant-cli-${CLI_VERSION}.tar.gz"
stage=$(mktemp -d)
mkdir -p "$stage/migration-assistant-cli-${CLI_VERSION}/skills"
cp -R "$CLI_DIR/bin" "$CLI_DIR/lib" \
      "$CLI_DIR/install.sh" "$CLI_DIR/README.md" \
      "$stage/migration-assistant-cli-${CLI_VERSION}/"
cp -R "$CLI_DIR/skills/." \
      "$stage/migration-assistant-cli-${CLI_VERSION}/skills/"

MANIFEST_SRC="$SCRIPT_DIR/../charts/aggregates/migrationAssistantWithArgo/scripts/privateEcrManifest.sh"
if [[ -f "$MANIFEST_SRC" ]]; then
  cp "$MANIFEST_SRC" \
     "$stage/migration-assistant-cli-${CLI_VERSION}/skills/privateEcrManifest.sh"
else
  printf 'ERROR: %s missing; cannot bundle image manifest\n' \
    "$MANIFEST_SRC" >&2
  exit 1
fi

# Pull LICENSE from the repo root (Apache-2.0) rather than vendoring a
# per-CLI copy. Hard-fail if absent so the published tarball never lacks
# its license.
LICENSE_SRC="$SCRIPT_DIR/../../../LICENSE"
if [[ -f "$LICENSE_SRC" ]]; then
  cp "$LICENSE_SRC" "$stage/migration-assistant-cli-${CLI_VERSION}/LICENSE"
else
  printf 'ERROR: %s missing; refusing to build a tarball without a LICENSE\n' \
    "$LICENSE_SRC" >&2
  exit 1
fi
tar -czf "$TARBALL" -C "$stage" "migration-assistant-cli-${CLI_VERSION}"
rm -rf "$stage"

# 2. Emit the curl-pipe shim. The shim downloads the tarball, unpacks it,
#    and execs the CLI. No repo checkout required by the operator.
cat > "$OUTPUT_DIR/aws-bootstrap.sh" <<SHIM
#!/usr/bin/env bash
# Self-contained migration-assistant bootstrap.
# Generated by deployment/k8s/aws/assemble-bootstrap.sh
# CLI version: ${CLI_VERSION}
set -o errexit
set -o nounset
set -o pipefail

CLI_VERSION='${CLI_VERSION}'
PREFIX="\${MIGRATE_PREFIX:-\$HOME/.opensearch-migrate/cli/\$CLI_VERSION}"
BIN="\$PREFIX/bin/migration-assistant"
TARBALL_NAME="migration-assistant-cli-\${CLI_VERSION}.tar.gz"

# Tarball resolution order (each can be overridden):
#   1. \$MIGRATE_TARBALL_URL — operator-supplied URL (use this for fork
#      previews / staging mirrors).
#   2. sibling tarball next to this shim (assemble-bootstrap.sh ships
#      both files together; Jenkins/CI flow lives here).
#   3. \$MIGRATE_REPO override of the upstream repo (also useful for forks).
#   4. opensearch-project upstream release (the published curl-pipe path).
DEFAULT_REPO='opensearch-project/opensearch-migrations'
REPO="\${MIGRATE_REPO:-\$DEFAULT_REPO}"
TARBALL_URL="\${MIGRATE_TARBALL_URL:-https://github.com/\${REPO}/releases/download/\${CLI_VERSION}/\${TARBALL_NAME}}"

SHIM_DIR=\$(cd "\$(dirname "\${BASH_SOURCE[0]:-\$0}")" && pwd 2>/dev/null) || SHIM_DIR=""
LOCAL_TARBALL="\${SHIM_DIR:+\$SHIM_DIR/\$TARBALL_NAME}"

# Refresh the install when:
#   * the binary doesn't exist yet, OR
#   * MIGRATE_REINSTALL=1 (operator wants to re-pull, e.g. after a CLI
#     bug fix in the same release tag), OR
#   * a sibling tarball is present and is NEWER than the cached binary
#     (running ./assemble-bootstrap.sh && ./dist/aws-bootstrap.sh on a
#     fresh repo build should pick up your local changes — without
#     this, the first install wins forever for that CLI_VERSION).
need_install=0
if [[ ! -x "\$BIN" ]]; then
  need_install=1
elif [[ "\${MIGRATE_REINSTALL:-0}" == "1" ]]; then
  need_install=1
elif [[ -n "\$LOCAL_TARBALL" && -f "\$LOCAL_TARBALL" && "\$LOCAL_TARBALL" -nt "\$BIN" ]]; then
  need_install=1
fi

if (( need_install )); then
  rm -rf "\$PREFIX"
  mkdir -p "\$PREFIX"
  tmp=\$(mktemp -d)
  if [[ -n "\$LOCAL_TARBALL" && -f "\$LOCAL_TARBALL" ]]; then
    cp "\$LOCAL_TARBALL" "\$tmp/cli.tgz"
  else
    curl -fsSL --max-time 120 -o "\$tmp/cli.tgz" "\$TARBALL_URL" \\
      || { echo "could not download \$TARBALL_URL" >&2; rm -rf "\$tmp"; exit 1; }
  fi
  tar -xzf "\$tmp/cli.tgz" -C "\$PREFIX" --strip-components=1
  rm -rf "\$tmp"
  chmod +x "\$BIN"
fi

exec "\$BIN" "\$@"
SHIM
chmod +x "$OUTPUT_DIR/aws-bootstrap.sh"

printf 'wrote %s\n' "$TARBALL"
printf 'wrote %s (curl-pipe shim)\n' "$OUTPUT_DIR/aws-bootstrap.sh"
