#!/usr/bin/env bash
# =============================================================================
# assemble-bootstrap.sh
#
# Produces the release artifacts for the EKS deploy path:
#
#   dist/aws-bootstrap.sh            backwards-compat shim (curl-friendly)
#   dist/migration-assistant-cli-<version>.tar.gz
#                                     full CLI tarball (bin + lib + skills)
#
# The shim is a single self-contained file that downloads + extracts the
# tarball into ~/.opensearch-migrate/cli/<version>/ on first run, then
# execs the unpacked migration-assistant binary. Equivalent UX to the old
# self-contained aws-bootstrap.sh but with the actual logic loaded from
# the tarball — so we only ship 50 lines of curl/tar/exec instead of
# inlining 1700 lines.
#
# Usage:
#   ./assemble-bootstrap.sh [--output-dir <path>] [--cli-version <ver>]
#
# Default: deployment/k8s/aws/dist/
# =============================================================================
set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLI_DIR="$SCRIPT_DIR/cli"
OUTPUT_DIR="${SCRIPT_DIR}/dist"
CLI_VERSION="${CLI_VERSION:-3.2.1}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir)  OUTPUT_DIR="$2";  shift 2 ;;
    --cli-version) CLI_VERSION="$2"; shift 2 ;;
    *) printf 'unknown arg: %s\n' "$1" >&2; exit 64 ;;
  esac
done

mkdir -p "$OUTPUT_DIR"

# 1. Tarball the CLI tree.
TARBALL="$OUTPUT_DIR/migration-assistant-cli-${CLI_VERSION}.tar.gz"
stage=$(mktemp -d)
mkdir -p "$stage/migration-assistant-cli-${CLI_VERSION}"
cp -R "$CLI_DIR/bin" "$CLI_DIR/lib" "$CLI_DIR/skills" \
      "$CLI_DIR/install.sh" "$CLI_DIR/README.md" \
      "$stage/migration-assistant-cli-${CLI_VERSION}/"
[[ -f "$CLI_DIR/LICENSE" ]] && cp "$CLI_DIR/LICENSE" \
                              "$stage/migration-assistant-cli-${CLI_VERSION}/"
tar -czf "$TARBALL" -C "$stage" "migration-assistant-cli-${CLI_VERSION}"
rm -rf "$stage"

# 2. Emit the curl-pipe shim. The shim downloads the tarball, unpacks it,
#    and execs the CLI. No repo checkout required by the operator.
cat > "$OUTPUT_DIR/aws-bootstrap.sh" <<SHIM
#!/usr/bin/env bash
# Self-contained migration-assistant bootstrap.
# Generated by deployment/k8s/aws/assemble-bootstrap.sh
# CLI version: ${CLI_VERSION}
set -o errexit
set -o nounset
set -o pipefail

CLI_VERSION='${CLI_VERSION}'
PREFIX="\${MIGRATE_PREFIX:-\$HOME/.opensearch-migrate/cli/\$CLI_VERSION}"
BIN="\$PREFIX/bin/migration-assistant"
TARBALL_NAME="migration-assistant-cli-\${CLI_VERSION}.tar.gz"
TARBALL_URL='https://github.com/opensearch-project/opensearch-migrations/releases/download/'\${CLI_VERSION}'/'\${TARBALL_NAME}

# Shim's directory — used to find a sibling tarball when one is shipped
# alongside (Jenkins/CI build, repo checkout, S3 dist bundle, etc.). Falls
# back to the GitHub release URL when no sibling exists.
SHIM_DIR=\$(cd "\$(dirname "\${BASH_SOURCE[0]:-\$0}")" && pwd)
LOCAL_TARBALL="\$SHIM_DIR/\$TARBALL_NAME"

if [[ ! -x "\$BIN" ]]; then
  mkdir -p "\$PREFIX"
  tmp=\$(mktemp -d)
  if [[ -f "\$LOCAL_TARBALL" ]]; then
    cp "\$LOCAL_TARBALL" "\$tmp/cli.tgz"
  else
    curl -fsSL --max-time 120 -o "\$tmp/cli.tgz" "\$TARBALL_URL" \\
      || { echo "could not download \$TARBALL_URL" >&2; rm -rf "\$tmp"; exit 1; }
  fi
  tar -xzf "\$tmp/cli.tgz" -C "\$PREFIX" --strip-components=1
  rm -rf "\$tmp"
  chmod +x "\$BIN"
fi

exec "\$BIN" "\$@"
SHIM
chmod +x "$OUTPUT_DIR/aws-bootstrap.sh"

printf 'wrote %s\n' "$TARBALL"
printf 'wrote %s (curl-pipe shim)\n' "$OUTPUT_DIR/aws-bootstrap.sh"
