apiVersion: v2
name: mock-customer-clusters
version: 0.1.0
dependencies:
  - name: elasticsearch
    version: "8.5.1"
    repository: https://helm.elastic.co
    alias: source
  - name: capture-proxy
    version: "0.1.0"
    repository: file://../../components/captureProxy
    alias: proxy
  - name: opensearch
    version: "2.23.1"
    repository: "https://opensearch-project.github.io/helm-charts/"
    alias: target
