proxy:
  parameters:
    destinationUri:
      value: "http://elasticsearch:9200"

source:
  imageTag: "7.10.2"
  image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  fullnameOverride: "elasticsearch"
  roles: [ master, data, ingest ]
  antiAffinity: "soft"
  esJavaOpts: "-Xmx128m -Xms128m"
  protocol: http
  # for simplest dev testing
  replicas: 2 # k8s replica count, not ES shard replicas
  createCert: false
  #  esConfig:
  #    elasticsearch.yml: |
  #      discovery.type: single-node

  # for load-testing deployments
  minimumMasterNodes: 1

target:
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: myStrongPassword123!
  singleNode: true
  persistence:
    enabled: false
