apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
spec:
  replicas: {{ .Values.replicas }}
  roles:
    - controller
    {{- if not (hasKey .Values "dedicatedController") }}
    - broker
    {{ end }}
  storage:
    type: jbod
    volumes:
      - id: 0
        type: {{ .Values.storageType }}
        size: {{ .Values.storageSize }}
        kraftMetadata: shared
        deleteClaim: {{ .Values.storageDeleteClaim }}
---
{{- if hasKey .Values "dedicatedController" }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
spec:
  replicas: {{ .Values.dedicatedController.replicas }}
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: {{ .Values.storageType }}
        size: {{ .Values.dedicatedController.storageSize }}
        kraftMetadata: shared
        deleteClaim: {{ .Values.storageDeleteClaim }}
---
{{- end }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.clusterName }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: 3.8-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: interbroker
        port: 9094
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      # Add these KRaft-specific configurations
      inter.broker.listener.name: interbroker
      listener.security.protocol.map: PLAINTEXT:PLAIN,SSL:SSL,INTERBROKER:SSL
  entityOperator:
    topicOperator: {}
    userOperator: {}