conditionalPackageInstalls:
  proxy: false
  source: false
  target: true

target:
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: myStrongPassword123!
  singleNode: true
  persistence:
    enabled: false