//! Deploy-artifact resolution: where the CFN template, the helm chart, and the
//! buildkit/gradle build come from, for the headless deploy.
//!
//! Two lanes:
//!   * **`--build` (source):** CFN template is synthesized by Gradle
//!     (`:deployment:migration-assistant-solution:cdkSynthMinified`) into
//!     `cdk.out-minified/`, the chart is the in-repo chart dir, and images are
//!     built + pushed by `:buildImages:buildImagesToRegistry`. The heavy lifting
//!     (CDK synth, buildkit) stays in Gradle — this module only computes the
//!     commands + paths, it does NOT reimplement them.
//!   * **Installed bundle:** the binary lives inside a self-contained install
//!     tree (`~/.opensearch-migration-assistant/`) that already ships the helm
//!     chart under `helm/` and the CDK solution under `cfn/`. No network calls.
//!
//! This module is pure (paths, URLs, command vectors); the side-effecting
//! shell-outs live on [`crate::app::App`], so they go through the runner seam
//! and stay testable.

use crate::cfn::TemplateVariant;
use std::path::{Path, PathBuf};

/// Locate the installed bundle root relative to the running binary.
///
/// Search order (up to 3 ancestors above the binary):
///   1. A directory containing `helm/migrationAssistantWithArgo/Chart.yaml`
///   2. `$MIGRATE_BUNDLE_DIR` env override
///
/// Returns `None` when not running from an installed layout (e.g. `cargo run`).
pub fn bundle_dir() -> Option<PathBuf> {
    if let Some(p) = std::env::var_os("MIGRATE_BUNDLE_DIR") {
        let p = PathBuf::from(p);
        if is_bundle_root(&p) {
            return Some(p);
        }
    }
    let exe = std::env::current_exe().ok()?;
    let exe = exe.canonicalize().unwrap_or(exe);
    exe.ancestors()
        .skip(1)
        .take(3)
        .find(|dir| is_bundle_root(dir))
        .map(Path::to_path_buf)
}

fn is_bundle_root(dir: &Path) -> bool {
    dir.join("helm/migrationAssistantWithArgo/Chart.yaml")
        .is_file()
}

/// The helm chart directory from the installed bundle.
pub fn bundled_chart_dir(bundle: &Path) -> PathBuf {
    bundle.join("helm/migrationAssistantWithArgo")
}

/// The CDK/CFN solution directory from the installed bundle.
pub fn bundled_cfn_dir(bundle: &Path) -> PathBuf {
    bundle.join("cfn")
}

/// The helm values files from the installed bundle chart (in apply order).
/// When `valuesImages.yaml` exists (generated by a custom pack), it's
/// applied after the EKS values to override image repositories/tags.
pub fn bundled_chart_values(bundle: &Path) -> Vec<String> {
    let chart = bundled_chart_dir(bundle);
    let mut values = vec![
        chart.join("values.yaml").to_string_lossy().to_string(),
        chart.join("valuesEks.yaml").to_string_lossy().to_string(),
    ];
    let custom_images = chart.join("valuesImages.yaml");
    if custom_images.is_file() {
        values.push(custom_images.to_string_lossy().to_string());
    }
    values
}

/// The local path the Gradle CDK synth writes the chosen template to.
/// Under `cdk.out-minified/<TemplateName>` in the solution package.
pub fn synthesized_template_path(base_dir: &str, variant: TemplateVariant) -> String {
    format!(
        "{base_dir}/deployment/migration-assistant-solution/cdk.out-minified/{}",
        variant.template_name()
    )
}

/// The in-repo helm chart directory used on the `--build` lane.
pub fn local_chart_dir(base_dir: &str) -> String {
    format!("{base_dir}/deployment/k8s/charts/aggregates/migrationAssistantWithArgo")
}

/// The helm values files applied (in order): the chart's base `values.yaml`
/// then the EKS overrides `valuesEks.yaml`.
pub fn local_chart_values(chart_dir: &str) -> Vec<String> {
    vec![
        format!("{chart_dir}/values.yaml"),
        format!("{chart_dir}/valuesEks.yaml"),
    ]
}

/// Gradle args (after the `gradlew` program) that synthesize the minified CFN
/// templates. `STACK_NAME_SUFFIX=""` is set by the caller as an env var so the
/// output filenames are the predictable [`TemplateVariant::template_name`].
pub fn cdk_synth_args(base_dir: &str) -> Vec<String> {
    vec![
        "-p".into(),
        base_dir.into(),
        ":deployment:migration-assistant-solution:cdkSynthMinified".into(),
        "-x".into(),
        "test".into(),
    ]
}

/// A buildkit builder name derived from the kube context, sanitized to
/// `[A-Za-z0-9_-]`. Non-matching chars become `-`.
pub fn builder_name(kube_context: &str) -> String {
    let sanitized: String = kube_context
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    format!("builder-{sanitized}")
}

/// The full image-build shell block (run via `bash -c`), mirroring the
/// The `--build` path: ensure a kubernetes-driver buildkit
/// builder exists (the EKS agents have no local docker build daemon), ECR-login
/// via docker, then `gradlew :buildImages:buildImagesToRegistry` with one retry.
/// Kept as a pure string so it's unit-testable; the side effect is the caller's
/// `runner.run("bash", ["-c", script])`.
#[allow(clippy::too_many_arguments)]
pub fn build_images_script(
    base_dir: &str,
    region: &str,
    ecr_host: &str,
    registry: &str,
    builder: &str,
    image_tag: &str,
    kube_context: &str,
    skip_test_images: bool,
) -> String {
    let skip_arg = if skip_test_images {
        "-PskipTestImages=true"
    } else {
        ""
    };
    // `set -euo pipefail` so any sub-step failure propagates a non-zero rc.
    // The builder is reused if healthy, else (re)created via the repo's
    // eksKubernetesBuildkit backend — exactly as the reference does.
    format!(
        r#"set -euo pipefail
export MULTI_ARCH_NATIVE=true
export KUBE_CONTEXT="{kube_context}"
export MIGRATIONS_REPO_ROOT_DIR="{base_dir}"
BUILDER_NAME="{builder}"
if docker buildx inspect "$BUILDER_NAME" --bootstrap >/dev/null 2>&1; then
  echo "Buildkit already configured and healthy, skipping setup"
else
  echo "Setting up buildkit (kubernetes driver) ..."
  docker buildx rm "$BUILDER_NAME" >/dev/null 2>&1 || true
  source "{base_dir}/buildImages/backends/eksKubernetesBuildkit.sh"
  setup_build_backend
fi
echo "Logging in to ECR registry: {ecr_host}"
aws ecr get-login-password --region "{region}" | docker login --username AWS --password-stdin "{ecr_host}"
echo "Building images to {registry}"
"{base_dir}/gradlew" -p "{base_dir}" :buildImages:buildImagesToRegistry \
  -PregistryEndpoint="{registry}" -Pbuilder="$BUILDER_NAME" -PimageVersion="{image_tag}" {skip_arg} -x test \
  || {{ echo "Image build failed, retrying in 10s..."; sleep 10; \
       "{base_dir}/gradlew" -p "{base_dir}" :buildImages:buildImagesToRegistry \
         -PregistryEndpoint="{registry}" -Pbuilder="$BUILDER_NAME" -PimageVersion="{image_tag}" {skip_arg} -x test; }}
echo "Cleaning up buildx builder ..."
docker buildx rm "$BUILDER_NAME" >/dev/null 2>&1 || true
"#
    )
}

/// Shell block (run via `bash -c`) that mirrors the third-party images + helm
/// charts into the private ECR and writes a private-ECR helm values override to
/// `values_out`:
/// it sources the chart's own `privateEcrManifest.sh` (the IMAGES/CHARTS lists),
/// `mirrorToEcr.sh` (`mirror_images_to_ecr`/`mirror_charts_to_ecr`), and
/// `generatePrivateEcrValues.sh` (`generate_private_ecr_values`) — the proven
/// scripts vendored in the chart — rather than reimplementing them in Rust.
///
/// Without this, the chart's `ma-dependency-installer` pre-install hook tries to
/// pull cert-manager/argo/strimzi/etc. charts+images from public registries
/// (which the in-cluster job can't reach / isn't configured for) and its pods
/// hang until `activeDeadlineSeconds` → `DeadlineExceeded`. The generated values
/// repoint every sub-chart at `oci://<ecr>/charts/...` + `<ecr>/mirrored/...`.
pub fn mirror_to_ecr_script(
    scripts_dir: &str,
    ecr_host: &str,
    region: &str,
    values_out: &str,
) -> String {
    format!(
        r#"set -euo pipefail
. "{scripts_dir}/privateEcrManifest.sh"
. "{scripts_dir}/mirrorToEcr.sh"
. "{scripts_dir}/generatePrivateEcrValues.sh"
echo "Mirroring third-party images to private ECR ({ecr_host}) ..."
mirror_images_to_ecr "{ecr_host}" "{region}" "$IMAGES"
echo "Mirroring helm charts to private ECR ..."
mirror_charts_to_ecr "{ecr_host}" "{region}" "$CHARTS"
echo "Generating private-ECR helm values override → {values_out}"
generate_private_ecr_values "{ecr_host}" > "{values_out}"
echo "wrote {values_out}"
"#
    )
}

/// Shell block (run via `bash -c`) that runs `aws cloudformation deploy` while a
/// background poller tails `describe-stack-events` so the operator sees live
/// resource-by-resource progress (and, on failure, the failing resource's
/// reason). `aws cloudformation deploy` ALONE prints "Waiting for stack
/// create/update to complete" and then goes SILENT for the whole ~15-20 min
/// VPC+EKS create — leaving the console looking hung. Includes a background
/// the deploy + event-tailer pair. Each element
/// of `params` is one parameter-override token (`Key=Value`), shell-quoted into
/// the deploy command.
pub fn cfn_deploy_script(
    region: &str,
    stack_name: &str,
    template_file: &str,
    params: &[String],
) -> String {
    // Shell-quote each parameter override (values may contain `=`,`,`,`/` etc.).
    let param_args = params
        .iter()
        .map(|p| format!("'{}'", p.replace('\'', "'\\''")))
        .collect::<Vec<_>>()
        .join(" ");
    format!(
        r#"set -uo pipefail
STACK="{stack_name}"
REGION="{region}"
SEEN="$(mktemp)"
# Background event tailer: print each new stack event (status, type, id, reason)
# so a long silent CFN create shows live progress.
stream_events() {{
  while true; do
    aws cloudformation describe-stack-events --stack-name "$STACK" --region "$REGION" \
      --query 'StackEvents[].[EventId,Timestamp,ResourceStatus,ResourceType,LogicalResourceId,ResourceStatusReason]' \
      --output text 2>/dev/null | tac | while IFS=$'\t' read -r eid ts status rtype logical reason; do
        grep -qxF "$eid" "$SEEN" 2>/dev/null && continue
        echo "$eid" >> "$SEEN"
        [ "$reason" = "None" ] && reason=""
        printf '  %-22s %-28s %-38s %s%s\n' "$ts" "$status" "$rtype" "$logical" "${{reason:+  ($reason)}}"
      done
    sleep 10
  done
}}
stream_events &
STREAM_PID=$!
aws cloudformation deploy \
  --region "$REGION" \
  --stack-name "$STACK" \
  --template-file "{template_file}" \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
  --no-fail-on-empty-changeset \
  --parameter-overrides {param_args}
rc=$?
kill $STREAM_PID 2>/dev/null; wait $STREAM_PID 2>/dev/null
rm -f "$SEEN"
# On failure, surface the failed resources explicitly (deploy's own error is terse).
if [ $rc -ne 0 ]; then
  echo "CFN deploy failed (rc=$rc) — failed resources:" >&2
  aws cloudformation describe-stack-events --stack-name "$STACK" --region "$REGION" \
    --query 'StackEvents[?contains(ResourceStatus,`FAILED`)].[LogicalResourceId,ResourceStatus,ResourceStatusReason]' \
    --output text 2>/dev/null | head -20 >&2
fi
exit $rc
"#
    )
}

/// Shell block (run via `bash -c`) that runs `helm upgrade --install … --wait`
/// while a background poller tails the release namespace, so the operator sees
/// live pod-status transitions and Warning events. `helm --wait` ALONE prints
/// `Release "ma" does not exist. Installing it now.` and then goes SILENT for
/// the whole ~15-20 min while the `ma-dependency-installer` pre-install hook and
/// the sub-chart pods converge — leaving the console looking hung. Worse, a pod
/// stuck in `ErrImagePull`/`ImagePullBackOff` (the failure that previously
/// produced a silent ~20-min `DeadlineExceeded`) gave no signal at all until the
/// deadline. The background watcher surfaces that within ~10s by streaming each
/// pod's name/ready/phase/waiting-reason and every Warning event (deduplicated
/// the same way `cfn_deploy_script` dedups stack events). On failure it dumps the
/// namespace pods plus recent Warnings so the cause lands in the log. Includes a
/// `stream_events` pattern in [`cfn_deploy_script`].
///
/// `helm_args` is the COMPLETE helm argument vector (already including any
/// `--kube-context <ctx>`); each token is shell-quoted into the command.
/// `kube_context`, when non-empty, is the `--context` the kubectl watcher binds
/// to (context names are metadata-safe — `[A-Za-z0-9._-]`, no spaces — so the
/// unquoted `$KCTX` word-splits into exactly two safe tokens or none).
pub fn helm_install_script(kube_context: &str, namespace: &str, helm_args: &[String]) -> String {
    let arg_str = helm_args
        .iter()
        .map(|a| format!("'{}'", a.replace('\'', "'\\''")))
        .collect::<Vec<_>>()
        .join(" ");
    let kctx = if kube_context.is_empty() {
        String::new()
    } else {
        format!("--context {kube_context}")
    };
    format!(
        r#"set -uo pipefail
NS="{namespace}"
KCTX="{kctx}"
SEEN="$(mktemp)"
# Background watcher: stream pod state transitions + Warning events so the long
# silent `helm --wait` (pre-install hook + sub-chart convergence) shows live
# progress — and an ErrImagePull/ImagePullBackOff surfaces in ~10s, not at the
# 20-min deadline. `tr -s ' '` squeezes custom-columns padding so a line is
# stable for dedup; `grep -qxF` against $SEEN prints each distinct state once.
watch_ns() {{
  while true; do
    kubectl $KCTX get pods -n "$NS" --no-headers \
      -o 'custom-columns=NAME:.metadata.name,READY:.status.containerStatuses[*].ready,PHASE:.status.phase,WAIT:.status.containerStatuses[*].state.waiting.reason' 2>/dev/null \
      | tr -s ' ' | while IFS= read -r line; do
        [ -z "$line" ] && continue
        grep -qxF "$line" "$SEEN" 2>/dev/null && continue
        echo "$line" >> "$SEEN"
        printf '  %s\n' "$line"
      done
    kubectl $KCTX get events -n "$NS" --field-selector type=Warning --no-headers \
      -o 'custom-columns=OBJECT:.involvedObject.name,REASON:.reason,MESSAGE:.message' 2>/dev/null \
      | tr -s ' ' | while IFS= read -r line; do
        [ -z "$line" ] && continue
        grep -qxF "evt $line" "$SEEN" 2>/dev/null && continue
        echo "evt $line" >> "$SEEN"
        case "$line" in
          *FailedScheduling*) printf '  \033[2m⧗ %s\033[0m\n' "$line" ;;
          *)                  printf '  ! %s\n' "$line" ;;
        esac
      done
    sleep 10
  done
}}
watch_ns &
WPID=$!
helm {arg_str}
rc=$?
kill $WPID 2>/dev/null; wait $WPID 2>/dev/null
rm -f "$SEEN"
# On failure, surface the namespace state explicitly (helm's own error is terse).
# `>&2 2>/dev/null` (NOT `2>/dev/null >&2`): point stdout at our stderr FIRST,
# then drop kubectl's own stderr — the reversed order would send the pod table
# to /dev/null (fd1 would inherit the just-redirected fd2).
if [ $rc -ne 0 ]; then
  echo "helm install/upgrade failed (rc=$rc) — namespace $NS pods:" >&2
  kubectl $KCTX get pods -n "$NS" >&2 2>/dev/null
  echo "recent Warning events:" >&2
  kubectl $KCTX get events -n "$NS" --field-selector type=Warning --sort-by=.lastTimestamp 2>/dev/null | tail -30 >&2
fi
exit $rc
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_path_uses_variant_name() {
        let p = synthesized_template_path("/repo", TemplateVariant::CreateVpc);
        assert!(
            p.ends_with("cdk.out-minified/Migration-Assistant-Infra-Create-VPC-eks.template.json")
        );
        let p = synthesized_template_path("/repo", TemplateVariant::ImportVpc);
        assert!(p.ends_with("Migration-Assistant-Infra-Import-VPC-eks.template.json"));
    }

    #[test]
    fn builder_name_sanitizes() {
        assert_eq!(
            builder_name("migration-eks-eksbyos-p200"),
            "builder-migration-eks-eksbyos-p200"
        );
        assert_eq!(
            builder_name("ctx:weird/chars.x"),
            "builder-ctx-weird-chars-x"
        );
    }

    #[test]
    fn build_images_script_has_setup_login_and_gradle() {
        let s = build_images_script(
            "/repo",
            "us-east-1",
            "123.dkr.ecr.us-east-1.amazonaws.com",
            "123.dkr.ecr.us-east-1.amazonaws.com/ecr",
            "builder-x",
            "tag1",
            "migration-eks-x",
            true,
        );
        // buildkit setup (reuse-or-create), ECR login, gradle build, skip-test.
        assert!(s.contains("docker buildx inspect \"$BUILDER_NAME\" --bootstrap"));
        assert!(s.contains("eksKubernetesBuildkit.sh"));
        assert!(s.contains("setup_build_backend"));
        assert!(s.contains("docker login --username AWS --password-stdin"));
        assert!(s.contains(":buildImages:buildImagesToRegistry"));
        assert!(s.contains("-PregistryEndpoint=\"123.dkr.ecr.us-east-1.amazonaws.com/ecr\""));
        assert!(s.contains("-Pbuilder=\"$BUILDER_NAME\""));
        assert!(s.contains("-PimageVersion=\"tag1\""));
        assert!(s.contains("-PskipTestImages=true"));
        assert!(s.contains("set -euo pipefail"));
        // skip-test omitted when false.
        let s2 = build_images_script("/r", "r", "h", "reg", "b", "t", "c", false);
        assert!(!s2.contains("-PskipTestImages=true"));
    }

    #[test]
    fn helm_install_script_wraps_helm_with_a_namespace_watcher() {
        let s = helm_install_script(
            "my-ctx",
            "ma",
            &[
                "--kube-context".into(),
                "my-ctx".into(),
                "upgrade".into(),
                "--install".into(),
                "ma".into(),
                "/charts/ma.tgz".into(),
                "--wait".into(),
            ],
        );
        // The full helm argv is embedded (shell-quoted) and invoked as `helm …`.
        assert!(s.contains("helm '--kube-context' 'my-ctx' 'upgrade' '--install' 'ma'"));
        // The bound context is carried in $KCTX (used by the watcher's kubectl).
        assert!(s.contains("KCTX=\"--context my-ctx\""));
        // Background watcher streams pods + Warning events via $KCTX.
        assert!(s.contains("watch_ns &"));
        assert!(s.contains("kubectl $KCTX get pods -n \"$NS\""));
        assert!(s.contains("--field-selector type=Warning"));
        // Watcher is torn down and rc is propagated.
        assert!(s.contains("kill $WPID"));
        assert!(s.contains("exit $rc"));
        // On failure it dumps namespace pods + recent warnings to stderr.
        assert!(s.contains("helm install/upgrade failed (rc=$rc)"));
        assert!(s.contains("get pods -n \"$NS\""));
    }

    #[test]
    fn helm_install_script_omits_context_when_empty() {
        // No kube context -> the watcher's kubectl runs without `--context`
        // (the `$KCTX` var is empty and word-splits to nothing).
        let s = helm_install_script("", "ma", &["upgrade".into(), "--install".into()]);
        assert!(s.contains("KCTX=\"\""));
        assert!(!s.contains("--context "));
    }

    #[test]
    fn helm_install_script_shell_quotes_args_safely() {
        // An arg containing a single quote is escaped, not left to break out:
        // `x=a'b` → `'x=a'\''b'` (close-quote, escaped-quote, reopen-quote).
        let s = helm_install_script("c", "ma", &["--set".into(), "x=a'b".into()]);
        assert!(s.contains(r#"'x=a'\''b'"#));
    }

    #[test]
    fn bundled_paths_resolve_from_bundle_root() {
        let bundle = Path::new("/opt/migration-assistant");
        assert_eq!(
            bundled_chart_dir(bundle),
            PathBuf::from("/opt/migration-assistant/helm/migrationAssistantWithArgo")
        );
        assert_eq!(
            bundled_cfn_dir(bundle),
            PathBuf::from("/opt/migration-assistant/cfn")
        );
        let values = bundled_chart_values(bundle);
        assert_eq!(values.len(), 2);
        assert!(values[0].ends_with("values.yaml"));
        assert!(values[1].ends_with("valuesEks.yaml"));
    }

    #[test]
    fn is_bundle_root_checks_chart_yaml() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(!is_bundle_root(tmp.path()));
        let chart_dir = tmp.path().join("helm/migrationAssistantWithArgo");
        std::fs::create_dir_all(&chart_dir).unwrap();
        std::fs::write(chart_dir.join("Chart.yaml"), "name: test\n").unwrap();
        assert!(is_bundle_root(tmp.path()));
    }

    #[test]
    fn cdk_synth_args_shape() {
        let a = cdk_synth_args("/repo");
        assert_eq!(a[0], "-p");
        assert_eq!(a[1], "/repo");
        assert!(a.iter().any(|x| x.contains("cdkSynthMinified")));
    }
}
