# Only create PVC, if PVC with same name does not already exist
{{- $pvc := lookup "v1" "PersistentVolumeClaim" .Release.Namespace .Values.volume.pvcClaimName -}}
{{- if not $pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.pvcClaimName }}
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  {{- if .Values.volume.storageClass }}
  storageClassName: {{ .Values.volume.storageClass }}
  {{- end }}
{{- end }}
