# Name of the Data Prepper pipeline
historical-data-migration:
  # Source cluster configuration
  source:
    opensearch:
      # CDK code will replace this value, so DO NOT CHANGE this
      # unless the file is being used outside of the CDK
      hosts:
      - <SOURCE_CLUSTER_HOST>
      # Example configuration on how to disable authentication (default: false)
      indices:
        # Indices to exclude - exclude system indices by default
        exclude:
        - index_name_regex: \.*
      # disable_authentication: true
      username: "admin"
      password: "admin"
      connection:
        insecure: true
  # Target cluster configuration
  sink:
  - opensearch:
      # Note - CDK code will replace this value with the target cluster endpoint
      hosts:
      - <TARGET_CLUSTER_ENDPOINT_PLACEHOLDER>
      # Derive index name from record metadata
      index: ${getMetadata("opensearch-index")}
      # Use the same document ID as the source cluster document
      document_id: ${getMetadata("opensearch-document_id")}
      # Example configuration for basic auth
      # disable_authentication: true
      username: "admin"
      password: "myStrongPassword123!"
      connection:
        insecure: true
  # Additional pipeline options/optimizations
  buffer:
    bounded_blocking: # Values recommended by an expert
      buffer_size: 1000000
      batch_size: 12500
  # For maximum throughput, match workers to number of vCPUs (default: 1)
  workers: 2
  # delay is how often the worker threads should process data (default: 3000 ms)
  delay: 0
