"""Load-test integration case (Shape A): a k6 load test layered on a live CDC migration.

Instead of `generate-data`, this drives real load through the capture proxy with a short k6 run (an
Argo Workflow that creates a k6-operator TestRun and waits for it), then asserts the
capture-and-replay pipeline moved that traffic to the target — i.e. the pipeline works *under load*,
not just for a handful of hand-written docs.

Requires the standalone k6LoadTest chart to be installed (operator + per-scenario WorkflowTemplates
+ RBAC) and the migrations/k6_scripts image, the data image mounted at /scripts that carries the
scenarios and presets. The test runner installs the chart on its own when a load-test ID (0080-0089)
is selected; the case is explicit-selection only so it never runs in a normal migration suite.
"""

import logging
import uuid

from .cdc_base import (
    MATestBase, MigrationType, MATestUserArguments,
    CDC_SOURCE_TARGET_COMBINATIONS, PROXY_ENDPOINT,
    wait_for_proxy_ready, wait_for_replayer_consuming, assert_replay_drained,
)

logger = logging.getLogger(__name__)

# The k6 ingest scenario writes the nyc_taxis schema to this index by default.
K6_INDEX = "nyc_taxis"


class Test0080CdcK6LoadTest(MATestBase):
    """Full E2E CDC where the captured traffic is generated by a short k6 load test.

    k6 runs in the replay-only (post-snapshot) phase so its docs reach the target via replay only
    (no snapshot/backfill duplication), making the source/target counts directly comparable.
    """
    requires_explicit_selection = True

    K6_DURATION = "20s"
    K6_RATE = "10"
    K6_PARALLELISM = 2

    def __init__(self, user_args: MATestUserArguments):
        super().__init__(
            user_args=user_args,
            description="Full E2E CDC driven by a k6 load test through the capture proxy.",
            migrations_required=[MigrationType.METADATA, MigrationType.BACKFILL,
                                 MigrationType.CAPTURE_AND_REPLAY],
            allow_source_target_combinations=CDC_SOURCE_TARGET_COMBINATIONS,
        )
        self._uid = f"{self.unique_id}-{uuid.uuid4().hex[:4]}"
        self._source_count = None

    def prepare_workflow_parameters(self, keep_workflows: bool = False):
        super().prepare_workflow_parameters(keep_workflows=keep_workflows)
        self.workflow_template = (
            "cdc-full-e2e-imported-clusters" if self.imported_clusters
            else "cdc-e2e-migration-with-clusters"
        )
        self.parameters["pre-snapshot-proxy-submit"] = "true"
        self.parameters["capture-proxy-service-type"] = self.capture_proxy_service_type

    def prepare_clusters(self):
        pass

    def _run_k6(self, namespace, target_url):
        """Fire a short k6 ingest run at the proxy and wait for the workflow to finish."""
        # Imported inside the method so the case only depends on the k6 module when actually run.
        from console_link.loadtest.utils import load_k8s_config
        from console_link.loadtest.runs import (
            build_k6_parameters, submit_k6_run, wait_for_run, SUCCESS_PHASE,
        )
        load_k8s_config()
        params = build_k6_parameters(
            scenario="ingest", parallelism=self.K6_PARALLELISM, target_url=target_url,
            duration=self.K6_DURATION, rate=self.K6_RATE,
            overrides_text="SEED_DOC_COUNT=0",   # skip the seed-count wait
            extra_args="--no-thresholds",        # loaded test cluster may breach latency thresholds
        )
        name = submit_k6_run(namespace, params)
        logger.info("Submitted k6 run %s against %s", name, target_url)
        phase = wait_for_run(namespace, name, timeout=300, interval=5)
        if phase != SUCCESS_PHASE:
            raise AssertionError(f"k6 run {name} ended in phase '{phase}' "
                                 f"(expected '{SUCCESS_PHASE}')")
        logger.info("k6 run %s finished", name)

    def workflow_perform_migrations(self, timeout_seconds: int = 3600):
        if not self.workflow_name:
            raise ValueError("Workflow name is not available")
        ns = self.argo_service.namespace

        if not self.imported_clusters:
            logger.info("Resuming workflow past pause-for-test-data to start proxy-only capture...")
            self.argo_service.resume_workflow(workflow_name=self.workflow_name)

        logger.info("Waiting for capture-proxy to be ready...")
        wait_for_proxy_ready(ns, timeout_seconds)

        # Advance to the full migration (snapshot + backfill + replay). No pre-snapshot load, so
        # everything k6 writes next reaches the target via replay only.
        logger.info("Waiting for workflow to pause before full migration submit...")
        self.argo_service.wait_for_suspend(workflow_name=self.workflow_name, timeout_seconds=600)
        logger.info("Resuming workflow to submit full migration...")
        self.argo_service.resume_workflow(workflow_name=self.workflow_name)

        logger.info("Waiting for replayer to join Kafka consumer group...")
        wait_for_replayer_consuming(namespace=ns, workflow_name=self.workflow_name)

        # Drive load through the proxy with k6; the replayer will replay it to the target.
        self._run_k6(ns, PROXY_ENDPOINT)

        # Capture assertion: k6 wrote through the proxy to the source.
        details = self.source_operations.get_all_index_details(cluster=self.source_cluster)
        self._source_count = int(details.get(K6_INDEX, {}).get("count", 0))
        logger.info("Source %s doc count after k6: %d", K6_INDEX, self._source_count)
        if self._source_count <= 0:
            raise AssertionError(f"k6 wrote no docs to source index '{K6_INDEX}' via the proxy")

        if not self.imported_clusters:
            logger.info("Waiting for workflow to reach pause-for-migration-verification suspend...")
            self.argo_service.wait_for_suspend(workflow_name=self.workflow_name, timeout_seconds=600)

    def post_migration_actions(self):
        pass

    def verify_clusters(self):
        # Replay assertion: the k6-generated load was captured and replayed to the target. The
        # ingest scenario bulk-writes with auto-generated _ids, so replay-only reproduces the same
        # count on the target as on the source.
        logger.info("Verifying %s replayed to target (expect %d)...", K6_INDEX, self._source_count)
        try:
            self.target_operations.check_doc_counts_match(
                cluster=self.target_cluster,
                expected_index_details={K6_INDEX: {"count": self._source_count}},
                max_attempts=120, delay=10.0,
            )
        finally:
            assert_replay_drained(label="replay-end")
