apiVersion: v2
name: test-solr-os-clusters
version: 0.1.0
dependencies:
  - name: shim-proxy
    alias: shimProxy
    version: "0.1.0"
    repository: "file://../../components/shimProxy"
  - name: opensearch
    condition: conditionalPackageInstalls.opensearch
    version: "2.32.0"
    repository: "https://opensearch-project.github.io/helm-charts/"
  - name: solr
    condition: conditionalPackageInstalls.solr
    version: "0.1.0"
    repository: "file://../../components/solr"
