# Define all enabled/disabled migration services
migration-console-enabled: true
capture-proxy-enabled: true
replayer-enabled: false
kafka-op-enabled: true
reindex-from-snapshot-enabled: false
elasticsearch-searchguard-enabled: true
opensearch-helm-enabled: true

# Define specific dependency configuration
opensearch-helm:
  image:
    tag: "2.17.0"
  replicas: 1
  singleNode: true
  config:
    discovery.type: single-node
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: myStrongPassword123!
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  persistence:
    enabled: true
    storageClass: "ebs-sc"
    size: "30Gi"

kafka-op:
  clusterName: kafka-cluster
  kafkaVersion: 3.8.0
  kafkaMetadataVersion: 3.8-IV0
  nodePool:
    replicas: 1
    volume:
      size: 10Gi
      class: "ebs-sc"
      deleteClaim: true

elasticsearch:
  replicaCount: 1
  image:
    repository: 977363099154.dkr.ecr.us-east-1.amazonaws.com/migrations-local-repo
    pullPolicy: IfNotPresent
    tag: "elasticsearch_searchguard-latest"
  service:
    type: ClusterIP
    port: 19200 # Port exposed to external
    targetPort: 9200 # Container port
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: path.repo
      value: "/storage/snapshot"
  volumes:
    - name: snapshot-vol
      persistentVolumeClaim:
        claimName: snapshot-vol-pvc
  volumeMounts:
    - name: snapshot-vol
      mountPath: /storage
  snapshot-vol:
    volume:
      volumeName: snapshot-vol
      mountPath: /storage # Path inside the container where the volume should be mounted
      # Persistent volume claim settings
      pvcClaimName: snapshot-vol-pvc
      storageClass: "efs-sc"
      accessMode: ReadWriteOnce
      size: 5Gi

migration-console:
  replicaCount: 1
  image:
    repository: 977363099154.dkr.ecr.us-east-1.amazonaws.com/migrations-local-repo
    pullPolicy: IfNotPresent
    tag: "migration_console-latest"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: SHARED_LOGS_DIR_PATH
      value: /shared-logs-output/traffic-replayer-default
    - name: STAGE
      configMapKeyRef:
        name: test-env
        key: STAGE
  volumes:
    - name: services-yaml
      configMap:
        name: services-yaml-config-map
    - name: shared-logs
      persistentVolumeClaim:
        claimName: shared-logs-pvc
    - name: snapshot-vol
      persistentVolumeClaim:
        claimName: snapshot-vol-pvc
  volumeMounts:
    - name: services-yaml
      mountPath: /etc/migration-config
    - name: shared-logs
      mountPath: /shared-logs-output
    - name: snapshot-vol
      mountPath: /storage
  snapshot-vol:
    volume:
      volumeName: snapshot-vol
      mountPath: /storage # Path inside the container where the volume should be mounted
      # Persistent volume claim settings
      pvcClaimName: snapshot-vol-pvc
      storageClass: "efs-sc"
      accessMode: ReadWriteOnce
      size: 5Gi
  shared-logs-vol:
    volume:
      volumeName: shared-logs
      mountPath: /shared-logs-output # Path inside the container where the volume should be mounted
      # Persistent volume claim settings
      pvcClaimName: shared-logs-pvc
      storageClass: "efs-sc"
      accessMode: ReadWriteOnce
      size: 10Gi

capture-proxy:
  replicaCount: 1
  image:
    repository: 977363099154.dkr.ecr.us-east-1.amazonaws.com/migrations-local-repo
    pullPolicy: IfNotPresent
    tag: "capture_proxy-latest"
  service:
    type: ClusterIP
    port: 9201 # Port exposed to external
    targetPort: 9200 # Container port
  container:
    command: >
      /runJavaWithClasspath.sh org.opensearch.migrations.trafficcapture.proxyserver.CaptureProxy
      --kafkaConnection kafka-cluster-kafka-bootstrap:9092
      --destinationUri  https://elasticsearch:19200
      --insecureDestination
      --listenPort 9200
      --sslConfigFile /usr/share/elasticsearch/config/proxy_tls.yml
  #--otelCollectorEndpoint http://localhost:4317
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
