version: '3.7'
services:

  otel-collector:
    image: migrations/otel_collector:latest
    networks:
      - migrations
    volumes:
      - ./composeExtensions/configs/otel-config-prometheus-jaeger-opensearch.yaml:/etc/otel-config-prometheus-jaeger.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317"   # otlp receiver
