version: '3.7'
services:

  otel-collector:
    image: migrations/otel_collector:latest
    command: ["--config=/etc/otel-config-everything.yaml", "${OTELCOL_ARGS}"]
    networks:
      - migrations
    volumes:
      - ./composeExtensions/configs/otel-config-everything.yaml:/etc/otel-config-everything.yaml
      - ~/.aws:/home/aoc/.aws
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317"   # otlp receiver
    depends_on:
      - jaeger
    environment:
      - AWS_REGION=us-east-2
      - AWS_DEFAULT_REGION=us-east-2
      - AWS_PROFILE=default