version: '3.7'
services:

  otel-collector:
    image: migrations/otel_collector:latest
    command: ["--config=/etc/otel-config-prometheus-jaeger.yaml", "${OTELCOL_ARGS}"]
    networks:
      - migrations
    volumes:
      - ./composeExtensions/configs/otel-config-prometheus-jaeger.yaml:/etc/otel-config-prometheus-jaeger.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317"   # otlp receiver
    depends_on:
      - jaeger