version: '3.7'
services:

  otel-collector:
    image: migrations/otel_collector:latest
    command: ["--config=/etc/otel-config-aws-debug.yaml", "${OTELCOL_ARGS}"]
    networks:
      - migrations
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317"   # otlp receiver
    volumes:
      - ~/.aws:/home/aoc/.aws
    environment:
      - AWS_REGION=us-east-2
      - AWS_DEFAULT_REGION=us-east-2
      - AWS_PROFILE=default
