apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
spec:
  selector:
    app: {{ include "generic.fullname" . }}
    env: v1
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
