apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: full-migration-
spec:
  workflowTemplateRef:
    name: full-migration
  entrypoint: main
  arguments:
    parameters:
      - name: source-migration-configs
        value: |
          [
              {
                  "source": {
                      "endpoint": "https://elasticsearch-master-headless:9200",
                      "allow_insecure": true,
                      "version": "ES_7.10",
                      "basic_auth": {
                          "username": "admin",
                          "password": "admin"
                      }
                  },
                  "snapshot-and-migration-configs": [
                      {
                          "indices": [
                              "index_3",
                              "index_4"
                          ],
                          "migrations": [
                              {
                                  "metadata": {
                                      "from_snapshot": null,
                                      "otel_endpoint": "http://otel-collector:4317",
                                      "transformer_config_base64": ""
                                  },
                                  "documentBackfillConfigs": [
                                      {
                                          "transformer_config_base64": "",
                                          "indices": [
                                              "index_3",
                                              "index_4"
                                          ]
                                      }
                                  ]
                              }
                          ]
                      }
                  ],
                  "replayer-config": {
                      "batchSize": 1000,
                      "concurrency": 4
                  }
              }
          ]
      - name: targets
        value: |
          [
              {
                  "endpoint": "https://opensearch-cluster-master-headless:9200",
                  "allow_insecure": true,
                  "basic_auth": {
                      "username": "admin",
                      "password": "admin"
                  }
              }
          ]
