apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: full-migration-with-clusters-
spec:
  workflowTemplateRef:
    name: full-migration-with-clusters
  entrypoint: main
  arguments:
    parameters:
      - name: source-cluster-template
        value: "elasticsearch-5-6-single-node"
      - name: target-cluster-template
        value: "opensearch-2-19-single-node"
      - name: cluster-namespace
        value: "ma"