{{- if .Values.useDedicatedKarpenterPool }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: dedicated-search-pool
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          # let's not do spot since we're pretty sloppy with these charts and don't configure durable persistence
          values: ["on-demand"]
        {{- if .Values.nodePoolInstanceTypes }}
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            {{- range .Values.nodePoolInstanceTypes }}
            - {{ . }}
            {{- end }}
        {{- else }}
        - key: eks.amazonaws.com/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values: ["5"]
        {{- end }}
      taints:
        - key: "dedicated-search"
          value: "true"
          effect: NoSchedule
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 10m
{{- end }}
