{{- if .Values.conditionalPackageInstalls.solrSource }}
apiVersion: v1
kind: Secret
metadata:
  name: solr-s3-credentials
type: Opaque
stringData:
  access-key-id: "test"
  secret-access-key: "test"
{{- end }}
