apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: migration-console-template
spec:
  entrypoint: run-migration-command
  templates:
    - name: get-console-config
      inputs:
        parameters:
          - name: kafka-info
            value: ""
            description: "Snapshot configuration information (JSON)"
          - name: source-cluster
            value: ""
            description: "Source cluster configuration (JSON)"
          - name: target-cluster
            value: ""
            description: "Target cluster configuration (JSON)"
          - name: snapshot-info
            value: ""
            description: "Snapshot configuration information (JSON)"
          - name: metadata-info
            value: ""
            description: "Metadata migration configuration information (JSON)"
      outputs:
        parameters:
          - name: config-contents
            valueFrom:
              expression: >-
                (inputs.parameters['kafka-info']     != "" ? "kafka: " +              inputs.parameters['kafka-info'] + "\n" : "") + 
                (inputs.parameters['source-cluster'] != "" ? "source_cluster: " +     inputs.parameters['source-cluster'] + "\n" : "") + 
                (inputs.parameters['snapshot-info']  != "" ? "snapshot: " +           inputs.parameters['snapshot-info'] + "\n" : "") +
                (inputs.parameters['metadata-info']  != "" ? "metadata_migration: " + inputs.parameters['metadata-info'] + "\n" : "") +
                (inputs.parameters['target-cluster'] != "" ? "target_cluster: " +     inputs.parameters['target-cluster'] + "\n" : "")
      steps: [[]]

    - name: run-console-with-config
      inputs:
        parameters:
          - name: command
          - name: config-contents
          - name: migration-console-image
          - name: migration-console-pull-policy
          - name: kafka-client-secret-bundle
            value: "dummy-secret"
          - name: use-localstack-aws-creds
            value: "false"
      container:
        image: "{{inputs.parameters.migration-console-image}}"
        imagePullPolicy: "{{inputs.parameters.migration-console-pull-policy}}"
        volumeMounts:
        - name: kafka-config
          mountPath: "/opt/kafka-config"
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e
            
            if [ "{{inputs.parameters.use-localstack-aws-creds}}" = "true" ]; then
              export AWS_ACCESS_KEY_ID=test
              export AWS_SECRET_ACCESS_KEY=test
              export AWS_SESSION_TOKEN=test
              export AWS_REGION=us-east-2
            fi
    
            # Save pod name to output path
            echo $HOSTNAME > /tmp/podname
            
            base64 -d > /config/migration_services.yaml << EOF
            {{= toBase64(inputs.parameters['config-contents']) }}
            EOF
            
            . /etc/profile.d/venv.sh
            source /.venv/bin/activate
            
            echo file dump
            echo ---
            cat /config/migration_services.yaml
            echo ---

            if [ "{{inputs.parameters.kafka-client-secret-bundle}}" = "" ]; then
              echo "WARNING: No kafka-client-secret-bundle provided. Kafka functionality will be limited or unavailable."
            fi
            
            {{inputs.parameters.command}}
      volumes:
      - name: kafka-config
        secret:
          secretName: "{{inputs.parameters.kafka-client-secret-bundle}}"
          optional: true

    - name: deploy-console-with-config
      inputs:
        parameters:
          - name: command
          - name: configContents
          - name: name
          - name: migration-console-image
          - name: migration-console-pull-policy
          - name: kafka-client-secret-bundle
            value: "dummy-secret"
      outputs:
        parameters:
          - name: deployment-name
            valueFrom:
              jsonPath: '{.metadata.name}'
      resource:
        action: create
        setOwnerReference: true
        successCondition: status.availableReplicas > 0
        manifest: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: {{inputs.parameters.name}}
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: user-environment
            template:
              metadata:
                labels:
                  app: user-environment
              spec:
                containers:
                  - name: main
                    image: "{{inputs.parameters.migration-console-image}}"
                    imagePullPolicy: "{{inputs.parameters.migration-console-pull-policy}}"
                    volumeMounts:
                    - name: kafka-config
                      mountPath: "/opt/kafka-config"
                    command:
                      - "/bin/sh"
                      - "-c"
                      - |
                        set -e
          
                        base64 -d > /config/migration_services.yaml << EOF
                        {{=toBase64(inputs.parameters.configContents)}}
                        EOF
                      
                        . /etc/profile.d/venv.sh
                        source /.venv/bin/activate
                      
                        echo file dump
                        echo ---
                        cat /config/migration_services.yaml
                        echo ---

                        if [ "{{inputs.parameters.kafka-client-secret-bundle}}" = "" ]; then
                          echo "WARNING: No kafka-client-secret-bundle provided. Kafka functionality will be limited or unavailable."
                        fi
          
                        {{inputs.parameters.command}}
                volumes:
                - name: kafka-config
                  secret:
                    secretName: "{{inputs.parameters.kafka-client-secret-bundle}}"
                    optional: true

    - name: run-console
      inputs:
        parameters:
          - name: command
          - name: migration-console-image
          - name: migration-console-pull-policy
          - name: source-cluster
            value: ""
          - name: target-cluster
            value: ""
          - name: snapshot-info
            value: ""
          - name: kafka-info
            value: ""
          - name: kafka-client-secret-bundle
            value: "dummy-secret"
      steps:
        - - name: get-console-config
            template: get-console-config
            arguments:
              parameters:
                - name: source-cluster
                  value: "{{inputs.parameters.source-cluster}}"
                - name: target-cluster
                  value: "{{inputs.parameters.target-cluster}}"
                - name: snapshot-info
                  value: "{{inputs.parameters.snapshot-info}}"
                - name: kafka-info
                  value: "{{inputs.parameters.kafka-info}}"
        - - name: run-console-with-config
            template: run-console-with-config
            arguments:
              parameters:
                - name: config-contents
                  value: "{{steps.get-console-config.outputs.parameters.config-contents}}"
                - name: command
                  value: "{{inputs.parameters.command}}"
                - name: migration-console-image
                  value: "{{inputs.parameters.migration-console-image}}"
                - name: migration-console-pull-policy
                  value: "{{inputs.parameters.migration-console-pull-policy}}"
                - name: kafka-client-secret-bundle
                  value: "{{inputs.parameters.kafka-client-secret-bundle}}"

    - name: deploy-console
      inputs:
        parameters:
          - name: command
          - name: migration-console-image
          - name: migration-console-pull-policy
          - name: kafka-info
            value: ""
          - name: name
            value: ""
          - name: snapshot-info
            value: ""
          - name: source-cluster
            value: ""
          - name: target-cluster
            value: ""
          - name: kafka-client-secret-bundle
            value: "dummy-secret"
      outputs:
        parameters:
          - name: deployment-name
            valueFrom:
              expression: "steps['deploy-console-with-config'].outputs.parameters['deployment-name']"
      steps:
        - - name: get-console-config
            template: get-console-config
            arguments:
              parameters:
                - name: kafka-info
                  value: "{{inputs.parameters.kafka-info}}"
                - name: snapshot-info
                  value: "{{inputs.parameters.snapshot-info}}"
                - name: source-cluster
                  value: "{{inputs.parameters.source-cluster}}"
                - name: target-cluster
                  value: "{{inputs.parameters.target-cluster}}"
        - - name: deploy-console-with-config
            template: deploy-console-with-config
            arguments:
              parameters:
                - name: name
                  value: "{{=let n=inputs.parameters.name; n == '' ? 'diagnostic-console-' + workflow.uid : n}}"
                - name: configContents
                  value: "{{steps.get-console-config.outputs.parameters.config-contents}}"
                - name: command
                  value: "{{inputs.parameters.command}}"
                - name: migration-console-image
                  value: "{{inputs.parameters.migration-console-image}}"
                - name: migration-console-pull-policy
                  value: "{{inputs.parameters.migration-console-pull-policy}}"
                - name: kafka-client-secret-bundle
                  value: "{{inputs.parameters.kafka-client-secret-bundle}}"
