sharedLogsVolumeEnabled: false
sharedLogsPvc: ""
snapshotVolumeEnabled: false
snapshotVolumePvc: ""
parameters:
  initialLeaseDuration:
    source: parameterConfig
    value: PT10M
    allowRuntimeOverride: true
  documentsPerBulkRequest:
    source: parameterConfig
    value: 1000
    allowRuntimeOverride: true
  luceneDir:
    source: parameterConfig
    value: /tmp
    allowRuntimeOverride: true
  snapshotLocalDir:
    source: parameterConfig
    value: /snapshot
    allowRuntimeOverride: true
