apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-dig-
spec:
  serviceAccountName: argo-workflow-executor
  entrypoint: test-dig
  arguments:
    parameters:
      - name: migrationConfig
        value: '{"documentBackfillConfigs": {"indices": ["index1", "index2", "index3"]}}'
  templates:
    - name: test-dig
      inputs:
        parameters:
          - name: migrationConfig
            default: "{}"
          - name: dr
            value: "{{=sprig.dig('documentBackfillConfigs', 'indices2', \"zoo\", fromJSON(inputs.parameters.migrationConfig)) }}"
      container:
        image: alpine:latest
        command: [sh, -c]
        args:
          - |
            echo "=== Testing dig function ==="
            echo "Input JSON: {{inputs.parameters.migrationConfig}}"
            echo "Dig result: 
            echo "{{=toBase64(toJSON(inputs.parameters.dr))}}" | base64 -d
            echo "{{=sprig.join(';', (inputs.parameters.dr))}}"
            echo "=== Test complete ==="
