apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-transforms
  labels:
    app.kubernetes.io/name: shim-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.transformFiles }}
data:
  {{- range $filename, $content := .Values.transformFiles }}
  {{ $filename }}: |
{{ $content | indent 4 }}
  {{- end }}
{{- end }}
