apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-solr
  labels:
    app.kubernetes.io/name: solr
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: solr
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solr
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
          ports:
            - name: zk-client
              containerPort: 2181
              protocol: TCP
          readinessProbe:
            exec:
              command: ["sh", "-c", "echo ruok | nc localhost 2181 | grep imok"]
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "mntr,conf,ruok"
        - name: solr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ZK_HOST
              value: "localhost:2181"
          args: ["-c"]
          ports:
            - name: http
              containerPort: 8983
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /solr/admin/info/system
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /solr/admin/info/system
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
