{{- if index .Values.conditionalPackageInstalls "aws-mountpoint-s3-csi-driver" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-s3-artifacts-pv
spec:
  capacity:
    storage: 1200Gi  # Ignored by S3 CSI driver, required by Kubernetes
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: s3-artifacts-pvc
  mountOptions:
    - region {{ .Values.aws.region }}
    - read-only
    {{- if .Values.defaultBucketConfiguration.useLocalStack }}
    - endpoint-url http://{{ .Values.defaultBucketConfiguration.endpoint }}.{{ .Release.Namespace }}.svc.cluster.local:4566
    - force-path-style
    - no-sign-request
    {{- end }}
  csi:
    driver: s3.csi.aws.com
    volumeHandle: {{ .Release.Namespace }}-s3-artifacts
    volumeAttributes:
      bucketName: {{ printf "migrations-default-%s-%s-%s" (toString .Values.aws.account) .Values.stageName .Values.aws.region }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-artifacts-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi  # Ignored by S3 CSI driver, required by Kubernetes
  volumeName: {{ .Release.Namespace }}-s3-artifacts-pv
{{- end }}
