{{- if .Values.defaultBucketConfiguration.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-s3-bucket-{{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: s3-bucket-create
    spec:
      serviceAccountName: {{ .Values.defaultBucketConfiguration.serviceAccountName }}
      restartPolicy: OnFailure
      containers:
        - name: aws-cli
          image: {{ .Values.defaultBucketConfiguration.bucketOperationImage }}
          imagePullPolicy: {{ .Values.defaultBucketConfiguration.bucketOperationImagePullPolicy }}
          env:
            {{- if .Values.defaultBucketConfiguration.useLocalStack }}
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
            {{- end }}
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: migrations-default-s3-config
                  key: AWS_REGION
            - name: S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: migrations-default-s3-config
                  key: ENDPOINT
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: migrations-default-s3-config
                  key: BUCKET_NAME
          command:
            - /bin/sh
            - -c
            - |
              set -e
              {{ include "migration.s3Functions" . | nindent 12 }}

              # Setting up variables
              MAX_RETRIES=10
              RETRY_INTERVAL=5
              S3_ENDPOINT_FLAG=$(get_s3_endpoint_flag)

              if [ -n "${S3_ENDPOINT_URL}" ]; then
                echo "Using endpoint: $S3_ENDPOINT_URL"
              fi
              echo "Target bucket for creation: $BUCKET_NAME"

              # Wait for S3 to be available
              retry_count=0
              while ! check_s3_available; do
                retry_count=$((retry_count + 1))
                if [ $retry_count -ge $MAX_RETRIES ]; then
                  echo "S3 endpoint not available after $MAX_RETRIES attempts. Exiting."
                  exit 1
                fi
                echo "S3 endpoint not available yet. Retrying in $RETRY_INTERVAL seconds... (Attempt $retry_count/$MAX_RETRIES)"
                sleep $RETRY_INTERVAL
              done

              echo "S3 endpoint is available. Proceeding with bucket operations."

              # Check if bucket exists
              if bucket_exists "$BUCKET_NAME"; then
                echo "Bucket $BUCKET_NAME already exists."
              else
                echo "Creating bucket $BUCKET_NAME..."
                aws $S3_ENDPOINT_FLAG s3 mb s3://"$BUCKET_NAME"

                # Verify bucket creation
                if bucket_exists "$BUCKET_NAME" 5; then
                  echo "Successfully created bucket $BUCKET_NAME."
                else
                  echo "Failed to create bucket $BUCKET_NAME."
                  exit 1
                fi
              fi

              # List all buckets to confirm
              echo "Listing all buckets:"
              aws $S3_ENDPOINT_FLAG s3 ls
{{- end }}
