
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrations-default-s3-tuple-config
  labels:
    workflows.argoproj.io/configmap-type: Parameter
data:
  TUPLE_S3_BUCKET: {{ printf "\"migrations-default-%s-%s-%s\"" (toString .Values.aws.account) .Values.stageName .Values.aws.region }}
  TUPLE_S3_REGION: {{ .Values.aws.region }}
  TUPLE_S3_PREFIX: "tuples/"
  USE_LOCAL_STACK: {{ .Values.defaultBucketConfiguration.useLocalStack | quote }}
