apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: capture-replay-
spec:
  workflowTemplateRef:
    name: capture-replay
  entrypoint: run-all
  arguments:
    parameters:
      - name: source-config
        value: |
          {
              "endpoint": "https://elasticsearch-master-headless:9200",
              "allow_insecure": true,
              "basic_auth": {
                  "username": "admin",
                  "password": "admin"
              }
          }
      - name: session-name
        value: test
      - name: topic-partitions
        value: 2
      - name: proxy-listen-port
        value: 9200
      - name: proxy-destination
        value: |
          {
              "endpoint": "https://elasticsearch-master-headless:9200",
              "allow_insecure": true
          }
      - name: replayer-target-config
        value: |
              {
                  "endpoint": "https://opensearch-cluster-master-headless:9200",
                  "allow_insecure": true,
                  "basic_auth": {
                      "username": "admin",
                      "password": "admin"
                  }
              }
