apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: capture-replay-
spec:
  workflowTemplateRef:
    name: kafka-setup
  entrypoint: topic-deploy
  arguments:
    parameters:
      - name: kafka-name
        value: captured-traffic-cluster
      - name: topic-name
        value: captured-traffic-topic
