apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: migrate-from-snapshot-
spec:
  workflowTemplateRef:
    name: full-migration
  entrypoint: pipeline-migrate-from-snapshot
  arguments:
    parameters:
      - name: source-config
        value: |
          {"allow_insecure":true,"basic_auth":{"password":"admin","username":"admin"},"endpoint":"https://elasticsearch-master-headless:9200"}
      - name: snapshot-config
        value: | 
          {"snapshot_name": "ahr0chm6ly9lbgfzdgljc2vhcmnolw1hc3rlci1ozwfkbgvzczo5mjaw", "s3": {"endpoint": "http://ma-localstack:4566", "aws_region": "us-west-2", "repo_uri": "s3://snapshot"}}
      - name: migration-config
        value: |
          {"documentBackfillConfigs":[{"indices":["index_3","index_4"]}],"metadata":{"mappings":{"properties":{}},"settings":{}}}
      - name: target-config
        value: |
          {"allow_insecure":true,"basic_auth":{"username":"admin","password":"admin"},"endpoint":"https://opensearch-cluster-master-headless:9200"}
      - name: latch-coordination-prefix
        value: "workflow-bee289ac-c428-482b-906e-35a1a07de144"
