apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: full-migration-
spec:
  workflowTemplateRef:
    name: bulk-load
  entrypoint: check-complete
  arguments:
    parameters:
      - name: session-name
        value: "workflow-bee289ac-c428-482b-906e-35a1a07de144"
