/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveCapabilityV1 */
        ApproveCapabilityV1: {
            /** Approvaltargetid */
            approvalTargetId: string;
            /**
             * Kind
             * @constant
             */
            kind: "approve";
            /** Label */
            label: string;
        };
        /** ComparisonV1 */
        ComparisonV1: {
            deployed: components["schemas"]["ValueStateV1"];
            /** Label */
            label: string;
            /** Path */
            path: string;
            pending: components["schemas"]["ValueStateV1"];
            /** Pendingchanged */
            pendingChanged: boolean;
            submitted: components["schemas"]["ValueStateV1"];
            /** Submittedchanged */
            submittedChanged: boolean;
        };
        /** DetailV1 */
        DetailV1: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Value */
            value: unknown;
        };
        /** DiagnosticV1 */
        DiagnosticV1: {
            /** Message */
            message: string;
            /** Path */
            path?: string[];
            /** Severity */
            severity: string;
            /**
             * Source
             * @default null
             */
            source: string | null;
        };
        /** EditCapabilityV1 */
        EditCapabilityV1: {
            /** Edittargetid */
            editTargetId: string;
            /**
             * Kind
             * @constant
             */
            kind: "edit";
            /**
             * Label
             * @default null
             */
            label: string | null;
        };
        /** HealthV1 */
        HealthV1: {
            /**
             * Apiversion
             * @default v1
             * @constant
             */
            apiVersion: "v1";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LogsCapabilityV1 */
        LogsCapabilityV1: {
            /**
             * Kind
             * @constant
             */
            kind: "logs";
            /**
             * Label
             * @default null
             */
            label: string | null;
            /** Logtargetid */
            logTargetId: string;
        };
        /** ManageNodeV1 */
        ManageNodeV1: {
            /** Capabilities */
            capabilities?: (components["schemas"]["EditCapabilityV1"] | components["schemas"]["ApproveCapabilityV1"] | components["schemas"]["ResetCapabilityV1"] | components["schemas"]["LogsCapabilityV1"] | components["schemas"]["OutputCapabilityV1"])[];
            /** Childids */
            childIds?: string[];
            /** Comparisons */
            comparisons?: components["schemas"]["ComparisonV1"][];
            /**
             * Description
             * @default null
             */
            description: string | null;
            /** Details */
            details?: components["schemas"]["DetailV1"][];
            /** Diagnostics */
            diagnostics?: components["schemas"]["DiagnosticV1"][];
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /**
             * Parentid
             * @default null
             */
            parentId: string | null;
            /**
             * Phase
             * @default null
             */
            phase: string | null;
            /**
             * Resourcename
             * @default null
             */
            resourceName: string | null;
            /**
             * Resourceplural
             * @default null
             */
            resourcePlural: string | null;
            /** Revision */
            revision: string;
            /** Status */
            status: string;
            /**
             * Valuesummary
             * @default null
             */
            valueSummary: string | null;
        };
        /** ManageSnapshotV1 */
        ManageSnapshotV1: {
            /**
             * Formatversion
             * @constant
             */
            formatVersion: 1;
            /** Namespace */
            namespace: string;
            /** Nodes */
            nodes: {
                [key: string]: components["schemas"]["ManageNodeV1"];
            };
            /**
             * Observedat
             * Format: date-time
             */
            observedAt: string;
            /** Problems */
            problems?: components["schemas"]["ProblemV1"][];
            /** @default null */
            refreshError: components["schemas"]["ProblemV1"] | null;
            /** Revision */
            revision: string;
            /** Rootids */
            rootIds: string[];
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            workflow: components["schemas"]["WorkflowV1"] | null;
            /** Workflowname */
            workflowName: string;
        };
        /** OutputCapabilityV1 */
        OutputCapabilityV1: {
            /**
             * Kind
             * @constant
             */
            kind: "output";
            /**
             * Label
             * @default null
             */
            label: string | null;
            /** Outputtargetid */
            outputTargetId: string;
        };
        /** ProblemV1 */
        ProblemV1: {
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            /** Source */
            source: string;
        };
        /** ResetCapabilityV1 */
        ResetCapabilityV1: {
            /**
             * Kind
             * @constant
             */
            kind: "reset";
            /** Label */
            label: string;
            /** Resettargetid */
            resetTargetId: string;
        };
        /** ValueStateV1 */
        ValueStateV1: {
            /** Present */
            present: boolean;
            /**
             * Provenance
             * @default null
             */
            provenance: {
                [key: string]: unknown;
            } | null;
            /**
             * Value
             * @default null
             */
            value: unknown;
        };
        /** WorkflowV1 */
        WorkflowV1: {
            /**
             * Finishedat
             * @default null
             */
            finishedAt: string | null;
            /** Name */
            name: string;
            /** Phase */
            phase: string;
            /**
             * Startedat
             * @default null
             */
            startedAt: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthV1"];
                };
            };
        };
    };
}
