/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_v1_approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Approval */
        get: operations["review_approval_api_v1_approvals_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Config */
        get: operations["open_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Config */
        post: operations["close_config_api_v1_config_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard Config */
        post: operations["discard_config_api_v1_config_discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Config Operation */
        post: operations["apply_config_operation_api_v1_config_operations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preflight Config */
        post: operations["preflight_config_api_v1_config_preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/removal-impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Config Removal Impact */
        post: operations["config_removal_impact_api_v1_config_removal_impact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Config */
        post: operations["review_config_api_v1_config_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Config */
        post: operations["save_config_api_v1_config_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Config */
        post: operations["submit_config_api_v1_config_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** External Resources */
        get: operations["external_resources_api_v1_external_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external-resources/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** External Resource Details */
        get: operations["external_resource_details_api_v1_external_resources_details_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external-resources/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save External Resource */
        post: operations["save_external_resource_api_v1_external_resources_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/external-resources/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select External Resource */
        post: operations["select_external_resource_api_v1_external_resources_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/log-streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Log Stream */
        post: operations["start_log_stream_api_v1_log_streams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/log-streams/{stream_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Stop Log Stream */
        delete: operations["stop_log_stream_api_v1_log_streams__stream_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/log-streams/{stream_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Log Events */
        get: operations["stream_log_events_api_v1_log_streams__stream_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/log-streams/{stream_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Log Page */
        get: operations["read_log_page_api_v1_log_streams__stream_id__pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manage Events */
        get: operations["manage_events_api_v1_manage_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manage State */
        get: operations["manage_state_api_v1_manage_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/log-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Log Targets */
        get: operations["list_log_targets_api_v1_nodes__node_id__log_targets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Operations */
        get: operations["list_operations_api_v1_operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operation Events */
        get: operations["operation_events_api_v1_operations_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Outputs */
        get: operations["list_outputs_api_v1_outputs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outputs/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Output */
        get: operations["read_output_api_v1_outputs_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outputs/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Output */
        get: operations["download_output_api_v1_outputs_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Reset */
        post: operations["execute_reset_api_v1_resets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resets/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Reset */
        post: operations["plan_reset_api_v1_resets_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddEditOperationV1 */
        AddEditOperationV1: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add";
            /** Path */
            path: string[];
            /** Value */
            value: unknown;
        };
        /** AdmissionPreflightIssueV1 */
        AdmissionPreflightIssueV1: {
            /** Blocking */
            blocking: boolean;
            /**
             * Classification
             * @enum {string}
             */
            classification: "recreate-required" | "invalid" | "approval-required" | "warning";
            /** Kind */
            kind: string;
            /** Message */
            message: string;
            /** Name */
            name: string;
            /** Plural */
            plural?: string | null;
            /** Resettargetid */
            resetTargetId?: string | null;
            /** Resourceid */
            resourceId?: string | null;
            /** Source */
            source: string;
        };
        /** AdmissionPreflightV1 */
        AdmissionPreflightV1: {
            /** Allowed */
            allowed: boolean;
            /** Checkedresources */
            checkedResources: number;
            /** Issues */
            issues: components["schemas"]["AdmissionPreflightIssueV1"][];
        };
        /** ApplyEditOperationRequestV1 */
        ApplyEditOperationRequestV1: {
            /** Expecteddraftrevision */
            expectedDraftRevision: string;
            /** Operation */
            operation: components["schemas"]["SetEditOperationV1"] | components["schemas"]["UnsetEditOperationV1"] | components["schemas"]["RemoveConfigEditOperationV1"] | components["schemas"]["RenameConfigEditOperationV1"] | components["schemas"]["AddEditOperationV1"];
        };
        /** ApprovalReviewV1 */
        ApprovalReviewV1: {
            /** Effect */
            effect: string;
            /** Gatename */
            gateName: string;
            /** Gaterevision */
            gateRevision: string;
            /** Nodeid */
            nodeId: string;
            /** Reason */
            reason?: string | null;
            /** Resourceid */
            resourceId?: string | null;
            /** Resourcekind */
            resourceKind?: string | null;
            /** Resourcename */
            resourceName?: string | null;
            /** Snapshotrevision */
            snapshotRevision?: string | null;
            /** Stage */
            stage: string;
            /** Targetid */
            targetId: string;
            /** Workflowname */
            workflowName: string;
        };
        /** ApproveCapabilityV1 */
        ApproveCapabilityV1: {
            /** Approvaltargetid */
            approvalTargetId: string;
            /**
             * Disabledreason
             * @default null
             */
            disabledReason: string | null;
            /**
             * Kind
             * @constant
             */
            kind: "approve";
            /** Label */
            label: string;
        };
        /** ApproveRequestV1 */
        ApproveRequestV1: {
            /** Expectedgaterevision */
            expectedGateRevision: string;
            /** Targetid */
            targetId: string;
        };
        /** ComparisonV1 */
        ComparisonV1: {
            deployed: components["schemas"]["ValueStateV1"];
            /** Label */
            label: string;
            /** Path */
            path: string;
            pending: components["schemas"]["ValueStateV1"];
            /** Pendingchanged */
            pendingChanged: boolean;
            submitted: components["schemas"]["ValueStateV1"];
            /** Submittedchanged */
            submittedChanged: boolean;
        };
        /** ConfigDraftV1 */
        ConfigDraftV1: {
            /** Baserevision */
            baseRevision: string;
            /** Dirty */
            dirty: boolean;
            /** Draftrevision */
            draftRevision: string;
            editState: components["schemas"]["EditStateV1"];
        };
        /** ConfigRemovalImpactEntryV1 */
        ConfigRemovalImpactEntryV1: {
            /** Fieldpath */
            fieldPath: string[];
            /** Path */
            path: string[];
            /** Reason */
            reason: string;
        };
        /** ConfigRemovalImpactRequestV1 */
        ConfigRemovalImpactRequestV1: {
            /** Expecteddraftrevision */
            expectedDraftRevision: string;
            /** Path */
            path: string[];
        };
        /** ConfigRemovalImpactV1 */
        ConfigRemovalImpactV1: {
            /** Affected */
            affected: components["schemas"]["ConfigRemovalImpactEntryV1"][];
            /** Targetlabel */
            targetLabel: string;
            /** Targetpath */
            targetPath: string[];
        };
        /** ConfigReviewChangeV1 */
        ConfigReviewChangeV1: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "field" | "resource";
            /** Label */
            label: string;
            /** Path */
            path: string;
            /** Resourceid */
            resourceId?: string | null;
            /** Resourcelabel */
            resourceLabel?: string | null;
        };
        /** ConfigReviewV1 */
        ConfigReviewV1: {
            /** Baserevision */
            baseRevision: string;
            /** Changes */
            changes: components["schemas"]["ConfigReviewChangeV1"][];
            /** Dirty */
            dirty: boolean;
            /** Draftrevision */
            draftRevision: string;
            /** Valid */
            valid: boolean;
            /** Validationmessages */
            validationMessages: string[];
        };
        /** DetailV1 */
        DetailV1: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Value */
            value: unknown;
        };
        /** DiagnosticV1 */
        DiagnosticV1: {
            /**
             * Code
             * @default null
             */
            code: string | null;
            /** Message */
            message: string;
            /** Path */
            path?: string[];
            /**
             * Remedy
             * @default null
             */
            remedy: string | null;
            /** Severity */
            severity: string;
            /**
             * Source
             * @default null
             */
            source: string | null;
            /**
             * Technicaldetail
             * @default null
             */
            technicalDetail: string | null;
            /**
             * Title
             * @default null
             */
            title: string | null;
        };
        /** DraftRevisionRequestV1 */
        DraftRevisionRequestV1: {
            /** Expecteddraftrevision */
            expectedDraftRevision: string;
        };
        /** EditCapabilityV1 */
        EditCapabilityV1: {
            /**
             * Disabledreason
             * @default null
             */
            disabledReason: string | null;
            /** Edittargetid */
            editTargetId: string;
            /**
             * Kind
             * @constant
             */
            kind: "edit";
            /**
             * Label
             * @default null
             */
            label: string | null;
        };
        /** EditCommandV1 */
        EditCommandV1: {
            /**
             * Autoeditadded
             * @default true
             */
            autoEditAdded: boolean;
            /** Blockedmessage */
            blockedMessage?: string | null;
            /**
             * Editadded
             * @default false
             */
            editAdded: boolean;
            /**
             * Requiresname
             * @default true
             */
            requiresName: boolean;
        };
        /** EditDiagnosticV1 */
        EditDiagnosticV1: {
            /** Message */
            message: string;
            /** Path */
            path?: string[];
            /**
             * Severity
             * @enum {string}
             */
            severity: "required" | "error" | "warning" | "gated" | "blocked";
        };
        /** EditNodeV1 */
        EditNodeV1: {
            /** Children */
            children?: components["schemas"]["EditNodeV1"][];
            /** Collapsed */
            collapsed?: boolean | null;
            command?: components["schemas"]["EditCommandV1"] | null;
            /** Description */
            description?: string | null;
            /** Diagnostics */
            diagnostics?: components["schemas"]["EditDiagnosticV1"][];
            /** Effectivedefault */
            effectiveDefault?: {
                [key: string]: unknown;
            } | null;
            /** Essential */
            essential?: boolean | null;
            /** Expert */
            expert?: boolean | null;
            /** Externalref */
            externalRef?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** Inputhint */
            inputHint?: {
                [key: string]: unknown;
            } | null;
            /** Label */
            label: string;
            /** Path */
            path: string[];
            /** Presence */
            presence?: ("required" | "optional") | null;
            /** Removable */
            removable?: boolean | null;
            /** Required */
            required?: boolean | null;
            /** Status */
            status?: ("ok" | "required" | "error" | "warning" | "changed" | "gated" | "blocked") | null;
            statusCounts?: components["schemas"]["EditStatusCountsV1"] | null;
            /** Validation */
            validation?: {
                [key: string]: string;
            } | null;
            /** Value */
            value?: unknown;
            /** Valueauthored */
            valueAuthored?: boolean | null;
            /** Valuedefaulted */
            valueDefaulted?: boolean | null;
            /**
             * Valuekind
             * @enum {string}
             */
            valueKind: "object" | "record" | "array" | "union" | "boolean" | "scalar" | "command";
            /** Valuetype */
            valueType?: ("string" | "number" | "boolean") | null;
            /** Variants */
            variants?: components["schemas"]["EditVariantV1"][];
        };
        /** EditProvenanceV1 */
        EditProvenanceV1: {
            /** Lossy */
            lossy: boolean;
            /**
             * Source
             * @constant
             */
            source: "pending-yaml";
            /** Warnings */
            warnings?: string[];
        };
        /** EditStateV1 */
        EditStateV1: {
            /**
             * Formatversion
             * @constant
             */
            formatVersion: 1;
            /** Nodes */
            nodes: components["schemas"]["EditNodeV1"][];
            provenance: components["schemas"]["EditProvenanceV1"];
            validation: components["schemas"]["EditValidationV1"];
        };
        /** EditStatusCountsV1 */
        EditStatusCountsV1: {
            /**
             * Blocked
             * @default 0
             */
            blocked: number;
            /**
             * Changed
             * @default 0
             */
            changed: number;
            /**
             * Errors
             * @default 0
             */
            errors: number;
            /**
             * Gated
             * @default 0
             */
            gated: number;
            /**
             * Required
             * @default 0
             */
            required: number;
            /**
             * Warnings
             * @default 0
             */
            warnings: number;
        };
        /** EditValidationV1 */
        EditValidationV1: {
            /** Diagnostics */
            diagnostics?: components["schemas"]["EditDiagnosticV1"][];
            /** Errors */
            errors?: string[];
            /** Valid */
            valid: boolean;
        };
        /** EditVariantV1 */
        EditVariantV1: {
            /** Childschema */
            childSchema?: components["schemas"]["EditNodeV1"][];
            /** Description */
            description?: string | null;
            /** Label */
            label: string;
            /** Value */
            value: unknown;
        };
        /** ExecuteResetRequestV1 */
        ExecuteResetRequestV1: {
            /** Approvals */
            approvals?: components["schemas"]["ResetApprovalRequestV1"][];
            /** Expecteddraftrevision */
            expectedDraftRevision?: string | null;
            /** Plantoken */
            planToken: string;
            /**
             * Resubmit
             * @default false
             */
            resubmit: boolean;
        };
        /** ExternalResourceDetailsV1 */
        ExternalResourceDetailsV1: {
            /** Displayname */
            displayName: string;
            /** Draftrevision */
            draftRevision: string;
            /** Fieldvalues */
            fieldValues?: {
                [key: string]: string;
            };
            /** Hiddenfields */
            hiddenFields?: string[];
            /** Keys */
            keys?: string[];
            /** Kind */
            kind: string;
            /** Message */
            message?: string | null;
            /**
             * Missing
             * @default false
             */
            missing: boolean;
            /** Name */
            name: string;
            /** Nodeid */
            nodeId: string;
            /** Resourcetype */
            resourceType?: string | null;
        };
        /** ExternalResourceInventoryV1 */
        ExternalResourceInventoryV1: {
            /** Displayname */
            displayName: string;
            /** Draftrevision */
            draftRevision: string;
            /** Nodeid */
            nodeId: string;
            /** Rows */
            rows: components["schemas"]["ExternalResourceRowV1"][];
        };
        /** ExternalResourceMutationV1 */
        ExternalResourceMutationV1: {
            draft: components["schemas"]["ConfigDraftV1"];
            /** Kind */
            kind: string;
            /** Message */
            message: string;
            /** Name */
            name: string;
        };
        /** ExternalResourceRowV1 */
        ExternalResourceRowV1: {
            /** Apiversion */
            apiVersion?: string | null;
            /**
             * Current
             * @default false
             */
            current: boolean;
            /**
             * Group
             * @default
             */
            group: string;
            /** Keys */
            keys?: string[];
            /** Kind */
            kind: string;
            /**
             * Message
             * @default
             */
            message: string;
            /** Name */
            name: string;
            /** Namespaced */
            namespaced?: boolean | null;
            /**
             * Status
             * @enum {string}
             */
            status: "matching" | "warn" | "error";
            /** Type */
            type?: string | null;
            /**
             * Version
             * @default
             */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthV1 */
        HealthV1: {
            /**
             * Apiversion
             * @default v1
             * @constant
             */
            apiVersion: "v1";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LogEventV1 */
        LogEventV1: {
            /** Container */
            container: string;
            /**
             * Kind
             * @default log
             * @enum {string}
             */
            kind: "log" | "error";
            /** Message */
            message: string;
            /** Podname */
            podName: string;
            /** Poduid */
            podUid: string;
            /** Previous */
            previous: boolean;
            /**
             * Receivedat
             * Format: date-time
             */
            receivedAt: string;
            /** Restartcount */
            restartCount: number;
            /** Sequence */
            sequence: number;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** LogPageV1 */
        LogPageV1: {
            /** Aftercursor */
            afterCursor?: string | null;
            /** Atavailablestart */
            atAvailableStart: boolean;
            /** Atbufferend */
            atBufferEnd: boolean;
            /** Beforecursor */
            beforeCursor?: string | null;
            /** Events */
            events: components["schemas"]["LogEventV1"][];
            /** Historytruncated */
            historyTruncated: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "starting" | "following" | "ended" | "stopped" | "error";
        };
        /** LogStreamStatusV1 */
        LogStreamStatusV1: {
            /** Id */
            id: string;
            /** Message */
            message?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "starting" | "following" | "ended" | "stopped" | "error";
        };
        /** LogStreamV1 */
        LogStreamV1: {
            /** Id */
            id: string;
            page: components["schemas"]["LogPageV1"];
            /**
             * State
             * @enum {string}
             */
            state: "starting" | "following" | "ended" | "stopped" | "error";
            target: components["schemas"]["LogTargetV1"];
        };
        /** LogTargetInventoryV1 */
        LogTargetInventoryV1: {
            /** Capabilitytargetid */
            capabilityTargetId: string;
            /** Message */
            message?: string | null;
            /** Nodeid */
            nodeId: string;
            /** Targets */
            targets: components["schemas"]["LogTargetV1"][];
        };
        /** LogTargetV1 */
        LogTargetV1: {
            /** Container */
            container?: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "aggregate" | "container";
            /** Label */
            label: string;
            /** Podname */
            podName?: string | null;
            /** Poduid */
            podUid?: string | null;
            /** Previous */
            previous: boolean;
            /** Restartcount */
            restartCount?: number | null;
            /** Supportsfollow */
            supportsFollow: boolean;
        };
        /** LogsCapabilityV1 */
        LogsCapabilityV1: {
            /**
             * Disabledreason
             * @default null
             */
            disabledReason: string | null;
            /**
             * Kind
             * @constant
             */
            kind: "logs";
            /**
             * Label
             * @default null
             */
            label: string | null;
            /** Logtargetid */
            logTargetId: string;
        };
        /** ManageNodeV1 */
        ManageNodeV1: {
            /** Capabilities */
            capabilities?: (components["schemas"]["EditCapabilityV1"] | components["schemas"]["ApproveCapabilityV1"] | components["schemas"]["ResetCapabilityV1"] | components["schemas"]["LogsCapabilityV1"] | components["schemas"]["OutputCapabilityV1"])[];
            /** Childids */
            childIds?: string[];
            /** Comparisons */
            comparisons?: components["schemas"]["ComparisonV1"][];
            /** Configpresence */
            configPresence?: {
                [key: string]: boolean;
            };
            /**
             * Description
             * @default null
             */
            description: string | null;
            /** Details */
            details?: components["schemas"]["DetailV1"][];
            /** Diagnostics */
            diagnostics?: components["schemas"]["DiagnosticV1"][];
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /**
             * Parentid
             * @default null
             */
            parentId: string | null;
            /**
             * Phase
             * @default null
             */
            phase: string | null;
            /** Relationships */
            relationships?: components["schemas"]["RelationshipV1"][];
            /**
             * Resourcename
             * @default null
             */
            resourceName: string | null;
            /**
             * Resourceplural
             * @default null
             */
            resourcePlural: string | null;
            /** Revision */
            revision: string;
            /** Status */
            status: string;
            /**
             * Valuesummary
             * @default null
             */
            valueSummary: string | null;
        };
        /** ManageSnapshotV1 */
        ManageSnapshotV1: {
            /**
             * Formatversion
             * @constant
             */
            formatVersion: 1;
            /** Namespace */
            namespace: string;
            /** Nodes */
            nodes: {
                [key: string]: components["schemas"]["ManageNodeV1"];
            };
            /**
             * Observedat
             * Format: date-time
             */
            observedAt: string;
            /** Problems */
            problems?: components["schemas"]["ProblemV1"][];
            /** @default null */
            refreshError: components["schemas"]["ProblemV1"] | null;
            /** Revision */
            revision: string;
            /** Rootids */
            rootIds: string[];
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            workflow: components["schemas"]["WorkflowV1"] | null;
            /** Workflowname */
            workflowName: string;
        };
        /** OperationListV1 */
        OperationListV1: {
            /** Operations */
            operations: components["schemas"]["OperationV1"][];
        };
        /** OperationV1 */
        OperationV1: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Detail */
            detail?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Message */
            message: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "waiting" | "succeeded" | "failed";
            /** Targetids */
            targetIds: string[];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** OutputCapabilityV1 */
        OutputCapabilityV1: {
            /**
             * Disabledreason
             * @default null
             */
            disabledReason: string | null;
            /**
             * Kind
             * @constant
             */
            kind: "output";
            /**
             * Label
             * @default null
             */
            label: string | null;
            /** Outputtargetid */
            outputTargetId: string;
        };
        /** OutputContentV1 */
        OutputContentV1: {
            /** Content */
            content?: string | null;
            descriptor: components["schemas"]["OutputDescriptorV1"];
            /** Inline */
            inline: boolean;
            /** Message */
            message?: string | null;
            /** Size */
            size: number;
        };
        /** OutputDescriptorV1 */
        OutputDescriptorV1: {
            /** Attempt */
            attempt?: string | null;
            /** Contenttype */
            contentType: string;
            /** Id */
            id: string;
            /** Outputname */
            outputName: string;
            /** Resourceid */
            resourceId: string;
            /** Resourcename */
            resourceName: string;
            /** Resourceplural */
            resourcePlural: string;
            /** Source */
            source: string;
            /** Stage */
            stage: string;
            /** Stageorder */
            stageOrder: number;
            /** Targetid */
            targetId: string;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** OutputInventoryV1 */
        OutputInventoryV1: {
            /** Outputs */
            outputs: components["schemas"]["OutputDescriptorV1"][];
            /** Resourceid */
            resourceId: string;
            /** Targetid */
            targetId: string;
        };
        /** ProblemV1 */
        ProblemV1: {
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            /** Source */
            source: string;
        };
        /** RelationshipV1 */
        RelationshipV1: {
            /**
             * Direction
             * @enum {string}
             */
            direction: "requires" | "required-by";
            /**
             * Kind
             * @constant
             */
            kind: "runtime-dependency";
            /**
             * Targetid
             * @default null
             */
            targetId: string | null;
            /** Targetname */
            targetName: string;
            /**
             * Targetphase
             * @default null
             */
            targetPhase: string | null;
            /**
             * Targetplural
             * @default null
             */
            targetPlural: string | null;
            /** Targetstatus */
            targetStatus: string;
        };
        /** RemoveConfigEditOperationV1 */
        RemoveConfigEditOperationV1: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "removeConfig";
            /** Path */
            path: string[];
        };
        /** RenameConfigEditOperationV1 */
        RenameConfigEditOperationV1: {
            /** Newname */
            newName: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "renameConfig";
            /** Path */
            path: string[];
        };
        /** ResetApprovalRequestV1 */
        ResetApprovalRequestV1: {
            /** Expectedgaterevision */
            expectedGateRevision: string;
            /** Targetid */
            targetId: string;
        };
        /** ResetCapabilityV1 */
        ResetCapabilityV1: {
            /**
             * Disabledreason
             * @default null
             */
            disabledReason: string | null;
            /**
             * Kind
             * @constant
             */
            kind: "reset";
            /** Label */
            label: string;
            /** Resettargetid */
            resetTargetId: string;
        };
        /** ResetPlanRequestV1 */
        ResetPlanRequestV1: {
            /** Targetid */
            targetId?: string | null;
            /** Targetids */
            targetIds?: string[];
        };
        /** ResetPlanV1 */
        ResetPlanV1: {
            /** Messages */
            messages: string[];
            /** Requesttargetid */
            requestTargetId: string;
            /** Targets */
            targets: components["schemas"]["ResetTargetV1"][];
            /** Token */
            token: string;
            /** Warnings */
            warnings: string[];
        };
        /** ResetTargetV1 */
        ResetTargetV1: {
            /** Dependson */
            dependsOn: string[];
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Phase */
            phase: string;
            /** Plural */
            plural: string;
            /** Type */
            type: string;
        };
        /** SaveExternalResourceRequestV1 */
        SaveExternalResourceRequestV1: {
            /** Confirmations */
            confirmations?: {
                [key: string]: string;
            };
            /** Existingname */
            existingName?: string | null;
            /** Expecteddraftrevision */
            expectedDraftRevision: string;
            /** Nodeid */
            nodeId: string;
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /** SelectExternalResourceRequestV1 */
        SelectExternalResourceRequestV1: {
            /**
             * Acceptwarning
             * @default false
             */
            acceptWarning: boolean;
            /** Expecteddraftrevision */
            expectedDraftRevision: string;
            /**
             * Group
             * @default
             */
            group: string;
            /** Key */
            key?: string | null;
            /** Kind */
            kind: string;
            /**
             * Manual
             * @default false
             */
            manual: boolean;
            /** Name */
            name: string;
            /** Nodeid */
            nodeId: string;
        };
        /** SetEditOperationV1 */
        SetEditOperationV1: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set";
            /** Path */
            path: string[];
            /** Value */
            value: unknown;
        };
        /** StartLogStreamRequestV1 */
        StartLogStreamRequestV1: {
            /**
             * Follow
             * @default true
             */
            follow: boolean;
            /**
             * Pagesize
             * @default 200
             */
            pageSize: number;
            /**
             * Taillines
             * @default 1000
             */
            tailLines: number;
            /** Targetid */
            targetId: string;
        };
        /** UnsetEditOperationV1 */
        UnsetEditOperationV1: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "unset";
            /** Path */
            path: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValueStateV1 */
        ValueStateV1: {
            /** Present */
            present: boolean;
            /**
             * Provenance
             * @default null
             */
            provenance: {
                [key: string]: unknown;
            } | null;
            /**
             * Value
             * @default null
             */
            value: unknown;
        };
        /** WorkflowV1 */
        WorkflowV1: {
            /**
             * Finishedat
             * @default null
             */
            finishedAt: string | null;
            /** Name */
            name: string;
            /** Phase */
            phase: string;
            /**
             * Startedat
             * @default null
             */
            startedAt: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    approve_api_v1_approvals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_approval_api_v1_approvals_review_get: {
        parameters: {
            query: {
                targetId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalReviewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDraftV1"];
                };
            };
        };
    };
    close_config_api_v1_config_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRevisionRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_config_api_v1_config_discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRevisionRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDraftV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_config_operation_api_v1_config_operations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyEditOperationRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDraftV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preflight_config_api_v1_config_preflight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRevisionRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmissionPreflightV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_removal_impact_api_v1_config_removal_impact_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigRemovalImpactRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRemovalImpactV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_config_api_v1_config_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRevisionRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigReviewV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_config_api_v1_config_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRevisionRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDraftV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_config_api_v1_config_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRevisionRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    external_resources_api_v1_external_resources_get: {
        parameters: {
            query: {
                nodeId: string;
                expectedDraftRevision: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalResourceInventoryV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    external_resource_details_api_v1_external_resources_details_get: {
        parameters: {
            query: {
                nodeId: string;
                expectedDraftRevision: string;
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalResourceDetailsV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_external_resource_api_v1_external_resources_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveExternalResourceRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalResourceMutationV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_external_resource_api_v1_external_resources_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectExternalResourceRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigDraftV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_log_stream_api_v1_log_streams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartLogStreamRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogStreamV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_log_stream_api_v1_log_streams__stream_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogStreamStatusV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_log_events_api_v1_log_streams__stream_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellable log event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_log_page_api_v1_log_streams__stream_id__pages_get: {
        parameters: {
            query?: {
                before?: string | null;
                after?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                stream_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogPageV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manage_events_api_v1_manage_events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow state invalidation event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manage_state_api_v1_manage_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManageSnapshotV1"];
                };
            };
        };
    };
    list_log_targets_api_v1_nodes__node_id__log_targets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogTargetInventoryV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_operations_api_v1_operations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationListV1"];
                };
            };
        };
    };
    operation_events_api_v1_operations_events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tracked operation event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_outputs_api_v1_outputs_get: {
        parameters: {
            query: {
                targetId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputInventoryV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_output_api_v1_outputs_content_get: {
        parameters: {
            query: {
                outputId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputContentV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_output_api_v1_outputs_download_get: {
        parameters: {
            query: {
                outputId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete managed output download */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/yaml": unknown;
                    "text/plain": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_reset_api_v1_resets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteResetRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_reset_api_v1_resets_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPlanRequestV1"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPlanV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthV1"];
                };
            };
        };
    };
}
