// This file is auto-generated by @hey-api/openapi-ts

/**
 * HealthApiResponse
 */
export type HealthApiResponse = {
  /**
   * Checks
   */
  checks: {
    [key: string]: string;
  };
  status: HealthStatus;
};

/**
 * HealthStatus
 */
export type HealthStatus = "ok" | "error";

export type SystemHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/system/health";
};

export type SystemHealthResponses = {
  /**
   * Successful Response
   */
  200: HealthApiResponse;
};

export type SystemHealthResponse =
  SystemHealthResponses[keyof SystemHealthResponses];

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
