{{- if eq (default false .Values.aws.configureAwsEksResources) true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-metadata
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1" # Make accessible earlier for charts that mount
data:
  STAGE_NAME: {{ required "Missing required value: .Values.stageName" .Values.stageName | quote }}
  AWS_REGION: {{ required "Missing required value: .Values.aws.region" .Values.aws.region | quote }}
  ACCOUNT: {{ required "Missing required value: .Values.aws.account" (toString .Values.aws.account) | quote }}
{{- end }}