{{- if eq (default false .Values.aws.eksEnabled) true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-metadata
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
data:
  STAGE_NAME: "{{ .Values.stageName }}"
  AWS_REGION: "{{ .Values.aws.region }}"
{{- end }}