{{- if .Values.cluster.useCustomKarpenterNodePool }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-work-pool
spec:
  weight: 100
  limits:
    cpu: {{ .Values.workloadsNodePool.limits.cpu }}
    memory: {{ .Values.workloadsNodePool.limits.memory }}
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: {{ .Values.aws.nodeClassName }}
      requirements:
        {{- if .Values.workloadsNodePool.capacityTypes }}
        - key: karpenter.sh/capacity-type
          operator: In
          values: {{ .Values.workloadsNodePool.capacityTypes | toJson }}
        {{- end }}
        {{- if .Values.workloadsNodePool.instanceCategories }}
        - key: eks.amazonaws.com/instance-category
          operator: In
          values: {{ .Values.workloadsNodePool.instanceCategories | toJson }}
        {{- end }}
        {{- if .Values.workloadsNodePool.minInstanceGeneration }}
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values: [{{ .Values.workloadsNodePool.minInstanceGeneration | quote }}]
        {{- end }}
        {{- if .Values.workloadsNodePool.architectures }}
        - key: kubernetes.io/arch
          operator: In
          values: {{ .Values.workloadsNodePool.architectures | toJson }}
        {{- end }}
        {{- if .Values.workloadsNodePool.instanceSizes }}
        - key: eks.amazonaws.com/instance-size
          operator: In
          values: {{ .Values.workloadsNodePool.instanceSizes | toJson }}
        {{- end }}
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
  disruption:
    consolidationPolicy: {{ .Values.workloadsNodePool.disruption.consolidationPolicy }}
    consolidateAfter: {{ .Values.workloadsNodePool.disruption.consolidateAfter }}
{{- end }}
