apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-or-get-snapshot
spec:
  entrypoint: create-or-get-snapshot
  templates:
    - name: create-or-get-snapshot
      inputs:
        parameters:
          - name: source-name
          - name: source-config
          - name: snapshot-and-migration-config
          - name: s3-config
          - name: image-config
          - name: otel-collector-endpoint
      steps:
        - - name: get-existing-snapshot
            template: get-existing-snapshot
#            when: "{{='existingSnapshot' in fromJSON(inputs.parameters['snapshot-and-migration-config'])}}"
            arguments:
              parameters:
                - name: existing-snapshot
                  value: "{{='existingSnapshot' in fromJSON(inputs.parameters['snapshot-and-migration-config']) ? fromJSON(inputs.parameters['snapshot-and-migration-config'])['existingSnapshot'] : '' }}"

        - - name: create-snapshot
            templateRef:
              name: create-snapshot
              template: snapshot-workflow
            when: "{{='existingSnapshot' in fromJSON(inputs.parameters['snapshot-and-migration-config'])}} == false"
            arguments:
              parameters:
                - name: snapshot-name
                  value: "{{inputs.parameters.source-name}}"
                - name: source-config
                  value: "{{inputs.parameters.source-config}}"
                - name: s3-config
                  value: "{{inputs.parameters.s3-config}}"
                - name: otel-collector-endpoint
                  value: "{{inputs.parameters.otel-collector-endpoint}}"
                - name: indices
                  value: "{{=let sc=inputs.parameters['snapshot-and-migration-config']; hasKey(fromJSON(sc), 'indices') ? join(fromJSON(sc).indices, ',') : ''}}"
                - name: migration-console-image
                  value: "{{=fromJSON(inputs.parameters['image-config'])['migration-console']['image']}}"
                - name: migration-console-pull-policy
                  value: "{{=fromJSON(inputs.parameters['image-config'])['migration-console']['pull-policy']}}"

        - - name: collect-output
            template: collect-output
            arguments:
              parameters:
                - name: create-snapshot-output
                  value: "{{=steps['create-snapshot'].outputs.parameters['snapshot-config'] ?? ''}}"
                - name: existing-snapshot
                  value: "{{=steps['get-existing-snapshot'] == nil ? '' : (steps['get-existing-snapshot'].outputs.parameters['existing-snapshot'] ?? '')}}"

      outputs:
        parameters:
          - name: snapshot-config
            valueFrom:
              expression: "steps['collect-output'].outputs.parameters['snapshot-config']"

    - name: get-existing-snapshot
      steps: [[]]
      inputs:
        parameters:
          - name: existing-snapshot
      outputs:
        parameters:
          - name: existing-snapshot
            valueFrom:
              expression: "inputs.parameters['existing-snapshot']"

    - name: collect-output
      inputs:
        parameters:
          - name: create-snapshot-output
          - name: existing-snapshot
      outputs:
        parameters:
          - name: snapshot-config
            valueFrom:
              expression: "inputs.parameters['existing-snapshot'] != '' ? inputs.parameters['existing-snapshot'] : inputs.parameters['create-snapshot-output']"
      steps: [[]]