apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-snapshot
  # add labels later w/ patch
spec:
  entrypoint: snapshot-workflow
  templates:
    - name: snapshot-workflow
      inputs:
        parameters:
          - name: migration-console-image
          - name: migration-console-pull-policy
          - name: otel-collector-endpoint
          - name: snapshot-name
            value: "migration-assistant-snapshot"
          - name: source-config
            value: "{ \"endpoint\": \"http://ma-capture-proxy:9200\" }"
          - name: s3-config
            value: "{ \"repo_uri\": \"s3://snapshot\", \"aws_region\": \"us-east-1\" }"
          - name: indices
            value: ""
            description: "Which indices should be snapshot.  Default empty.  Empty string means all."
          - name: snapshot-config
            value: "{ \"snapshot_name\": \"{{inputs.parameters.snapshot-name}}\", \"otel_endpoint\": \"{{inputs.parameters.otel-collector-endpoint}}\" , \"s3\": {{inputs.parameters.s3-config}} }"
      outputs:
        parameters:
          - name: snapshot-config
            valueFrom:
              expression: "inputs.parameters['snapshot-config']"
      steps:
        - - name: get-console-config
            templateRef:
              name: migration-console-template
              template: get-console-config
            arguments:
              parameters:
                - name: source-cluster
                  value: "{{inputs.parameters.source-config}}"
                - name: snapshot-info
                  value: "{{inputs.parameters.snapshot-config}}"

        - - name: create-snapshot
            templateRef:
              name: migration-console-template
              template: run-console-with-config
            arguments:
              parameters:
                - name: config-contents
                  value: "{{steps.get-console-config.outputs.parameters.config-contents}}"
                - name: command
                  value: |
                    set -e && 
                    console --config-file=/config/migration_services.yaml -v snapshot delete --acknowledge-risk ;
                    console --config-file=/config/migration_services.yaml -v snapshot create
                - name: migration-console-image
                  value: "{{inputs.parameters.migration-console-image}}"
                - name: migration-console-pull-policy
                  value: "{{inputs.parameters.migration-console-pull-policy}}"

        - - name: check-snapshot-status
            template: check-snapshot-status
            arguments:
              parameters:
                - name: config-contents
                  value: "{{steps.get-console-config.outputs.parameters.config-contents}}"
                - name: migration-console-image
                  value: "{{inputs.parameters.migration-console-image}}"
                - name: migration-console-pull-policy
                  value: "{{inputs.parameters.migration-console-pull-policy}}"

    - name: check-snapshot-status
      inputs:
        parameters:
          - name: config-contents
          - name: migration-console-image
          - name: migration-console-pull-policy
      retryStrategy:
        limit: "200"
        retryPolicy: "Always"
        backoff:
          duration: "5"
          factor: "2"
          maxDuration: "300"
      steps:
        - - name: check-snapshot-completion
            templateRef:
              name: migration-console-template
              template: run-console-with-config
            arguments:
              parameters:
                - name: config-contents
                  value: "{{inputs.parameters.config-contents}}"
                - name: command
                  value: |
                    set -e && 
                    [ "$(console --config-file=/config/migration_services.yaml snapshot status)" = "SUCCESS" ] && exit 0 || exit 1
                - name: migration-console-image
                  value: "{{inputs.parameters.migration-console-image}}"
                - name: migration-console-pull-policy
                  value: "{{inputs.parameters.migration-console-pull-policy}}"
