apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: localstack-helper
spec:
  entrypoint: resolve-s3-endpoint

  templates:
    # Ideally this would not run for non-localstack endpoints, but conditionals in Argo seem rather tricky
    - name: resolve-s3-endpoint
      inputs:
        parameters:
          - name: s3-endpoint
          - name: migration-console-image
          - name: migration-console-pull-policy
      script:
        image: "{{inputs.parameters.migration-console-image}}"
        imagePullPolicy: "{{inputs.parameters.migration-console-pull-policy}}"
        command: [sh]
        source: |
          set -euo pipefail
          
          if [ -z "{{inputs.parameters.s3-endpoint}}" ] || ! echo "{{inputs.parameters.s3-endpoint}}" | grep -q "^http://localstack"; then
            echo "No S3 endpoint provided or not using localstack, skipping resolution"
            echo "{{inputs.parameters.s3-endpoint}}" > /tmp/resolved
            echo "false" > /tmp/isLocalstack
            exit 0
          fi
    
          echo "Resolving S3 endpoint IP address for {{inputs.parameters.s3-endpoint}}"
          RAW="{{inputs.parameters.s3-endpoint}}"
          S3_HOST=$(echo "$RAW" | sed -E 's|^https?://||' | sed -E 's|/.*$||' | sed -E 's|:[0-9]+$||')
          echo "Extracted hostname: $S3_HOST"
    
          S3_IP=$(getent hosts "$S3_HOST" | awk '{ print $1 }')
          if [ -z "$S3_IP" ]; then
            echo "Failed to resolve $S3_HOST, using original endpoint"
            FINAL_ENDPOINT="{{inputs.parameters.s3-endpoint}}"
          else
            echo "Resolved $S3_HOST to IP: $S3_IP"
            if echo "{{inputs.parameters.s3-endpoint}}" | grep -q "^https"; then
              PROTOCOL="https://"
            else
              PROTOCOL="http://"
            fi
          
            PORT=$(echo "{{inputs.parameters.s3-endpoint}}" | grep -Eo ':[0-9]+' || true)
            FINAL_ENDPOINT="${PROTOCOL}${S3_IP}${PORT}"
          fi
    
          echo "Final resolved S3 endpoint: $FINAL_ENDPOINT"
          echo "$FINAL_ENDPOINT" > /tmp/resolved
          echo "true" > /tmp/isLocalstack
      outputs:
        parameters:
          - name: resolved-s3-endpoint
            valueFrom:
              path: /tmp/resolved
          - name: is-localstack-endpoint
            valueFrom:
              path: /tmp/isLocalstack
