apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: metadata-migration
spec:
  entrypoint: migrate-metadata-from-config

  templates:
    - name: migrate-metadata-from-config
      inputs:
        parameters:
          - name: snapshot-config
            description: "Details of the snapshot to use"
          - name: target-config
            description: "Target cluster details"
          - name: metadata-migration-config
            description: "Metadata migration details"
          - name: migration-console-image
          - name: migration-console-pull-policy
          - name: localstack-enabled
          - name: source-config
            description: "Source cluster details (Optional)"
            value: ""

      steps:
        - - name: get-console-config
            templateRef:
              name: migration-console-template
              template: get-console-config
            arguments:
              parameters:
                - name: source-cluster
                  value: "{{inputs.parameters.source-config}}"
                - name: target-cluster
                  value: "{{inputs.parameters.target-config}}"
                - name: snapshot-info
                  value: "{{inputs.parameters.snapshot-config}}"
                - name: metadata-info
                  value: "{{inputs.parameters.metadata-migration-config}}"
        - - name: run-metadata-migration
            templateRef:
              name: migration-console-template
              template: run-console-with-config
            arguments:
              parameters:
                - name: config-contents
                  value: "{{steps.get-console-config.outputs.parameters.config-contents}}"
                - name: command
                  value: |
                    set -e &&                    
                    console --config-file=/config/migration_services.yaml -v metadata evaluate ;
                    console --config-file=/config/migration_services.yaml -v metadata migrate
                - name: use-localstack-aws-creds
                  value: "{{inputs.parameters.localstack-enabled}}"
                - name: migration-console-image
                  value: "{{inputs.parameters.migration-console-image}}"
                - name: migration-console-pull-policy
                  value: "{{inputs.parameters.migration-console-pull-policy}}"
