apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.pvcClaimName }}
spec:
  accessModes:
    - {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  {{- if .Values.volume.storageClass }}
  storageClassName: {{ .Values.volume.storageClass }}
  {{- end }}
