name: Setup CI Environment
description: Sets up all required runtimes and environment versions
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: "corretto"

    - uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.12.1

    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install pipenv globally
      run: |
        python3 -m pip install --upgrade pipenv
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Aggressive disk cleanup
      run: |
        # Remove .NET SDKs
        sudo rm -rf /usr/share/dotnet

        # Remove Swift toolchain
        sudo rm -rf /usr/share/swift

        # Remove Haskell (GHC)
        sudo rm -rf /usr/local/.ghcup

        # Remove Julia
        sudo rm -rf /usr/local/julia*

        # Remove Android SDKs
        sudo rm -rf /usr/local/lib/android

        # Remove Chromium (optional if not using for browser tests)
        sudo rm -rf /usr/local/share/chromium

        # Remove Microsoft/Edge and Google Chrome builds
        sudo rm -rf /opt/microsoft /opt/google

        # Remove Azure CLI
        sudo rm -rf /opt/az

        # Remove PowerShell
        sudo rm -rf /usr/local/share/powershell