# Generated by Django 5.1.3 on 2024-12-07 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transform_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
