/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.opensearch.migrations.trafficcapture.proxyserver;

import org.apache.commons.text.WordUtils;

public class Main {
    public static void main(String[] args) {
        System.out.println(WordUtils.capitalize("Hi World"));
    }
}
