apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "generic.fullname" . }}-website
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "generic.fullname" . }}-website
                port:
                  number: 80
