apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}-website
spec:
  selector:
    app: {{ include "generic.fullname" . }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
