/* tslint:disable */
/* eslint-disable */
/**
 * Migration Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthApiResponse,
} from '../models/index';
import {
    HealthApiResponseFromJSON,
    HealthApiResponseToJSON,
} from '../models/index';

/**
 * SystemApi - interface
 * 
 * @export
 * @interface SystemApiInterface
 */
export interface SystemApiInterface {
    /**
     * 
     * @summary Health
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemApiInterface
     */
    healthSystemHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthApiResponse>>;

    /**
     * Health
     */
    healthSystemHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthApiResponse>;

}

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI implements SystemApiInterface {

    /**
     * Health
     */
    async healthSystemHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/system/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthApiResponseFromJSON(jsonValue));
    }

    /**
     * Health
     */
    async healthSystemHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthApiResponse> {
        const response = await this.healthSystemHealthGetRaw(initOverrides);
        return await response.value();
    }

}
