/* tslint:disable */
/* eslint-disable */
/**
 * Transformation API
 * API for JSON transformation logic.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * * `Elasticsearch 6.8` - ES_6_8 * `Elasticsearch 7.10` - ES_7_10
 * @export
 * @enum {string}
 */

export const SourceVersionEnum = {
    _68: 'Elasticsearch 6.8',
    _710: 'Elasticsearch 7.10'
} as const;

export type SourceVersionEnum = typeof SourceVersionEnum[keyof typeof SourceVersionEnum];


/**
 * * `OpenSearch 2.17` - OS_2_17
 * @export
 * @enum {string}
 */

export const TargetVersionEnum = {
    OpenSearch217: 'OpenSearch 2.17'
} as const;

export type TargetVersionEnum = typeof TargetVersionEnum[keyof typeof TargetVersionEnum];


/**
 * * `Python` - PYTHON
 * @export
 * @enum {string}
 */

export const TransformLanguageEnum = {
    Python: 'Python'
} as const;

export type TransformLanguageEnum = typeof TransformLanguageEnum[keyof typeof TransformLanguageEnum];


/**
 * 
 * @export
 * @interface TransformsIndexCreateRequest
 */
export interface TransformsIndexCreateRequest {
    /**
     * 
     * @type {SourceVersionEnum}
     * @memberof TransformsIndexCreateRequest
     */
    'source_version': SourceVersionEnum;
    /**
     * 
     * @type {TargetVersionEnum}
     * @memberof TransformsIndexCreateRequest
     */
    'target_version': TargetVersionEnum;
    /**
     * 
     * @type {TransformLanguageEnum}
     * @memberof TransformsIndexCreateRequest
     */
    'transform_language': TransformLanguageEnum;
    /**
     * 
     * @type {TransformsIndexCreateRequestInputShape}
     * @memberof TransformsIndexCreateRequest
     */
    'input_shape': TransformsIndexCreateRequestInputShape;
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexCreateRequest
     */
    'transform_logic'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexCreateRequest
     */
    'user_guidance'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexCreateRequest
     */
    'test_target_url'?: string;
}


/**
 * 
 * @export
 * @interface TransformsIndexCreateRequestInputShape
 */
export interface TransformsIndexCreateRequestInputShape {
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexCreateRequestInputShape
     */
    'index_name': string;
    /**
     * 
     * @type {object}
     * @memberof TransformsIndexCreateRequestInputShape
     */
    'index_json': object;
}
/**
 * 
 * @export
 * @interface TransformsIndexCreateResponse
 */
export interface TransformsIndexCreateResponse {
    /**
     * 
     * @type {Array<TransformsIndexCreateRequestInputShape>}
     * @memberof TransformsIndexCreateResponse
     */
    'output_shape': Array<TransformsIndexCreateRequestInputShape>;
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexCreateResponse
     */
    'transform_logic': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransformsIndexCreateResponse
     */
    'validation_report': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexCreateResponse
     */
    'validation_outcome': string;
}
/**
 * 
 * @export
 * @interface TransformsIndexTestRequest
 */
export interface TransformsIndexTestRequest {
    /**
     * 
     * @type {TransformLanguageEnum}
     * @memberof TransformsIndexTestRequest
     */
    'transform_language': TransformLanguageEnum;
    /**
     * 
     * @type {SourceVersionEnum}
     * @memberof TransformsIndexTestRequest
     */
    'source_version': SourceVersionEnum;
    /**
     * 
     * @type {TargetVersionEnum}
     * @memberof TransformsIndexTestRequest
     */
    'target_version': TargetVersionEnum;
    /**
     * 
     * @type {TransformsIndexCreateRequestInputShape}
     * @memberof TransformsIndexTestRequest
     */
    'input_shape': TransformsIndexCreateRequestInputShape;
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexTestRequest
     */
    'transform_logic': string;
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexTestRequest
     */
    'test_target_url'?: string;
}


/**
 * 
 * @export
 * @interface TransformsIndexTestResponse
 */
export interface TransformsIndexTestResponse {
    /**
     * 
     * @type {Array<TransformsIndexCreateRequestInputShape>}
     * @memberof TransformsIndexTestResponse
     */
    'output_shape': Array<TransformsIndexCreateRequestInputShape>;
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexTestResponse
     */
    'transform_logic': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransformsIndexTestResponse
     */
    'validation_report': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TransformsIndexTestResponse
     */
    'validation_outcome': string;
}

/**
 * ApiApi - axios parameter creator
 * @export
 */
export const ApiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
         * @param {ApiSchemaRetrieveFormatEnum} [format] 
         * @param {ApiSchemaRetrieveLangEnum} [lang] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSchemaRetrieve: async (format?: ApiSchemaRetrieveFormatEnum, lang?: ApiSchemaRetrieveLangEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/schema/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication cookieAuth required

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (lang !== undefined) {
                localVarQueryParameter['lang'] = lang;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApiApi - functional programming interface
 * @export
 */
export const ApiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApiApiAxiosParamCreator(configuration)
    return {
        /**
         * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
         * @param {ApiSchemaRetrieveFormatEnum} [format] 
         * @param {ApiSchemaRetrieveLangEnum} [lang] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSchemaRetrieve(format?: ApiSchemaRetrieveFormatEnum, lang?: ApiSchemaRetrieveLangEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSchemaRetrieve(format, lang, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiApi.apiSchemaRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ApiApi - factory interface
 * @export
 */
export const ApiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApiApiFp(configuration)
    return {
        /**
         * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
         * @param {ApiSchemaRetrieveFormatEnum} [format] 
         * @param {ApiSchemaRetrieveLangEnum} [lang] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSchemaRetrieve(format?: ApiSchemaRetrieveFormatEnum, lang?: ApiSchemaRetrieveLangEnum, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.apiSchemaRetrieve(format, lang, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApiApi - object-oriented interface
 * @export
 * @class ApiApi
 * @extends {BaseAPI}
 */
export class ApiApi extends BaseAPI {
    /**
     * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
     * @param {ApiSchemaRetrieveFormatEnum} [format] 
     * @param {ApiSchemaRetrieveLangEnum} [lang] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiApi
     */
    public apiSchemaRetrieve(format?: ApiSchemaRetrieveFormatEnum, lang?: ApiSchemaRetrieveLangEnum, options?: RawAxiosRequestConfig) {
        return ApiApiFp(this.configuration).apiSchemaRetrieve(format, lang, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ApiSchemaRetrieveFormatEnum = {
    Json: 'json',
    Yaml: 'yaml'
} as const;
export type ApiSchemaRetrieveFormatEnum = typeof ApiSchemaRetrieveFormatEnum[keyof typeof ApiSchemaRetrieveFormatEnum];
/**
 * @export
 */
export const ApiSchemaRetrieveLangEnum = {
    Af: 'af',
    Ar: 'ar',
    ArDz: 'ar-dz',
    Ast: 'ast',
    Az: 'az',
    Be: 'be',
    Bg: 'bg',
    Bn: 'bn',
    Br: 'br',
    Bs: 'bs',
    Ca: 'ca',
    Ckb: 'ckb',
    Cs: 'cs',
    Cy: 'cy',
    Da: 'da',
    De: 'de',
    Dsb: 'dsb',
    El: 'el',
    En: 'en',
    EnAu: 'en-au',
    EnGb: 'en-gb',
    Eo: 'eo',
    Es: 'es',
    EsAr: 'es-ar',
    EsCo: 'es-co',
    EsMx: 'es-mx',
    EsNi: 'es-ni',
    EsVe: 'es-ve',
    Et: 'et',
    Eu: 'eu',
    Fa: 'fa',
    Fi: 'fi',
    Fr: 'fr',
    Fy: 'fy',
    Ga: 'ga',
    Gd: 'gd',
    Gl: 'gl',
    He: 'he',
    Hi: 'hi',
    Hr: 'hr',
    Hsb: 'hsb',
    Hu: 'hu',
    Hy: 'hy',
    Ia: 'ia',
    Id: 'id',
    Ig: 'ig',
    Io: 'io',
    Is: 'is',
    It: 'it',
    Ja: 'ja',
    Ka: 'ka',
    Kab: 'kab',
    Kk: 'kk',
    Km: 'km',
    Kn: 'kn',
    Ko: 'ko',
    Ky: 'ky',
    Lb: 'lb',
    Lt: 'lt',
    Lv: 'lv',
    Mk: 'mk',
    Ml: 'ml',
    Mn: 'mn',
    Mr: 'mr',
    Ms: 'ms',
    My: 'my',
    Nb: 'nb',
    Ne: 'ne',
    Nl: 'nl',
    Nn: 'nn',
    Os: 'os',
    Pa: 'pa',
    Pl: 'pl',
    Pt: 'pt',
    PtBr: 'pt-br',
    Ro: 'ro',
    Ru: 'ru',
    Sk: 'sk',
    Sl: 'sl',
    Sq: 'sq',
    Sr: 'sr',
    SrLatn: 'sr-latn',
    Sv: 'sv',
    Sw: 'sw',
    Ta: 'ta',
    Te: 'te',
    Tg: 'tg',
    Th: 'th',
    Tk: 'tk',
    Tr: 'tr',
    Tt: 'tt',
    Udm: 'udm',
    Ug: 'ug',
    Uk: 'uk',
    Ur: 'ur',
    Uz: 'uz',
    Vi: 'vi',
    ZhHans: 'zh-hans',
    ZhHant: 'zh-hant'
} as const;
export type ApiSchemaRetrieveLangEnum = typeof ApiSchemaRetrieveLangEnum[keyof typeof ApiSchemaRetrieveLangEnum];


/**
 * TransformsApi - axios parameter creator
 * @export
 */
export const TransformsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {TransformsIndexCreateRequest} transformsIndexCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transformsIndexCreateCreate: async (transformsIndexCreateRequest: TransformsIndexCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transformsIndexCreateRequest' is not null or undefined
            assertParamExists('transformsIndexCreateCreate', 'transformsIndexCreateRequest', transformsIndexCreateRequest)
            const localVarPath = `/transforms/index/create/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication cookieAuth required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transformsIndexCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {TransformsIndexTestRequest} transformsIndexTestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transformsIndexTestCreate: async (transformsIndexTestRequest: TransformsIndexTestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transformsIndexTestRequest' is not null or undefined
            assertParamExists('transformsIndexTestCreate', 'transformsIndexTestRequest', transformsIndexTestRequest)
            const localVarPath = `/transforms/index/test/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            // authentication cookieAuth required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transformsIndexTestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransformsApi - functional programming interface
 * @export
 */
export const TransformsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransformsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {TransformsIndexCreateRequest} transformsIndexCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transformsIndexCreateCreate(transformsIndexCreateRequest: TransformsIndexCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransformsIndexCreateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transformsIndexCreateCreate(transformsIndexCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransformsApi.transformsIndexCreateCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {TransformsIndexTestRequest} transformsIndexTestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transformsIndexTestCreate(transformsIndexTestRequest: TransformsIndexTestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransformsIndexTestResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transformsIndexTestCreate(transformsIndexTestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransformsApi.transformsIndexTestCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TransformsApi - factory interface
 * @export
 */
export const TransformsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransformsApiFp(configuration)
    return {
        /**
         * 
         * @param {TransformsIndexCreateRequest} transformsIndexCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transformsIndexCreateCreate(transformsIndexCreateRequest: TransformsIndexCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<TransformsIndexCreateResponse> {
            return localVarFp.transformsIndexCreateCreate(transformsIndexCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {TransformsIndexTestRequest} transformsIndexTestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transformsIndexTestCreate(transformsIndexTestRequest: TransformsIndexTestRequest, options?: RawAxiosRequestConfig): AxiosPromise<TransformsIndexTestResponse> {
            return localVarFp.transformsIndexTestCreate(transformsIndexTestRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TransformsApi - object-oriented interface
 * @export
 * @class TransformsApi
 * @extends {BaseAPI}
 */
export class TransformsApi extends BaseAPI {
    /**
     * 
     * @param {TransformsIndexCreateRequest} transformsIndexCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransformsApi
     */
    public transformsIndexCreateCreate(transformsIndexCreateRequest: TransformsIndexCreateRequest, options?: RawAxiosRequestConfig) {
        return TransformsApiFp(this.configuration).transformsIndexCreateCreate(transformsIndexCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {TransformsIndexTestRequest} transformsIndexTestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransformsApi
     */
    public transformsIndexTestCreate(transformsIndexTestRequest: TransformsIndexTestRequest, options?: RawAxiosRequestConfig) {
        return TransformsApiFp(this.configuration).transformsIndexTestCreate(transformsIndexTestRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



