// Copyright OpenSearch Contributors
// SPDX-License-Identifier: Apache-2.0

package mcp

var ProvisionedRequestSchema = map[string]interface{}{
	"type":        "object",
	"description": "Parameters for estimating provisioned OpenSearch domain costs. Specify exactly one of: search, vector, or timeSeries.",
	"properties": map[string]interface{}{
		"search": map[string]interface{}{
			"type":        "object",
			"description": "Configuration for search workload estimation",
			"properties": map[string]interface{}{
				"size":                  map[string]interface{}{"type": "number", "description": "Data size in GB"},
				"targetShardSize":       map[string]interface{}{"type": "integer", "description": "Target size per shard in GB (default: 25)"},
				"azs":                   map[string]interface{}{"type": "integer", "description": "Number of availability zones (default: 3). For Production use 3 AZs for high availability. For Non-production/dev environments, use 1 AZ to reduce costs."},
				"replicas":              map[string]interface{}{"type": "integer", "description": "Number of replicas (default: 1). For Production - Performant use 2 replicas for higher availability. For Production - Cost optimized or Balanced use 1. For Non-production/dev environments, use 0 to minimize resource usage."},
				"CPUsPerShard":          map[string]interface{}{"type": "number", "description": "CPU cores per shard (default: 1.5). For Production - Performant use 2. For Production - Balanced use 1.5. For Production - Cost optimized use 1.0. For Non-production/dev use 1 or lower to minimize resource usage."},
				"region":                map[string]interface{}{"type": "string", "description": "AWS region code (default: 'us-east-1')"},
				"pricingType":           map[string]interface{}{"type": "string", "description": "Pricing model: OnDemand, AURI1 (All Upfront for 1 year), AURI3 (All Upfront for 3 years), NURI1 (No Upfront for 1 year), NURI3 (No Upfront for 3 years), PURI1 (Partial Upfront for 1 year), PURI3 (Partial Upfront for 3 years)"},
				"preferInternalStorage": map[string]interface{}{"type": "boolean", "description": "Prefer instance store over EBS storage. For Production - Performant set to true for better performance. For Production - Cost optimized or Balanced, evaluate based on data size. For Non-production/dev, set to false."},
				"storageClass":          map[string]interface{}{"type": "string", "description": "EBS storage type (default: gp3). For Production - Performant use NVME based disk. For Production - Cost optimized consider gp3. For Production - Balanced or Non-production/dev use gp3 with default settings."},
				"freeStorageRequired":   map[string]interface{}{"type": "integer", "description": "Free storage percentage required (default: 25). For Non-production/dev use 15-20%."},
				"indexExpansionRate":    map[string]interface{}{"type": "integer", "description": "Index expansion rate percentage. If the workload is dealing with complex full text fields, use a higher value. For Production environments use 10-15%. For Non-production/dev use 5-10% (default: 10)"},
				"derivedSource":         map[string]interface{}{"type": "boolean", "description": "Enable derived source for ~25% storage reduction. Stores only essential fields, reconstructing _source on retrieval. Recommended for search workloads with large documents."},
				"zstdCompression":       map[string]interface{}{"type": "boolean", "description": "Enable ZSTD index codec for ~15% storage reduction. Can be combined with derived source for up to ~36% total reduction."},
				"minimumJVM":            map[string]interface{}{"type": "number", "description": "Minimum JVM heap size in GB (default: 0). For Production - Performant use 32GB. For Production - Balanced use 8GB. For Production - Cost optimized use 8GB. For Non-production/dev use 0-4GB to let the system calculate based on instance size."},
				"dedicatedManager":      map[string]interface{}{"type": "boolean", "description": "Use dedicated manager nodes (default: true). For all Production environments (Performant, Balanced, Cost optimized) set to true. For Non-production/dev set to false to reduce costs."},
				"activePrimaryShards":   map[string]interface{}{"type": "integer", "description": "Override calculated primary shards. Use this option only if you know what you're doing (default: 0)"},
				"instanceTypes":         map[string]interface{}{"type": "array", "items": map[string]interface{}{"type": "string"}, "description": "Filter allowed instance types."},
				"instanceFamily":        map[string]interface{}{"type": "array", "items": map[string]interface{}{"type": "string"}, "description": "Instance families: ['Memory optimized', 'Compute optimized', 'Storage optimized', 'OpenSearch optimized']"},
				"edp":                   map[string]interface{}{"type": "number", "description": "Enterprise discount percentage. Apply your organization's discount if available."},
				"config":                map[string]interface{}{"type": "string", "description": "Preset configuration: 'dev' or 'production'"},
				"multiAzWithStandby":    map[string]interface{}{"type": "boolean", "description": "Enable Multi-AZ with Standby for 99.99% availability. When enabled, 1/3 of instances are standby nodes that don't take traffic. Thread calculations are based on 2/3 of the instance count. Requires minimum 2 replicas. Use for Production - Performant workloads requiring highest availability."},
				// Warm and Cold storage tier support for search workloads
				"warmPercentage":         map[string]interface{}{"type": "integer", "description": "Percentage of data to store in warm tier (UltraWarm or OI2) (0-100, default: 0). Warm tier uses SSD-backed storage with lower cost but higher latency. Useful for less-frequently accessed data."},
				"coldPercentage":         map[string]interface{}{"type": "integer", "description": "Percentage of data to archive in cold tier (S3) (0-100, default: 0). Cold tier stores data in S3 for archival with lowest cost but highest latency. Suitable for rarely queried historical data."},
				"warmInstanceType":       map[string]interface{}{"type": "string", "description": "Override warm instance type selection. UltraWarm options: 'ultrawarm1.medium.search' (1.5TB cache) or 'ultrawarm1.large.search' (20TB cache). OI2 options (requires OpenSearch Optimized hot nodes): 'oi2.xlarge.search', 'oi2.2xlarge.search', 'oi2.4xlarge.search', 'oi2.8xlarge.search', 'oi2.16xlarge.search'. If not specified, auto-selects based on storage size."},
				"autoSelectWarmInstance": map[string]interface{}{"type": "boolean", "description": "Enable automatic warm instance selection based on storage requirements (default: true). Set to false to use warmInstanceType override."},
			},
		},
		"vector": map[string]interface{}{
			"type":        "object",
			"description": "Configuration for vector search workload estimation",
			"properties": map[string]interface{}{
				"size":                       map[string]interface{}{"type": "number", "description": "Data size in GB"},
				"targetShardSize":            map[string]interface{}{"type": "integer", "description": "Target size per shard in GB (default: 45)"},
				"azs":                        map[string]interface{}{"type": "integer", "description": "Number of availability zones (default: 3). For Production environments (Performant, Balanced, Cost optimized) use 3 AZs for high availability. For Non-production/dev environments, use 1 AZ to reduce costs."},
				"replicas":                   map[string]interface{}{"type": "integer", "description": "Number of replicas (default: 1). For Production - Performant use 2 replicas for higher availability. For Production - Balanced or Cost optimized use 1. For Non-production/dev environments, use 0 to minimize resource usage."},
				"CPUsPerShard":               map[string]interface{}{"type": "number", "description": "CPU cores per shard (default: 1.5). For Production - Performant use 2. For Production - Balanced use 1.5. For Production - Cost optimized use 1.0. For Non-production/dev use 1 or lower to minimize resource usage."},
				"region":                     map[string]interface{}{"type": "string", "description": "AWS region (default: 'us-east-1')"},
				"pricingType":                map[string]interface{}{"type": "string", "description": "Pricing model: OnDemand, AURI1 (All Upfront for 1 year), AURI3 (All Upfront for 3 years), NURI1 (No Upfront for 1 year), NURI3 (No Upfront for 3 years), PURI1 (Partial Upfront for 1 year), PURI3 (Partial Upfront for 3 years)"},
				"vectorEngineType":           map[string]interface{}{"type": "string", "description": "Vector engine: hnsw, hnswfp16, hnswint8, hnswbv, ivf, ivffp16, ivfint8, ivfbv, ivfpq, hnswpq. For Production - Performant use hnsw for best accuracy. For Production - Balanced use hnswfp16 for good balance of accuracy and memory usage. For Production - Cost optimized use hnswint8 or hnswpq for memory efficiency. For Non-production/dev use ivfpq for minimal resource usage. Note: on-disk mode only works with uncompressed engines (hnsw, ivf)."},
				"vectorCount":                map[string]interface{}{"type": "integer", "description": "Total number of vectors"},
				"dimensionsCount":            map[string]interface{}{"type": "integer", "description": "Vector dimensions (default: 384)"},
				"vectorMemoryCircuitBreaker": map[string]interface{}{"type": "integer", "description": "Memory circuit breaker percentage (default: 75)"},
				"maxEdges":                   map[string]interface{}{"type": "integer", "description": "Maximum edges in HNSW graph (default: 16)."},
				"segments":                   map[string]interface{}{"type": "integer", "description": "Number of segments (default: 100)."},
				"nlist":                      map[string]interface{}{"type": "integer", "description": "Number of clusters for IVF."},
				"PQEdges":                    map[string]interface{}{"type": "integer", "description": "PQ edges for HNSWPQ."},
				"subVectors":                 map[string]interface{}{"type": "integer", "description": "Sub-vectors for IVFPQ."},
				"codeSize":                   map[string]interface{}{"type": "integer", "description": "Code size for PQ methods."},
				"excludeVectorSource":        map[string]interface{}{"type": "boolean", "description": "Exclude vector source from storage calculation."},
				"exactKNN":                   map[string]interface{}{"type": "boolean", "description": "Use exact KNN for vector search instead of approximate methods. enable this where there are strong filters or highest accuracy."},
				"onDisk":                     map[string]interface{}{"type": "boolean", "description": "Enable on-disk mode with memory compression for uncompressed engines (HNSW, IVF). provides highest savings where the latency is slightly slower. make this as default."},
				"compressionLevel":           map[string]interface{}{"type": "integer", "description": "Compression level for on-disk mode. Valid values: 2, 4, 8, 16, 32. default value: 32. For Production - Performant use 2-4 for minimal performance impact. For Production - Balanced use 8-16. For Production - Cost optimized, use 32 for maximum memory savings."},
				"derivedSource":              map[string]interface{}{"type": "boolean", "description": "Enable derived source for ~30% storage reduction on non-vector document data. Applies to the data size, not the vector index."},
				"zstdCompression":            map[string]interface{}{"type": "boolean", "description": "Enable ZSTD index codec for ~20% storage reduction on non-vector document data. Can be combined with derived source."},
				"preferInternalStorage":      map[string]interface{}{"type": "boolean", "description": "Prefer instance store over EBS storage. For Production - Performant set to true for better performance. For Production - Cost optimized or Balanced, evaluate based on data size. For Non-production/dev, set to false."},
				"storageClass":               map[string]interface{}{"type": "string", "description": "EBS storage type (default: gp3). For Production - Performant use NVME based disk. For Production - Cost optimized consider standard. For Production - Balanced or Non-production/dev use gp3 with default settings."},
				"freeStorageRequired":        map[string]interface{}{"type": "integer", "description": "Free storage percentage required (default: 25). For Non-production/dev use 15-20%."},
				"indexExpansionRate":         map[string]interface{}{"type": "integer", "description": "Index expansion rate percentage (default: 25). For Production environments use 25-30%. For Non-production/dev use 15-20%."},
				"minimumJVM":                 map[string]interface{}{"type": "number", "description": "Minimum JVM heap size in GB (default: 0). For Production - Performant use 32GB. For Production - Balanced use 8GB. For Production - Cost optimized use 8GB. For Non-production/dev use 0 to let the system calculate based on instance size."},
				"dedicatedManager":           map[string]interface{}{"type": "boolean", "description": "Use dedicated manager nodes (default: true). For all Production environments (Performant, Balanced, Cost optimized) set to true. For Non-production/dev set to false to reduce costs."},
				"activePrimaryShards":        map[string]interface{}{"type": "integer", "description": "Override calculated primary shards. Use this option only if you know what you're doing (default: 0)"},
				"instanceTypes":              map[string]interface{}{"type": "array", "items": map[string]interface{}{"type": "string"}, "description": "Filter allowed instance types"},
				"instanceFamily":             map[string]interface{}{"type": "array", "items": map[string]interface{}{"type": "string"}, "description": "Instance families: ['Memory optimized', 'Compute optimized', 'Storage optimized', 'OpenSearch optimized']"},
				"edp":                        map[string]interface{}{"type": "number", "description": "Enterprise discount percentage. Apply your organization's discount if available."},
				"config":                     map[string]interface{}{"type": "string", "description": "Preset configuration: 'dev' or 'production'"},
				"multiAzWithStandby":         map[string]interface{}{"type": "boolean", "description": "Enable Multi-AZ with Standby for 99.99% availability. When enabled, 1/3 of instances are standby nodes that don't take traffic. Thread calculations are based on 2/3 of the instance count. Requires minimum 2 replicas. Use for Production - Performant workloads requiring highest availability."},
				"warmPercentage":             map[string]interface{}{"type": "integer", "description": "Percentage of vectors to store in warm tier (UltraWarm) (0-100, default: 0). Available in OpenSearch 2.17+. Warm tier uses SSD-backed storage with lower cost but higher latency. Useful for less-frequently accessed vectors."},
				"coldPercentage":             map[string]interface{}{"type": "integer", "description": "Percentage of vectors to archive in cold tier (S3) (0-100, default: 0). Cold tier stores vectors in S3 for archival with lowest cost but highest latency. Suitable for rarely queried historical vectors."},
				"warmInstanceType":           map[string]interface{}{"type": "string", "description": "Override UltraWarm instance type selection. Options: 'ultrawarm1.medium.search' (1.5TB cache) or 'ultrawarm1.large.search' (20TB cache). If not specified, auto-selects based on storage size."},
				"autoSelectWarmInstance":     map[string]interface{}{"type": "boolean", "description": "Enable automatic UltraWarm instance selection based on storage requirements (default: true). Set to false to use warmInstanceType override."},
			},
		},
		"timeSeries": map[string]interface{}{
			"type":        "object",
			"description": "Configuration for time-series workload estimation",
			"properties": map[string]interface{}{
				"size":                  map[string]interface{}{"type": "number", "description": "Data ingestion size in GB per period. The period could be hourly, daily, weekly, monthly, or combined periods"},
				"targetShardSize":       map[string]interface{}{"type": "integer", "description": "Target shard size in GB (default: 45)"},
				"azs":                   map[string]interface{}{"type": "integer", "description": "Number of availability zones (default: 3). For Production environments (Performant, Balanced, Cost optimized) use 3 AZs for high availability. For Non-production/dev environments, use 1 AZ to reduce costs."},
				"replicas":              map[string]interface{}{"type": "integer", "description": "Number of replicas (default: 1). For Production - Performant use 2 replicas for higher availability. For Production - Balanced or Cost optimized use 1. For Non-production/dev environments, use 0 to minimize resource usage."},
				"CPUsPerShard":          map[string]interface{}{"type": "number", "description": "CPU cores per shard (default: 1.25). For Production - Performant use 1.5. For Production - Balanced use 1.25. For Production - Cost optimized use 1.0. For Non-production/dev use 1 or lower."},
				"hotRetentionPeriod":    map[string]interface{}{"type": "integer", "description": "Period to keep data in hot storage."},
				"warmRetentionPeriod":   map[string]interface{}{"type": "integer", "description": "Period to keep data in warm storage."},
				"coldRetentionPeriod":   map[string]interface{}{"type": "integer", "description": "Period to keep data in cold storage."},
				"region":                map[string]interface{}{"type": "string", "description": "AWS region (default: 'us-east-1')"},
				"pricingType":           map[string]interface{}{"type": "string", "description": "Pricing model: OnDemand, AURI1 (All Upfront for 1 year), AURI3 (All Upfront for 3 years), NURI1 (No Upfront for 1 year), NURI3 (No Upfront for 3 years), PURI1 (Partial Upfront for 1 year), PURI3 (Partial Upfront for 3 years)."},
				"preferInternalStorage": map[string]interface{}{"type": "boolean", "description": "Prefer instance store over EBS storage. For Production - Performant set to true for better performance. For Production - Cost optimized or Balanced, evaluate based on data size. For Non-production/dev, set to false."},
				"storageClass":          map[string]interface{}{"type": "string", "description": "EBS storage type (default: gp3). For Production - Performant use NVME based disk. For Production - Cost optimized consider gp3. For Production - Balanced or Non-production/dev use gp3 with default settings."},
				"freeStorageRequired":   map[string]interface{}{"type": "integer", "description": "Free storage percentage required (default: 25). For Non-production/dev use 15-20%."},
				"indexExpansionRate":    map[string]interface{}{"type": "integer", "description": "Index expansion rate percentage. With a strong compression like zstd, the index can shrink by up to 35%. In that case, use negative values (default: 10)"},
				"derivedSource":         map[string]interface{}{"type": "boolean", "description": "Enable derived source for ~30% storage reduction. Highly recommended for log analytics and time-series workloads."},
				"zstdCompression":       map[string]interface{}{"type": "boolean", "description": "Enable ZSTD index codec for ~20% storage reduction. Can be combined with derived source for up to ~44% total reduction."},
				"minimumJVM":            map[string]interface{}{"type": "number", "description": "Minimum JVM heap size in GB (default: 0). For Production - Performant use 32GB. For Production - Balanced use 8GB. For Production - Cost optimized use 8GB. For Non-production/dev use 0-4GB to let the system calculate based on instance size."},
				"dedicatedManager":      map[string]interface{}{"type": "boolean", "description": "Use dedicated manager nodes (default: true). For all Production environments (Performant, Balanced, Cost optimized) set to true. For Non-production/dev set to false to reduce costs."},
				"activePrimaryShards":   map[string]interface{}{"type": "integer", "description": "Override calculated primary shards. Use this option only if you know what you're doing (default: 0)"},
				"instanceTypes":         map[string]interface{}{"type": "array", "items": map[string]interface{}{"type": "string"}, "description": "Filter allowed instance types"},
				"instanceFamily":        map[string]interface{}{"type": "array", "items": map[string]interface{}{"type": "string"}, "description": "Instance families: ['Memory optimized', 'Compute optimized', 'Storage optimized', 'OpenSearch optimized']"},
				"edp":                   map[string]interface{}{"type": "number", "description": "Enterprise discount percentage. Apply your organization's discount if available."},
				"config":                map[string]interface{}{"type": "string", "description": "Preset configuration: 'dev' or 'production'"},
				"multiAzWithStandby":    map[string]interface{}{"type": "boolean", "description": "Enable Multi-AZ with Standby for 99.99% availability. When enabled, 1/3 of instances are standby nodes that don't take traffic. Thread calculations are based on 2/3 of the instance count. Requires minimum 2 replicas. Use for Production - Performant workloads requiring highest availability."},
				"remoteStorage": map[string]interface{}{
					"type":        "object",
					"description": "Remote storage configuration for inactive shards. For Production - Cost optimized, consider using DROP_REPLICA_FOR_NONACTIVE_SHARDS to reduce storage costs for inactive shards. For Production - Performant, avoid using this option to maintain query performance. For Production - Balanced or Non-production/dev, evaluate based on query patterns and cost constraints.",
					"properties": map[string]interface{}{
						"type": map[string]interface{}{"type": "string", "description": "Remote storage type: 'DROP_REPLICA_FOR_NONACTIVE_SHARDS'. Use for Production - Cost optimized to reduce storage costs."},
					},
				},
				// Warm instance selection for time-series workloads
				"warmInstanceType":       map[string]interface{}{"type": "string", "description": "Override warm instance type selection for warm retention tier. UltraWarm options: 'ultrawarm1.medium.search' (1.5TB cache) or 'ultrawarm1.large.search' (20TB cache). OI2 options (requires OpenSearch Optimized hot nodes): 'oi2.xlarge.search', 'oi2.2xlarge.search', 'oi2.4xlarge.search', 'oi2.8xlarge.search', 'oi2.16xlarge.search'. If not specified, auto-selects based on storage size."},
				"autoSelectWarmInstance": map[string]interface{}{"type": "boolean", "description": "Enable automatic warm instance selection based on storage requirements (default: true). Set to false to use warmInstanceType override."},
			},
		},
	},
}
var ServerlessRequestSchema = map[string]interface{}{
	"type":        "object",
	"description": "Parameters for estimating serverless v2 OpenSearch collection costs. Ingest is required, plus optional search, timeSeries, and/or vector workloads.",
	"properties": map[string]interface{}{
		"ingest": map[string]interface{}{
			"type":        "object",
			"description": "Ingestion workload configuration (required)",
			"properties": map[string]interface{}{
				"minIndexingRate": map[string]interface{}{"type": "number", "description": "Minimum indexing rate in GB/hour"},
				"maxIndexingRate": map[string]interface{}{"type": "number", "description": "Maximum indexing rate in GB/hour"},
				"timePerDayAtMax": map[string]interface{}{"type": "number", "description": "Hours per day at maximum indexing rate"},
				"minOCU":          map[string]interface{}{"type": "number", "description": "Minimum OCU for ingestion"},
				"maxOCU":          map[string]interface{}{"type": "number", "description": "Maximum OCU for ingestion"},
				"OCUHoursADay":    map[string]interface{}{"type": "number", "description": "OCU hours per day for ingestion"},
				"replicas":        map[string]interface{}{"type": "integer", "description": "Number of replicas for ingestion"},
			},
		},
		"search": map[string]interface{}{
			"type":        "object",
			"description": "Search workload configuration (optional)",
			"properties": map[string]interface{}{
				"collectionSize":  map[string]interface{}{"type": "number", "description": "Collection size in GB"},
				"replicas":        map[string]interface{}{"type": "integer", "description": "Number of replicas"},
				"minQueryRate":    map[string]interface{}{"type": "integer", "description": "Minimum queries per hour"},
				"maxQueryRate":    map[string]interface{}{"type": "integer", "description": "Maximum queries per hour"},
				"hoursAtMaxRate":  map[string]interface{}{"type": "integer", "description": "Hours per day at maximum query rate"},
				"derivedSource":   map[string]interface{}{"type": "boolean", "description": "Enable derived source for ~25% storage reduction"},
				"zstdCompression": map[string]interface{}{"type": "boolean", "description": "Enable ZSTD compression for ~15% storage reduction"},
				"minOCU":          map[string]interface{}{"type": "integer", "description": "Minimum OCU for search"},
				"maxOCU":          map[string]interface{}{"type": "integer", "description": "Maximum OCU for search"},
				"OCUHoursADay":    map[string]interface{}{"type": "integer", "description": "OCU hours per day for search"},
			},
		},
		"timeSeries": map[string]interface{}{
			"type":        "object",
			"description": "Time-series workload configuration (optional)",
			"properties": map[string]interface{}{
				"dailyIndexSize":  map[string]interface{}{"type": "number", "description": "Daily index size in GB"},
				"replicas":        map[string]interface{}{"type": "integer", "description": "Number of replicas"},
				"daysInHot":       map[string]interface{}{"type": "integer", "description": "Days to keep data in hot storage"},
				"daysInWarm":      map[string]interface{}{"type": "integer", "description": "Days to keep data in warm storage"},
				"minQueryRate":    map[string]interface{}{"type": "integer", "description": "Minimum queries per hour"},
				"maxQueryRate":    map[string]interface{}{"type": "integer", "description": "Maximum queries per hour"},
				"hoursAtMaxRate":  map[string]interface{}{"type": "integer", "description": "Hours per day at maximum query rate"},
				"derivedSource":   map[string]interface{}{"type": "boolean", "description": "Enable derived source for ~30% storage reduction"},
				"zstdCompression": map[string]interface{}{"type": "boolean", "description": "Enable ZSTD compression for ~20% storage reduction"},
				"minOCU":          map[string]interface{}{"type": "integer", "description": "Minimum OCU for time-series"},
				"maxOCU":          map[string]interface{}{"type": "integer", "description": "Maximum OCU for time-series"},
				"OCUHoursADay":    map[string]interface{}{"type": "integer", "description": "OCU hours per day for time-series"},
				"hotIndexSize":    map[string]interface{}{"type": "number", "description": "Hot index size in GB"},
				"warmIndexSize":   map[string]interface{}{"type": "number", "description": "Warm index size in GB"},
			},
		},
		"vector": map[string]interface{}{
			"type":        "object",
			"description": "Vector search workload configuration (optional)",
			"properties": map[string]interface{}{
				"size":                       map[string]interface{}{"type": "number", "description": "Vector data size in GB"},
				"replicas":                   map[string]interface{}{"type": "integer", "description": "Number of replicas"},
				"vectorMemoryCircuitBreaker": map[string]interface{}{"type": "integer", "description": "Memory circuit breaker percentage"},
				"PQEdges":                    map[string]interface{}{"type": "integer", "description": "PQ edges for vector engine"},
				"segments":                   map[string]interface{}{"type": "integer", "description": "Number of segments"},
				"vectorEngineType":           map[string]interface{}{"type": "string", "description": "Vector engine type: hnsw, hnswfp16, hnswbv, ivf, ivfpq, hnswpq"},
				"vectorCount":                map[string]interface{}{"type": "integer", "description": "Total number of vectors"},
				"dimensionsCount":            map[string]interface{}{"type": "integer", "description": "Vector dimensions"},
				"maxEdges":                   map[string]interface{}{"type": "integer", "description": "Maximum edges in HNSW graph"},
				"subVectors":                 map[string]interface{}{"type": "integer", "description": "Sub-vectors for IVFPQ"},
				"nlist":                      map[string]interface{}{"type": "integer", "description": "Number of clusters for IVF"},
				"codeSize":                   map[string]interface{}{"type": "integer", "description": "Code size for PQ methods"},
				"onDisk":                     map[string]interface{}{"type": "boolean", "description": "Enable on-disk mode with memory compression for uncompressed engines (HNSW, IVF). provides highest savings where the latency is slightly slower. make this as default."},
				"compressionLevel":           map[string]interface{}{"type": "integer", "description": "Compression level for on-disk mode. Valid values: 2, 4, 8, 16, 32. default value: 32. For Production - Performant use 2-4 for minimal performance impact. For Production - Balanced use 8-16. For Production - Cost optimized, use 32 for maximum memory savings."},
				"derivedSource":              map[string]interface{}{"type": "boolean", "description": "Enable derived source for ~30% storage reduction on non-vector document data"},
				"zstdCompression":            map[string]interface{}{"type": "boolean", "description": "Enable ZSTD compression for ~20% storage reduction on non-vector document data"},
				"documentSize":               map[string]interface{}{"type": "integer", "description": "Document size in bytes (legacy)"},
				"incrementHint":              map[string]interface{}{"type": "integer", "description": "Increment hint (legacy)"},
				"replica":                    map[string]interface{}{"type": "integer", "description": "Replica count (legacy)"},
				"indexOCU":                   map[string]interface{}{"type": "number", "description": "Index OCU (calculated)"},
				"searchOCU":                  map[string]interface{}{"type": "number", "description": "Search OCU (calculated)"},
				"collectionSize":             map[string]interface{}{"type": "number", "description": "Collection size (calculated)"},
				"vectorGraphSizeInMemory":    map[string]interface{}{"type": "number", "description": "Vector graph size in memory (calculated)"},
				"config":                     map[string]interface{}{"type": "string", "description": "Preset configuration: 'dev' or 'production'"},
			},
		},
		"region":     map[string]interface{}{"type": "string", "description": "AWS region for the serverless collection"},
		"edp":        map[string]interface{}{"type": "number", "description": "Enterprise discount percentage"},
		"redundancy": map[string]interface{}{"type": "boolean", "description": "Enable redundancy for multi-AZ deployment. It can be disabled for non production environments or when there is no need for high availability (default: true)"},
	},
	"required": []string{"ingest", "region"},
}
