# Elastic docker registry does not seem to include 2.x versions and thus being pulled from docker hub
elasticsearch:
  imageTag: "2.4.5"
  image: "elasticsearch"
  antiAffinity: "soft"
  esJavaOpts: "-Xmx128m -Xms128m"
  protocol: http
  replicas: 1 # Set replicas to the number of nodes you want in the cluster (e.g., 3)
  createCert: false
  sysctlInitContainer:
    enabled: false
  esConfig:
    elasticsearch.yml: |
      bootstrap.system_call_filter: false
      xpack.security.enabled: false
      network.host: 0.0.0.0
  extraEnvs:
    - name: "cluster.initial_master_nodes" # Replace this setting that is added by chart with "" since this setting is not supported in ES 2.x
      value: ""
    - name: "node.roles" # Replace this setting that is added by chart with "" since this setting is not supported in ES 2.x
      value: ""
    - name: "path.repo"
      value: "/snapshot"
  extraVolumes:
    - name: snapshot-volume
      persistentVolumeClaim:
        claimName: snapshot-volume-pvc  # Should match existing snapshot volume PVC
  extraVolumeMounts:
    - name: snapshot-volume
      mountPath: /snapshot