elasticsearch:
  imageTag: "8.18.0"
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  replicas: 1 # Set replicas to the number of nodes you want in the cluster
  createCert: false
  persistence:
    enabled: false
  roles: [] # This is necessary to remove 'cluster.initial_master_nodes=elasticsearch-master-0' which causes issue for a single node cluster
  esConfig:
    elasticsearch.yml: |
      cluster.name: "elasticsearch-cluster"
      network.host: 0.0.0.0  
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
  extraEnvs:
    - name: "node.roles"
      value: "master,data,data_content,data_hot,data_warm,data_cold,ingest,ml,remote_cluster_client,transform"
    - name: "discovery.seed_hosts" # Remove this setting for single node cluster to prevent warning
      value: "[]"
    - name: "path.repo"
      value: "/snapshot"
  extraVolumes:
    - name: snapshot-volume
      persistentVolumeClaim:
        claimName: snapshot-volume-pvc  # Should match existing snapshot volume PVC
  extraVolumeMounts:
    - name: snapshot-volume
      mountPath: /snapshot