conditionalPackageInstalls:
  localstack: false

cloudProvider: gcp

gcp:
  project: ""
  serviceAccountEmail: ""

logs:
  sharedLogsVolume:
    enabled: false

defaultBucketConfiguration:
  useLocalStack: false
  create: false

gcsBucketConfiguration:
  create: false

charts:
  argo-workflows:
    values:
      artifactRepository:
        s3: null
        gcs:
          keyFormat: "argo-artifacts/{{workflow.name}}/{{pod.name}}"
  fluent-bit:
    values:
      extraVolumes:
        - name: logs-pv
          emptyDir: {}
        - name: lua-scripts
          configMap:
            name: fluentbit-lua-scripts
      extraVolumeMounts:
        - name: logs-pv
          mountPath: /shared_logs
        - name: lua-scripts
          mountPath: /fluentbit/scripts
          readOnly: true
