apiVersion: v2
name: migration-assistant
version: 0.1.0
type: application
appVersion: "1.16.0"
dependencies:
  - name: migration-console
    version: "0.1.0"
    repository: "file://../../components/migrationConsole"

  - name: bulk-document-loader
    condition: conditionalPackageInstalls.bulkLoader
    version: "0.1.0"
    repository: "file://../../components/bulkLoad"

  - name: capture-proxy
    condition: conditionalPackageInstalls.proxy
    version: "0.1.0"
    repository: "file://../../components/captureProxy"
  - name: kafka-cluster
    alias: captured-traffic-kafka-cluster
    condition: conditionalPackageInstalls.kafka
    version: "0.1.0"
    repository: "file://../../sharedResources/baseKafkaCluster"
  - name: replayer
    condition: conditionalPackageInstalls.replayer
    version: "0.1.0"
    repository: "file://../../components/replayer"

  - name: shared-configs
    version: "0.1.0"
    repository: "file://../../sharedResources/sharedConfigs"

#  - name: otel-collector
#    version: 1.2.2
#    repository:

  - name: grafana
    condition: conditionalPackageInstalls.grafana
    version: "8.5.0"
    repository: "https://grafana.github.io/helm-charts"
  - name: prometheus
    condition: conditionalPackageInstalls.prometheus
    version: "25.27.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: jaeger
    condition: conditionalPackageInstalls.jaeger
    version: "3.2.0"
    repository: "https://jaegertracing.github.io/helm-charts"
