/* tslint:disable */
/* eslint-disable */
/**
 * Migration Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthStatus } from './HealthStatus';
import {
    HealthStatusFromJSON,
    HealthStatusFromJSONTyped,
    HealthStatusToJSON,
} from './HealthStatus';

/**
 * 
 * @export
 * @interface HealthApiResponse
 */
export interface HealthApiResponse {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HealthApiResponse
     */
    checks: { [key: string]: string; };
    /**
     * 
     * @type {HealthStatus}
     * @memberof HealthApiResponse
     */
    status: HealthStatus;
}

/**
 * Check if a given object implements the HealthApiResponse interface.
 */
export function instanceOfHealthApiResponse(value: object): boolean {
    if (!('checks' in value)) return false;
    if (!('status' in value)) return false;
    return true;
}

export function HealthApiResponseFromJSON(json: any): HealthApiResponse {
    return HealthApiResponseFromJSONTyped(json, false);
}

export function HealthApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'checks': json['checks'],
        'status': HealthStatusFromJSON(json['status']),
    };
}

export function HealthApiResponseToJSON(value?: HealthApiResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'checks': value['checks'],
        'status': HealthStatusToJSON(value['status']),
    };
}

