/* tslint:disable */
/* eslint-disable */
/**
 * Migration Assistant API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HealthStatus = {
    Ok: 'ok',
    Error: 'error'
} as const;
export type HealthStatus = typeof HealthStatus[keyof typeof HealthStatus];


export function instanceOfHealthStatus(value: any): boolean {
    return Object.values(HealthStatus).includes(value);
}

export function HealthStatusFromJSON(json: any): HealthStatus {
    return HealthStatusFromJSONTyped(json, false);
}

export function HealthStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthStatus {
    return json as HealthStatus;
}

export function HealthStatusToJSON(value?: HealthStatus | null): any {
    return value as any;
}

