/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Migration Assistant API
 * OpenAPI spec version: 0.0.1
 */
import type { HealthApiResponseChecks } from './healthApiResponseChecks';
import type { HealthStatus } from './healthStatus';

export interface HealthApiResponse {
  checks: HealthApiResponseChecks;
  status: HealthStatus;
}
