/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Migration Assistant API
 * OpenAPI spec version: 0.0.1
 */

export type HealthStatus = typeof HealthStatus[keyof typeof HealthStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthStatus = {
  ok: 'ok',
  error: 'error',
} as const;
