receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :4317
      http:
        endpoint: :4318
processors:
  batch:
    timeout: 10s
    send_batch_size: 8192
    send_batch_max_size: 10000
  probabilistic_sampler/traces:
    sampling_percentage: ${env:TRACE_SAMPLING_PERCENTAGE:-1}
extensions:
  zpages:
    endpoint: :55679
  pprof:
    endpoint: :1888
  health_check:
    endpoint: :13133
exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  prometheus:
    endpoint: "0.0.0.0:8889"
    send_timestamps: true
    metric_expiration: 5m
    enable_open_metrics: true
  otlp/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
    endpoint: jaeger:4317
    tls:
      insecure: true
service:
  extensions: [zpages, pprof, health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler/traces, batch]
      exporters: [debug, otlp/jaeger]
    logs:
      receivers: [otlp]
      processors:
      exporters: [debug]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
