/**
 * JSON Schema Type Definitions
 * 
 * Type definitions for JSON Schema (draft-07) with UI metadata extensions.
 * These types are used by the OpenAPI parser to extract field configurations
 * from JSON Schema generated by @asteasolutions/zod-to-openapi.
 */

/**
 * JSON Schema type names
 */
export type JSONSchema7TypeName =
    | 'string'
    | 'number'
    | 'integer'
    | 'boolean'
    | 'object'
    | 'array'
    | 'null';

/**
 * JSON Schema definition with UI metadata extensions
 * 
 * This interface extends the standard JSON Schema draft-07 with
 * custom properties that flow through from Zod's .meta() annotations.
 */
export interface JSONSchema7 {
    // ============================================
    // JSON Schema Standard Properties
    // ============================================

    /** Schema identifier */
    $id?: string;

    /** Reference to another schema */
    $ref?: string;

    /** JSON Schema version */
    $schema?: string;

    /** Comment for documentation */
    $comment?: string;

    // ============================================
    // Type
    // ============================================

    /** Type of the value */
    type?: JSONSchema7TypeName | JSONSchema7TypeName[];

    // ============================================
    // Metadata
    // ============================================

    /** Title for the schema */
    title?: string;

    /** Description of the schema */
    description?: string;

    /** Default value */
    default?: unknown;

    /** Example values */
    examples?: unknown[];

    // ============================================
    // String Validation
    // ============================================

    /** Minimum string length */
    minLength?: number;

    /** Maximum string length */
    maxLength?: number;

    /** Regex pattern for validation */
    pattern?: string;

    /** String format (e.g., 'email', 'uri', 'date-time') */
    format?: string;

    // ============================================
    // Number Validation
    // ============================================

    /** Minimum value (inclusive) */
    minimum?: number;

    /** Maximum value (inclusive) */
    maximum?: number;

    /** Minimum value (exclusive) */
    exclusiveMinimum?: number;

    /** Maximum value (exclusive) */
    exclusiveMaximum?: number;

    /** Value must be a multiple of this number */
    multipleOf?: number;

    // ============================================
    // Object Validation
    // ============================================

    /** Property schemas for object type */
    properties?: Record<string, JSONSchema7>;

    /** Required property names */
    required?: string[];

    /** Schema for additional properties (or false to disallow) */
    additionalProperties?: boolean | JSONSchema7;

    /** Minimum number of properties */
    minProperties?: number;

    /** Maximum number of properties */
    maxProperties?: number;

    /** Pattern-based property schemas */
    patternProperties?: Record<string, JSONSchema7>;

    /** Property dependencies */
    dependencies?: Record<string, JSONSchema7 | string[]>;

    /** Property names schema */
    propertyNames?: JSONSchema7;

    // ============================================
    // Array Validation
    // ============================================

    /** Schema for array items */
    items?: JSONSchema7 | JSONSchema7[];

    /** Schema for additional items (when items is an array) */
    additionalItems?: boolean | JSONSchema7;

    /** Minimum number of items */
    minItems?: number;

    /** Maximum number of items */
    maxItems?: number;

    /** Whether items must be unique */
    uniqueItems?: boolean;

    /** Schema that at least one item must match */
    contains?: JSONSchema7;

    // ============================================
    // Composition
    // ============================================

    /** All schemas must match */
    allOf?: JSONSchema7[];

    /** At least one schema must match */
    anyOf?: JSONSchema7[];

    /** Exactly one schema must match */
    oneOf?: JSONSchema7[];

    /** Schema must not match */
    not?: JSONSchema7;

    // ============================================
    // Conditional
    // ============================================

    /** Condition schema */
    if?: JSONSchema7;

    /** Schema to apply if condition matches */
    then?: JSONSchema7;

    /** Schema to apply if condition doesn't match */
    else?: JSONSchema7;

    // ============================================
    // Enum & Const
    // ============================================

    /** Allowed values */
    enum?: unknown[];

    /** Exact value required */
    const?: unknown;

    // ============================================
    // UI Metadata Extensions (from Zod .meta())
    // ============================================

    /** Placeholder text for input fields */
    placeholder?: string;

    /** Constraint text shown below the field */
    constraintText?: string;

    /** Help text shown in a tooltip */
    helpText?: string;

    /** Explicit field type override */
    fieldType?:
        | 'text'
        | 'number'
        | 'select'
        | 'multiselect'
        | 'checkbox'
        | 'toggle'
        | 'textarea'
        | 'password'
        | 'url'
        | 'email'
        | 'radio'
        | 'tiles'
        | 'slider'
        | 'tags'
        | 'record'
        | 'array'
        | 'object'
        | 'union';

    /** Options for select/multiselect/radio/tiles fields */
    options?: Array<{
        label: string;
        value: string;
        description?: string;
        disabled?: boolean;
        iconName?: string;
        tags?: string[];
    }>;

    /** Whether the field is disabled */
    disabled?: boolean;

    /** Whether the field is read-only */
    readOnly?: boolean;

    /** Sort order within a group */
    order?: number;

    /** Group ID for organizing fields */
    group?: string;

    /** Whether the field is hidden */
    hidden?: boolean;

    /** Whether the field is advanced */
    advanced?: boolean;

    /** Column span for grid layouts */
    colSpan?: 1 | 2;

    /** Custom error messages */
    errorMessages?: Record<string, string>;

    /** Conditional visibility */
    showWhen?: {
        field: string;
        value: unknown;
        operator?: 'eq' | 'neq' | 'in' | 'notIn';
    };

    /** Title for items in records/arrays */
    itemTitle?: string;

    /** Text for add button in records/arrays */
    addButtonText?: string;

    /** Discriminator value for union variants */
    discriminator?: string;

    /** Labels for union variants */
    variantLabels?: Record<string, string>;

    /** Example value for form initialization (from Zod .meta()) */
    exampleValue?: unknown;

    // ============================================
    // Index Signature for Additional Properties
    // ============================================

    /** Allow additional properties from JSON Schema extensions */
    [key: string]: unknown;
}

/**
 * OpenAPI Schema Object (subset relevant for form generation)
 * 
 * This is a simplified version of the OpenAPI Schema Object that
 * includes the properties we need for form generation.
 */
export interface OpenAPISchema extends Omit<JSONSchema7, 'discriminator'> {
    /** Discriminator for polymorphism (OpenAPI style - different from UI metadata discriminator) */
    discriminator?: {
        propertyName: string;
        mapping?: Record<string, string>;
    } | string; // Can be either OpenAPI style object or simple string from UI metadata

    /** Whether the value can be null (OpenAPI 3.0 style) */
    nullable?: boolean;

    /** Deprecation flag */
    deprecated?: boolean;

    /** XML representation options */
    xml?: {
        name?: string;
        namespace?: string;
        prefix?: string;
        attribute?: boolean;
        wrapped?: boolean;
    };

    /** External documentation */
    externalDocs?: {
        description?: string;
        url: string;
    };
}

/**
 * OpenAPI Components Object (for $ref resolution)
 */
export interface OpenAPIComponents {
    schemas?: Record<string, OpenAPISchema>;
}

/**
 * Root OpenAPI Document (subset for schema extraction)
 */
export interface OpenAPIDocument {
    openapi: string;
    info: {
        title: string;
        version: string;
        description?: string;
    };
    components?: OpenAPIComponents;
}

/**
 * Type guard to check if a value is a JSONSchema7 object
 */
export function isJSONSchema7(value: unknown): value is JSONSchema7 {
    return (
        typeof value === 'object' &&
        value !== null &&
        !Array.isArray(value)
    );
}

/**
 * Type guard to check if schema has properties (is an object schema)
 */
export function isObjectSchema(schema: JSONSchema7): boolean {
    return schema.type === 'object' || schema.properties !== undefined;
}

/**
 * Type guard to check if schema is an array schema
 */
export function isArraySchema(schema: JSONSchema7): boolean {
    return schema.type === 'array' || schema.items !== undefined;
}

/**
 * Type guard to check if schema is a union (anyOf/oneOf)
 */
export function isUnionSchema(schema: JSONSchema7): boolean {
    return (
        (schema.anyOf !== undefined && schema.anyOf.length > 0) ||
        (schema.oneOf !== undefined && schema.oneOf.length > 0)
    );
}

/**
 * Type guard to check if schema is an enum
 */
export function isEnumSchema(schema: JSONSchema7): boolean {
    return schema.enum !== undefined && schema.enum.length > 0;
}

/**
 * Type guard to check if schema has a const value
 */
export function isConstSchema(schema: JSONSchema7): boolean {
    return schema.const !== undefined;
}
