apiVersion: v1
kind: ConfigMap
metadata:
  name: log-aggregation-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1" # Make accessible earlier for charts that mount
data:
  # plain or template
  OUTPUT_FORMAT:
    {{ if eq .Values.logs.format "application" }}template{{ else }}plain{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-lua-scripts
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1" # Make accessible earlier for charts that mount
data:
  trim.lua: |
    function trim_log(tag, timestamp, record)
        if record["log_processed"] then
            if record["log_processed"]["msg"] then
                record["orig_log"] = record["log"]
                record["log"] = record["log_processed"]["msg"]
            end
            if record["log_processed"]["level"] then
                record["level"] = record["log_processed"]["level"]
            end
        elseif record["log"] then
            if record["msg"] then
                record["orig_log"] = record["log"]
                record["log"] = record["msg"]
            end
            record["log"] = string.gsub(record["log"], "(\r?\n)$", "")
        end
        return 1, timestamp, record
    end
