apiVersion: v1
kind: ConfigMap
metadata:
  name: log-aggregation-config
  namespace: {{ .Release.Namespace }}
data:
  # plain or template
  OUTPUT_FORMAT:
    {{ if eq .Values.logs.format "application" }}template{{ else }}plain{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-lua-scripts
data:
  trim.lua: |
    function trim_log(tag, timestamp, record)
        local log = record["log"]
        if log then
            log = string.gsub(log, "(\r?\n)$", "")
            record["log"] = log
        end
        return 1, timestamp, record
    end
