apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-image-config
  labels:
    # Necessary label for Argo to pull values from a configmap
    workflows.argoproj.io/configmap-type: Parameter

data:
  captureProxyImage: "{{ include "migration.image" (dict "root" . "image" .Values.images.captureProxy) }}"
  captureProxyPullPolicy: "{{ .Values.images.captureProxy.pullPolicy }}"
  trafficReplayerImage: "{{ include "migration.image" (dict "root" . "image" .Values.images.trafficReplayer) }}"
  trafficReplayerPullPolicy: "{{ .Values.images.trafficReplayer.pullPolicy }}"
  reindexFromSnapshotImage: "{{ include "migration.image" (dict "root" . "image" .Values.images.reindexFromSnapshot) }}"
  reindexFromSnapshotPullPolicy: "{{ .Values.images.reindexFromSnapshot.pullPolicy }}"
  migrationConsoleImage: "{{ include "migration.image" (dict "root" . "image" .Values.images.migrationConsole) }}"
  migrationConsolePullPolicy: "{{ .Values.images.migrationConsole.pullPolicy }}"
  coordinatorClusterImage: "{{ .Values.images.coordinatorCluster.repository }}:{{ .Values.images.coordinatorCluster.tag }}"
  coordinatorClusterPullPolicy: "{{ .Values.images.coordinatorCluster.pullPolicy }}"
