import type { components } from "../api/schema.generated";


export type ManageSnapshot = components["schemas"]["ManageSnapshotV1"];
export type ConfigDraft = components["schemas"]["ConfigDraftV1"];


export const manageSnapshot: ManageSnapshot = {
  formatVersion: 1,
  revision: "snapshot-1",
  observedAt: "2026-08-12T16:00:00Z",
  namespace: "ma",
  workflowName: "migration",
  workflow: {
    name: "migration",
    phase: "Running",
    startedAt: "2026-08-12T15:55:00Z",
    finishedAt: null,
  },
  rootIds: ["section:Sources", "section:Live Traffic Migration"],
  nodes: {
    "section:Sources": {
      id: "section:Sources",
      revision: "sources-section-1",
      parentId: null,
      childIds: ["group:Sources:Sources"],
      kind: "section",
      label: "Sources",
      description: null,
      status: "ok",
      phase: null,
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
    "group:Sources:Sources": {
      id: "group:Sources:Sources",
      revision: "sources-group-1",
      parentId: "section:Sources",
      childIds: [],
      kind: "group",
      label: "Sources",
      description: null,
      status: "ok",
      phase: null,
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
    "section:Live Traffic Migration": {
      id: "section:Live Traffic Migration",
      revision: "section-1",
      parentId: null,
      childIds: [
        "group:Live Traffic Migration:Capture",
        "group:Live Traffic Migration:Replay",
      ],
      kind: "section",
      label: "Live Traffic Migration",
      description: null,
      status: "warning",
      phase: null,
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
    "group:Live Traffic Migration:Capture": {
      id: "group:Live Traffic Migration:Capture",
      revision: "capture-group-1",
      parentId: "section:Live Traffic Migration",
      childIds: ["resource:captureproxies:capture"],
      kind: "group",
      label: "Capture",
      description: null,
      status: "warning",
      phase: null,
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
    "resource:captureproxies:capture": {
      id: "resource:captureproxies:capture",
      revision: "capture-1",
      parentId: "group:Live Traffic Migration:Capture",
      childIds: [],
      kind: "resource",
      label: "capture",
      description: "captureproxies/capture",
      status: "warning",
      phase: "Ready",
      valueSummary: "1 change to submit",
      diagnostics: [
        {
          severity: "warning",
          message: "Load balancer is unavailable in this cluster",
          path: ["capture", "serviceType"],
          source: "cluster",
        },
      ],
      capabilities: [
        {
          kind: "edit",
          editTargetId: "edit:workflowConfiguration",
          label: "Edit capture",
        },
        {
          kind: "logs",
          logTargetId: "logs:captureproxies:capture",
          label: "Logs for capture",
        },
        {
          kind: "reset",
          resetTargetId: "reset:captureproxies:capture",
          label: "Reset capture",
        },
      ],
      details: [
        { label: "Phase", value: "Ready", kind: "phase" },
        { label: "listenPort", value: 9201, kind: "spec" },
      ],
      relationships: [
        {
          kind: "runtime-dependency",
          direction: "required-by",
          targetId: "resource:trafficreplays:replay",
          targetName: "replay",
          targetPlural: "trafficreplays",
          targetPhase: "Running",
          targetStatus: "running",
        },
      ],
      comparisons: [
        {
          path: "serviceType",
          label: "Service type",
          deployed: { present: true, value: "LoadBalancer", provenance: null },
          submitted: { present: true, value: "LoadBalancer", provenance: null },
          pending: { present: true, value: "ClusterIP", provenance: null },
          submittedChanged: false,
          pendingChanged: true,
        },
      ],
      resourcePlural: "captureproxies",
      resourceName: "capture",
    },
    "group:Live Traffic Migration:Replay": {
      id: "group:Live Traffic Migration:Replay",
      revision: "replay-group-1",
      parentId: "section:Live Traffic Migration",
      childIds: ["resource:trafficreplays:replay"],
      kind: "group",
      label: "Replay",
      description: null,
      status: "running",
      phase: null,
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
    "resource:trafficreplays:replay": {
      id: "resource:trafficreplays:replay",
      revision: "replay-1",
      parentId: "group:Live Traffic Migration:Replay",
      childIds: ["workflow-step:resource:trafficreplays:replay:deploy"],
      kind: "resource",
      label: "replay",
      description: "trafficreplays/replay",
      status: "running",
      phase: "Running",
      valueSummary: "Running",
      diagnostics: [],
      capabilities: [
        {
          kind: "edit",
          editTargetId: "edit:trafficreplays:replay",
          label: "Edit replay",
        },
      ],
      details: [{ label: "Phase", value: "Running", kind: "phase" }],
      relationships: [
        {
          kind: "runtime-dependency",
          direction: "requires",
          targetId: "resource:captureproxies:capture",
          targetName: "capture",
          targetPlural: "captureproxies",
          targetPhase: "Ready",
          targetStatus: "ok",
        },
      ],
      comparisons: [],
      resourcePlural: "trafficreplays",
      resourceName: "replay",
    },
    "workflow-step:resource:trafficreplays:replay:deploy": {
      id: "workflow-step:resource:trafficreplays:replay:deploy",
      revision: "step-1",
      parentId: "resource:trafficreplays:replay",
      childIds: [],
      kind: "workflow-step",
      label: "Deploy replay",
      description: null,
      status: "running",
      phase: "Running",
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [
        {
          label: "Started",
          value: "2026-08-12T15:56:00Z",
          kind: "timestamp",
        },
      ],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
  },
  problems: [],
  stale: false,
  refreshError: null,
};


const zeroCounts = {
  required: 0,
  errors: 0,
  warnings: 0,
  changed: 0,
  gated: 0,
  blocked: 0,
};


export const configDraft: ConfigDraft = {
  baseRevision: "config-base-1",
  draftRevision: "config-draft-1",
  dirty: false,
  editState: {
    formatVersion: 1,
    provenance: {
      source: "pending-yaml",
      lossy: false,
      warnings: [],
    },
    validation: {
      valid: false,
      errors: ["One field requires attention."],
      diagnostics: [{
        severity: "warning",
        message: "Review the transform ConfigMap key.",
        path: ["traffic", "transform", "configMap"],
      }],
    },
    nodes: [{
      id: "edit:sourceClusters",
      path: ["sourceClusters"],
      label: "Source clusters",
      valueKind: "record",
      presence: "required",
      essential: true,
      inputHint: {
        kind: "record",
        addLabel: "source cluster",
        keyPattern: "^[a-z0-9-]+$",
        message: "Use a Kubernetes-compatible name.",
      },
      status: "warning",
      statusCounts: { ...zeroCounts, warnings: 1 },
      diagnostics: [],
      children: [{
        id: "edit:sourceClusters.legacy",
        path: ["sourceClusters", "legacy"],
        label: "legacy",
        valueKind: "object",
        presence: "required",
        removable: true,
        status: "warning",
        statusCounts: { ...zeroCounts, warnings: 1 },
        diagnostics: [],
        children: [
          {
            id: "edit:sourceClusters.legacy.endpoint",
            path: ["sourceClusters", "legacy", "endpoint"],
            label: "Endpoint: https://legacy.example.com:9200",
            value: "https://legacy.example.com:9200",
            valueAuthored: true,
            valueKind: "scalar",
            valueType: "string",
            presence: "required",
            required: true,
            status: "ok",
            statusCounts: zeroCounts,
            inputHint: {
              kind: "text",
              pattern: "^https://",
              message: "Use an HTTPS endpoint.",
            },
            diagnostics: [],
            children: [],
          },
          {
            id: "edit:sourceClusters.legacy.timeout",
            path: ["sourceClusters", "legacy", "timeout"],
            label: "Timeout: 30",
            value: 30,
            valueDefaulted: true,
            valueKind: "scalar",
            valueType: "number",
            presence: "optional",
            status: "ok",
            statusCounts: zeroCounts,
            effectiveDefault: {
              label: "runtime timeout",
              description: "Generated from the standard runtime profile.",
            },
            diagnostics: [],
            children: [],
          },
          {
            id: "edit:sourceClusters.legacy.allowInsecure",
            path: ["sourceClusters", "legacy", "allowInsecure"],
            label: "Allow insecure: false",
            value: false,
            valueAuthored: true,
            valueKind: "boolean",
            valueType: "boolean",
            presence: "optional",
            status: "ok",
            statusCounts: zeroCounts,
            diagnostics: [],
            children: [],
          },
          {
            id: "edit:sourceClusters.legacy.authConfig",
            path: ["sourceClusters", "legacy", "authConfig"],
            label: "Authentication: < basic >",
            value: "basic",
            valueAuthored: true,
            valueKind: "union",
            presence: "optional",
            status: "ok",
            statusCounts: zeroCounts,
            variants: [
              {
                label: "default (none)",
                value: "unset",
                description: "Use no authentication.",
              },
              {
                label: "basic",
                value: "basic",
                description: "HTTP basic authentication.",
              },
              {
                label: "sigv4",
                value: "sigv4",
                description: "AWS request signing.",
              },
            ],
            diagnostics: [],
            children: [{
              id: "edit:sourceClusters.legacy.authConfig.basic.secretName",
              path: [
                "sourceClusters",
                "legacy",
                "authConfig",
                "basic",
                "secretName",
              ],
              label: "Credentials secret: source-creds",
              value: "source-creds",
              valueAuthored: true,
              valueKind: "scalar",
              valueType: "string",
              presence: "required",
              required: true,
              status: "ok",
              statusCounts: zeroCounts,
              description: "Kubernetes Secret containing the HTTP credentials.",
              diagnostics: [],
              children: [],
            }],
          },
          {
            id: "edit:sourceClusters.legacy.advanced",
            path: ["sourceClusters", "legacy", "advanced"],
            label: "Advanced setting: quiet",
            value: "quiet",
            valueAuthored: true,
            valueKind: "scalar",
            valueType: "string",
            presence: "optional",
            expert: true,
            status: "ok",
            statusCounts: zeroCounts,
            diagnostics: [],
            children: [],
          },
          {
            id: "edit:sourceClusters.legacy.snapshotName",
            path: ["sourceClusters", "legacy", "snapshotName"],
            label: "Snapshot: nightly",
            value: "nightly",
            valueAuthored: true,
            valueKind: "scalar",
            valueType: "string",
            presence: "required",
            required: true,
            status: "ok",
            statusCounts: zeroCounts,
            inputHint: {
              kind: "reference",
              sourcePath: ["sourceClusters", "legacy", "snapshots"],
              allowCustom: false,
              options: [
                {
                  label: "nightly",
                  value: "nightly",
                  description: "Generated from the source snapshot definitions.",
                },
                {
                  label: "weekly",
                  value: "weekly",
                  description: "Generated from the source snapshot definitions.",
                },
              ],
            },
            diagnostics: [],
            children: [],
          },
        ],
      }, {
        id: "edit:sourceClusters:add",
        path: ["sourceClusters"],
        label: "+ Add source cluster",
        valueKind: "command",
        status: "ok",
        statusCounts: zeroCounts,
        inputHint: {
          kind: "text",
          pattern: "^[a-z0-9-]+$",
          message: "Use a Kubernetes-compatible name.",
        },
        command: {
          requiresName: true,
          editAdded: true,
          autoEditAdded: true,
        },
        diagnostics: [],
        children: [],
      }],
    }, {
      id: "edit:traffic",
      path: ["traffic"],
      label: "Live traffic migration",
      valueKind: "object",
      presence: "optional",
      essential: true,
      status: "warning",
      statusCounts: { ...zeroCounts, warnings: 1 },
      diagnostics: [],
      children: [{
        id: "edit:traffic.transform",
        path: ["traffic", "transform"],
        label: "Transform",
        valueKind: "object",
        presence: "optional",
        status: "warning",
        statusCounts: { ...zeroCounts, warnings: 1 },
        diagnostics: [],
        children: [{
          id: "edit:traffic.transform.configMap",
          path: ["traffic", "transform", "configMap"],
          label: "ConfigMap: transform-code",
          value: "transform-code",
          valueAuthored: true,
          valueKind: "scalar",
          valueType: "string",
          presence: "required",
          required: true,
          status: "warning",
          statusCounts: { ...zeroCounts, warnings: 1 },
          externalRef: {
            kind: "kubernetesResource",
            purpose: "file-ref-config-map",
            displayName: "Transform ConfigMap",
            description: "Choose a ConfigMap and one of its file keys.",
            selection: {
              target: "fileRefConfigMap",
              nameField: "configMap",
              pathField: "path",
            },
            k8s: {
              resourceTypes: [{
                group: "",
                version: "v1",
                kind: "ConfigMap",
                namespaced: true,
              }],
            },
            create: {
              label: "Transform ConfigMap",
              fields: [
                {
                  name: "name",
                  label: "ConfigMap name",
                  input: "name",
                  required: true,
                  validationIds: ["k8s-name"],
                },
                {
                  name: "key",
                  label: "Key",
                  input: "text",
                  required: true,
                  default: "transform.js",
                  validationIds: ["configmap-key"],
                },
                {
                  name: "contents",
                  label: "JavaScript",
                  input: "multilineText",
                  required: true,
                  validationIds: ["non-empty"],
                },
              ],
              output: {
                kind: "ConfigMap",
                data: {
                  "transform.js": {
                    fromField: "contents",
                  },
                },
              },
              apply: {
                target: "fileRefConfigMap",
                nameField: "name",
                pathField: "key",
              },
            },
          },
          diagnostics: [{
            severity: "warning",
            message: "Selected key is not present.",
            path: ["traffic", "transform", "configMap"],
          }],
          children: [],
        }, {
          id: "edit:traffic.transform.path",
          path: ["traffic", "transform", "path"],
          label: "Path: missing.js",
          value: "missing.js",
          valueAuthored: true,
          valueKind: "scalar",
          valueType: "string",
          presence: "required",
          required: true,
          status: "warning",
          statusCounts: { ...zeroCounts, warnings: 1 },
          diagnostics: [],
          children: [],
        }],
      }, {
        id: "edit:traffic.transforms",
        path: ["traffic", "transforms"],
        label: "Transforms: 0 items",
        value: [],
        valueAuthored: true,
        valueKind: "array",
        presence: "optional",
        status: "ok",
        statusCounts: zeroCounts,
        diagnostics: [],
        children: [{
          id: "edit:traffic.transforms:add",
          path: ["traffic", "transforms"],
          label: "+ Add transform",
          valueKind: "command",
          status: "ok",
          statusCounts: zeroCounts,
          command: {
            requiresName: false,
            editAdded: false,
            autoEditAdded: true,
          },
          diagnostics: [],
          children: [],
        }],
      }],
    }],
  },
};
