import type { components } from "../api/schema.generated";


export type ManageSnapshot = components["schemas"]["ManageSnapshotV1"];


export const manageSnapshot: ManageSnapshot = {
  formatVersion: 1,
  revision: "snapshot-1",
  observedAt: "2026-08-12T16:00:00Z",
  namespace: "ma",
  workflowName: "migration",
  workflow: {
    name: "migration",
    phase: "Running",
    startedAt: "2026-08-12T15:55:00Z",
    finishedAt: null,
  },
  rootIds: ["section:Live Traffic Migration"],
  nodes: {
    "section:Live Traffic Migration": {
      id: "section:Live Traffic Migration",
      revision: "section-1",
      parentId: null,
      childIds: [
        "group:Live Traffic Migration:Capture",
        "group:Live Traffic Migration:Replay",
      ],
      kind: "section",
      label: "Live Traffic Migration",
      description: null,
      status: "warning",
      phase: null,
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
    "group:Live Traffic Migration:Capture": {
      id: "group:Live Traffic Migration:Capture",
      revision: "capture-group-1",
      parentId: "section:Live Traffic Migration",
      childIds: ["resource:captureproxies:capture"],
      kind: "group",
      label: "Capture",
      description: null,
      status: "warning",
      phase: null,
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
    "resource:captureproxies:capture": {
      id: "resource:captureproxies:capture",
      revision: "capture-1",
      parentId: "group:Live Traffic Migration:Capture",
      childIds: [],
      kind: "resource",
      label: "capture",
      description: "captureproxies/capture",
      status: "warning",
      phase: "Ready",
      valueSummary: "1 change to submit",
      diagnostics: [
        {
          severity: "warning",
          message: "Load balancer is unavailable in this cluster",
          path: ["capture", "serviceType"],
          source: "cluster",
        },
      ],
      capabilities: [
        {
          kind: "edit",
          editTargetId: "edit:captureproxies:capture",
          label: "Edit capture",
        },
        {
          kind: "logs",
          logTargetId: "logs:captureproxies:capture",
          label: "Logs for capture",
        },
        {
          kind: "reset",
          resetTargetId: "reset:captureproxies:capture",
          label: "Reset capture",
        },
      ],
      details: [
        { label: "Phase", value: "Ready", kind: "phase" },
        { label: "listenPort", value: 9201, kind: "spec" },
      ],
      comparisons: [
        {
          path: "serviceType",
          label: "Service type",
          deployed: { present: true, value: "LoadBalancer", provenance: null },
          submitted: { present: true, value: "LoadBalancer", provenance: null },
          pending: { present: true, value: "ClusterIP", provenance: null },
          submittedChanged: false,
          pendingChanged: true,
        },
      ],
      resourcePlural: "captureproxies",
      resourceName: "capture",
    },
    "group:Live Traffic Migration:Replay": {
      id: "group:Live Traffic Migration:Replay",
      revision: "replay-group-1",
      parentId: "section:Live Traffic Migration",
      childIds: ["resource:trafficreplays:replay"],
      kind: "group",
      label: "Replay",
      description: null,
      status: "running",
      phase: null,
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
    "resource:trafficreplays:replay": {
      id: "resource:trafficreplays:replay",
      revision: "replay-1",
      parentId: "group:Live Traffic Migration:Replay",
      childIds: ["workflow-step:resource:trafficreplays:replay:deploy"],
      kind: "resource",
      label: "replay",
      description: "trafficreplays/replay",
      status: "running",
      phase: "Running",
      valueSummary: "Running",
      diagnostics: [],
      capabilities: [
        {
          kind: "edit",
          editTargetId: "edit:trafficreplays:replay",
          label: "Edit replay",
        },
      ],
      details: [{ label: "Phase", value: "Running", kind: "phase" }],
      comparisons: [],
      resourcePlural: "trafficreplays",
      resourceName: "replay",
    },
    "workflow-step:resource:trafficreplays:replay:deploy": {
      id: "workflow-step:resource:trafficreplays:replay:deploy",
      revision: "step-1",
      parentId: "resource:trafficreplays:replay",
      childIds: [],
      kind: "workflow-step",
      label: "Deploy replay",
      description: null,
      status: "running",
      phase: "Running",
      valueSummary: null,
      diagnostics: [],
      capabilities: [],
      details: [
        {
          label: "Started",
          value: "2026-08-12T15:56:00Z",
          kind: "timestamp",
        },
      ],
      comparisons: [],
      resourcePlural: null,
      resourceName: null,
    },
  },
  problems: [],
  stale: false,
  refreshError: null,
};
