source_cluster:
  endpoint: "http://elasticsearch-master:9200"
  allow_insecure: true
  version: "7.10.2"
  no_auth:
target_cluster:
  endpoint: "https://opensearch-cluster-master:9200"
  allow_insecure: true
  basic_auth:
    username: "admin"
    password: "myStrongPassword123!"
metrics_source:
  prometheus:
    endpoint: "http://prometheus:9090"
backfill:
  reindex_from_snapshot:
    k8s:
      namespace: "ma"
      deployment_name: "ma-bulk-document-loader"
replay:
  k8s:
    namespace: "ma"
    deployment_name: "ma-replayer"
snapshot:
  snapshot_name: "rfs-snapshot"
  fs:
    repo_path: "/snapshot"
  #otel_endpoint: "http://localhost:4317"
metadata_migration:
  from_snapshot:
  min_replicas: 0
  source_cluster_version: "ES_7.10"
  #otel_endpoint: "http://localhost:4317"
kafka:
  broker_endpoints: "captured-traffic-kafka-bootstrap:9092"
  standard: ""