# Exit Types
EXIT_TYPE_ABORT = 'Aborted'
EXIT_TYPE_FAILURE = 'Failed'
EXIT_TYPE_FAILURE_UNEXPECTED = 'FailedUnexpected'
EXIT_TYPE_FAILURE_UNHANDLED = 'FailedUnhandled'
EXIT_TYPE_SUCCESS = 'Succeeded'
EXIT_TYPES_FAILURE = [
    EXIT_TYPE_FAILURE,
    EXIT_TYPE_FAILURE_UNEXPECTED,
    EXIT_TYPE_FAILURE_UNHANDLED
]

# Upgrade Types
UPGRADE_STYLE_SNAPSHOT = "snapshot-restore"