apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-permissions
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kafka.strimzi.io"]  # Kafka's API group
    resources: ["kafkas"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-permissions-binding
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: app-permissions
  apiGroup: rbac.authorization.k8s.io